/**
 * This file is generated by FiOrdOs, a program licensed under GPL
 * by copyright holder Automatic Control Laboratory, ETH Zurich.
 * 
 * If you are interested in using this file commercially,
 * please contact the copyright holder.
 */

#ifndef EX2_SOLVER_H
#define EX2_SOLVER_H

#ifdef USE_REALTYPE_SINGLE
  typedef float realtype;
#else
  typedef double realtype;
#endif

/* <<< struct Params >>> */
#if defined(USE_PARAMSMODE_PTR)  && !(defined(MATLAB_MEX_FILE) || defined(RT))
#  define PARAMS_MACRO(name,len) const realtype *name;
#else /* the default */
#  define PARAMS_MACRO(name,len) realtype name[len];
#endif
typedef struct {
    PARAMS_MACRO(g,30)
    PARAMS_MACRO(c,1)
    PARAMS_MACRO(be,20)
} ex2_Params;
#undef PARAMS_MACRO

/* <<< struct Settings >>> */
typedef struct {
    struct {
        int warmstartInner;
    } approach;
    struct {
        realtype init[30];
        int maxit;
        realtype stopgEps;
        int stopgStride;
    } algoInner;
    struct {
        realtype init[20];
        int maxit;
        realtype stopgEps;
        int stopgStride;
    } algoOuter;
} ex2_Settings;

/* <<< struct Result >>> */
typedef struct {
    realtype la[20];
    realtype x[30];
    realtype d;
    int iter;
    int exitflag;
} ex2_Result;

/* <<< struct Work >>> */
typedef struct {
    struct {
        realtype H[30];
        realtype Ae[600];
        realtype inner_g[30];
        realtype inner_c[1];
        struct {
            realtype l[1];
            realtype u[1];
        } X1;
        struct {
            realtype l[1];
            realtype u[1];
        } X2;
        struct {
            realtype l[1];
            realtype u[1];
        } X3;
        struct {
            realtype l[1];
            realtype u[1];
        } X4;
        struct {
            realtype l[1];
            realtype u[1];
        } X5;
        struct {
            realtype l[1];
            realtype u[1];
        } X6;
        struct {
            realtype l[1];
            realtype u[1];
        } X7;
        struct {
            realtype l[1];
            realtype u[1];
        } X8;
        struct {
            realtype l[1];
            realtype u[1];
        } X9;
        struct {
            realtype l[1];
            realtype u[1];
        } X10;
        struct {
            realtype l[2];
            realtype u[2];
        } X11;
        struct {
            realtype l[2];
            realtype u[2];
        } X12;
        struct {
            realtype l[2];
            realtype u[2];
        } X13;
        struct {
            realtype l[2];
            realtype u[2];
        } X14;
        struct {
            realtype l[2];
            realtype u[2];
        } X15;
        struct {
            realtype l[2];
            realtype u[2];
        } X16;
        struct {
            realtype l[2];
            realtype u[2];
        } X17;
        struct {
            realtype l[2];
            realtype u[2];
        } X18;
        struct {
            realtype l[2];
            realtype u[2];
        } X19;
        struct {
            realtype l[2];
            realtype u[2];
        } X20;
    } Prob;
    struct {
        realtype init[30];
        realtype glob_Linv;
        realtype glob_mu;
        realtype res_z[30];
        int res_stopcode;
        int res_iter;
    } algoInner;
    struct {
        realtype init[20];
        realtype glob_Linv;
        realtype res_z[20];
        int res_stopcode;
        int res_iter;
    } algoOuter;
} ex2_Work;

/* <<< solver INTERFACE >>> */
void ex2_init(ex2_Params *params, ex2_Settings *settings, ex2_Result *result, ex2_Work *work);
void ex2_solve(ex2_Params *params, ex2_Settings *settings, ex2_Result *result, ex2_Work *work);
#endif
