function cross_term_jacobian = omega_cross_term_jacobian(in1,in2)
%OMEGA_CROSS_TERM_JACOBIAN
%    CROSS_TERM_JACOBIAN = OMEGA_CROSS_TERM_JACOBIAN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    19-Jan-2023 19:31:14

A_11 = in2(1);
A_12 = in2(4);
A_13 = in2(7);
A_21 = in2(2);
A_22 = in2(5);
A_23 = in2(8);
A_31 = in2(3);
A_32 = in2(6);
A_33 = in2(9);
omg_1 = in1(1,:);
omg_2 = in1(2,:);
omg_3 = in1(3,:);
t2 = A_11.*omg_1;
t3 = A_22.*omg_2;
t4 = A_33.*omg_3;
cross_term_jacobian = reshape([-A_21.*omg_3+A_31.*omg_2,-t4+A_11.*omg_3-A_31.*omg_1.*2.0-A_32.*omg_2,t3-A_11.*omg_2+A_21.*omg_1.*2.0+A_23.*omg_3,t4-A_22.*omg_3+A_31.*omg_1+A_32.*omg_2.*2.0,A_12.*omg_3-A_32.*omg_1,-t2-A_12.*omg_2.*2.0-A_13.*omg_3+A_22.*omg_1,-t3-A_21.*omg_1-A_23.*omg_3.*2.0+A_33.*omg_2,t2+A_12.*omg_2+A_13.*omg_3.*2.0-A_33.*omg_1,-A_13.*omg_2+A_23.*omg_1],[3,3]);
