/**
 * This file is generated by FiOrdOs, a program licensed under GPL
 * by copyright holder Automatic Control Laboratory, ETH Zurich.
 * 
 * If you are interested in using this file commercially,
 * please contact the copyright holder.
 */

#include "ex10_solver.h"
#include <stdio.h>
#include <math.h>
#include <string.h>

#ifdef MATLAB_MEX_FILE
#include "mex.h"
#endif

/* <<< print >>> */
static void printArray(realtype *arr, int dim) {
  int i;
  printf("[\n"); ;
  for (i=0; i<dim; i++) {
    printf("%8.16e\n",*arr++);
  }
  printf("]\n\n");
}

static void printArrayNamed(realtype *arr, int dim, char *txt) {
  printf("%s = ",txt);
  printArray(arr,dim);
}

/* <<< copy vectors >>> */
static void copyvec120(realtype *dest, const realtype *src) {
    {
        int i;
        for (i=0; i<120; ++i) {
            dest[i] = src[i];
        }
    }
}
static void copyvec80(realtype *dest, const realtype *src) {
    {
        int i;
        for (i=0; i<80; ++i) {
            dest[i] = src[i];
        }
    }
}

/* <<< projection >>> */
static void algoInner_project(realtype *thevec, ex10_Work *work, ex10_Params *params) {
    realtype *theveci;

    /* ====== EssBox X1 ====== */
    theveci = thevec;
    /* ------ projection ------ */
    {
        int icoord;
        for (icoord=0; icoord<4; ++icoord) {
          if (theveci[icoord] < work->Prob.X1.l[icoord]) {
            theveci[icoord] = work->Prob.X1.l[icoord];
          }
          else if (theveci[icoord] > work->Prob.X1.u[icoord]) {
            theveci[icoord] = work->Prob.X1.u[icoord];
          }
        }
    }
    /* ====== EssBox X2 ====== */
    theveci = thevec+4;
    /* ------ projection ------ */
    {
        int icoord;
        for (icoord=0; icoord<4; ++icoord) {
          if (theveci[icoord] < work->Prob.X2.l[icoord]) {
            theveci[icoord] = work->Prob.X2.l[icoord];
          }
          else if (theveci[icoord] > work->Prob.X2.u[icoord]) {
            theveci[icoord] = work->Prob.X2.u[icoord];
          }
        }
    }
    /* ====== EssBox X3 ====== */
    theveci = thevec+8;
    /* ------ projection ------ */
    {
        int icoord;
        for (icoord=0; icoord<4; ++icoord) {
          if (theveci[icoord] < work->Prob.X3.l[icoord]) {
            theveci[icoord] = work->Prob.X3.l[icoord];
          }
          else if (theveci[icoord] > work->Prob.X3.u[icoord]) {
            theveci[icoord] = work->Prob.X3.u[icoord];
          }
        }
    }
    /* ====== EssBox X4 ====== */
    theveci = thevec+12;
    /* ------ projection ------ */
    {
        int icoord;
        for (icoord=0; icoord<4; ++icoord) {
          if (theveci[icoord] < work->Prob.X4.l[icoord]) {
            theveci[icoord] = work->Prob.X4.l[icoord];
          }
          else if (theveci[icoord] > work->Prob.X4.u[icoord]) {
            theveci[icoord] = work->Prob.X4.u[icoord];
          }
        }
    }
    /* ====== EssBox X5 ====== */
    theveci = thevec+16;
    /* ------ projection ------ */
    {
        int icoord;
        for (icoord=0; icoord<4; ++icoord) {
          if (theveci[icoord] < work->Prob.X5.l[icoord]) {
            theveci[icoord] = work->Prob.X5.l[icoord];
          }
          else if (theveci[icoord] > work->Prob.X5.u[icoord]) {
            theveci[icoord] = work->Prob.X5.u[icoord];
          }
        }
    }
    /* ====== EssBox X6 ====== */
    theveci = thevec+20;
    /* ------ projection ------ */
    {
        int icoord;
        for (icoord=0; icoord<4; ++icoord) {
          if (theveci[icoord] < work->Prob.X6.l[icoord]) {
            theveci[icoord] = work->Prob.X6.l[icoord];
          }
          else if (theveci[icoord] > work->Prob.X6.u[icoord]) {
            theveci[icoord] = work->Prob.X6.u[icoord];
          }
        }
    }
    /* ====== EssBox X7 ====== */
    theveci = thevec+24;
    /* ------ projection ------ */
    {
        int icoord;
        for (icoord=0; icoord<4; ++icoord) {
          if (theveci[icoord] < work->Prob.X7.l[icoord]) {
            theveci[icoord] = work->Prob.X7.l[icoord];
          }
          else if (theveci[icoord] > work->Prob.X7.u[icoord]) {
            theveci[icoord] = work->Prob.X7.u[icoord];
          }
        }
    }
    /* ====== EssBox X8 ====== */
    theveci = thevec+28;
    /* ------ projection ------ */
    {
        int icoord;
        for (icoord=0; icoord<4; ++icoord) {
          if (theveci[icoord] < work->Prob.X8.l[icoord]) {
            theveci[icoord] = work->Prob.X8.l[icoord];
          }
          else if (theveci[icoord] > work->Prob.X8.u[icoord]) {
            theveci[icoord] = work->Prob.X8.u[icoord];
          }
        }
    }
    /* ====== EssBox X9 ====== */
    theveci = thevec+32;
    /* ------ projection ------ */
    {
        int icoord;
        for (icoord=0; icoord<4; ++icoord) {
          if (theveci[icoord] < work->Prob.X9.l[icoord]) {
            theveci[icoord] = work->Prob.X9.l[icoord];
          }
          else if (theveci[icoord] > work->Prob.X9.u[icoord]) {
            theveci[icoord] = work->Prob.X9.u[icoord];
          }
        }
    }
    /* ====== EssBox X10 ====== */
    theveci = thevec+36;
    /* ------ projection ------ */
    {
        int icoord;
        for (icoord=0; icoord<4; ++icoord) {
          if (theveci[icoord] < work->Prob.X10.l[icoord]) {
            theveci[icoord] = work->Prob.X10.l[icoord];
          }
          else if (theveci[icoord] > work->Prob.X10.u[icoord]) {
            theveci[icoord] = work->Prob.X10.u[icoord];
          }
        }
    }
    /* ====== EssBox X11 ====== */
    theveci = thevec+40;
    /* ------ projection ------ */
    {
        int icoord;
        for (icoord=0; icoord<8; ++icoord) {
          if (theveci[icoord] < work->Prob.X11.l[icoord]) {
            theveci[icoord] = work->Prob.X11.l[icoord];
          }
          else if (theveci[icoord] > work->Prob.X11.u[icoord]) {
            theveci[icoord] = work->Prob.X11.u[icoord];
          }
        }
    }
    /* ====== EssBox X12 ====== */
    theveci = thevec+48;
    /* ------ projection ------ */
    {
        int icoord;
        for (icoord=0; icoord<8; ++icoord) {
          if (theveci[icoord] < work->Prob.X12.l[icoord]) {
            theveci[icoord] = work->Prob.X12.l[icoord];
          }
          else if (theveci[icoord] > work->Prob.X12.u[icoord]) {
            theveci[icoord] = work->Prob.X12.u[icoord];
          }
        }
    }
    /* ====== EssBox X13 ====== */
    theveci = thevec+56;
    /* ------ projection ------ */
    {
        int icoord;
        for (icoord=0; icoord<8; ++icoord) {
          if (theveci[icoord] < work->Prob.X13.l[icoord]) {
            theveci[icoord] = work->Prob.X13.l[icoord];
          }
          else if (theveci[icoord] > work->Prob.X13.u[icoord]) {
            theveci[icoord] = work->Prob.X13.u[icoord];
          }
        }
    }
    /* ====== EssBox X14 ====== */
    theveci = thevec+64;
    /* ------ projection ------ */
    {
        int icoord;
        for (icoord=0; icoord<8; ++icoord) {
          if (theveci[icoord] < work->Prob.X14.l[icoord]) {
            theveci[icoord] = work->Prob.X14.l[icoord];
          }
          else if (theveci[icoord] > work->Prob.X14.u[icoord]) {
            theveci[icoord] = work->Prob.X14.u[icoord];
          }
        }
    }
    /* ====== EssBox X15 ====== */
    theveci = thevec+72;
    /* ------ projection ------ */
    {
        int icoord;
        for (icoord=0; icoord<8; ++icoord) {
          if (theveci[icoord] < work->Prob.X15.l[icoord]) {
            theveci[icoord] = work->Prob.X15.l[icoord];
          }
          else if (theveci[icoord] > work->Prob.X15.u[icoord]) {
            theveci[icoord] = work->Prob.X15.u[icoord];
          }
        }
    }
    /* ====== EssBox X16 ====== */
    theveci = thevec+80;
    /* ------ projection ------ */
    {
        int icoord;
        for (icoord=0; icoord<8; ++icoord) {
          if (theveci[icoord] < work->Prob.X16.l[icoord]) {
            theveci[icoord] = work->Prob.X16.l[icoord];
          }
          else if (theveci[icoord] > work->Prob.X16.u[icoord]) {
            theveci[icoord] = work->Prob.X16.u[icoord];
          }
        }
    }
    /* ====== EssBox X17 ====== */
    theveci = thevec+88;
    /* ------ projection ------ */
    {
        int icoord;
        for (icoord=0; icoord<8; ++icoord) {
          if (theveci[icoord] < work->Prob.X17.l[icoord]) {
            theveci[icoord] = work->Prob.X17.l[icoord];
          }
          else if (theveci[icoord] > work->Prob.X17.u[icoord]) {
            theveci[icoord] = work->Prob.X17.u[icoord];
          }
        }
    }
    /* ====== EssBox X18 ====== */
    theveci = thevec+96;
    /* ------ projection ------ */
    {
        int icoord;
        for (icoord=0; icoord<8; ++icoord) {
          if (theveci[icoord] < work->Prob.X18.l[icoord]) {
            theveci[icoord] = work->Prob.X18.l[icoord];
          }
          else if (theveci[icoord] > work->Prob.X18.u[icoord]) {
            theveci[icoord] = work->Prob.X18.u[icoord];
          }
        }
    }
    /* ====== EssBox X19 ====== */
    theveci = thevec+104;
    /* ------ projection ------ */
    {
        int icoord;
        for (icoord=0; icoord<8; ++icoord) {
          if (theveci[icoord] < work->Prob.X19.l[icoord]) {
            theveci[icoord] = work->Prob.X19.l[icoord];
          }
          else if (theveci[icoord] > work->Prob.X19.u[icoord]) {
            theveci[icoord] = work->Prob.X19.u[icoord];
          }
        }
    }
    /* ====== EssBox X20 ====== */
    theveci = thevec+112;
    /* ------ projection ------ */
    {
        int icoord;
        for (icoord=0; icoord<8; ++icoord) {
          if (theveci[icoord] < work->Prob.X20.l[icoord]) {
            theveci[icoord] = work->Prob.X20.l[icoord];
          }
          else if (theveci[icoord] > work->Prob.X20.u[icoord]) {
            theveci[icoord] = work->Prob.X20.u[icoord];
          }
        }
    }
}

/* <<< oracle >>> */
static void algoInner_oracle(ex10_Work *work, ex10_Params *params, realtype *z, realtype *fval, realtype *grad) {
    realtype hz[120];
    {
        /* (hz):= (work->Prob.H)^T*(z);   // (120x120)*(120x1) */
        {
            int k;
            for (k=0; k<120; ++k) {
              hz[k] = (+work->Prob.H[k]) * z[k];
            }
        }
    }

    if (NULL!=fval) {
        int i;
        realtype tmp;
        tmp = 0.0;
        for (i=0; i<120; ++i) {
          tmp += (0.5*hz[i] + work->Prob.inner_g[i]) * z[i];
        }
        fval[0] = tmp + work->Prob.inner_c[0];
    }

    if (NULL!=grad) {
        int i;
        for (i=0; i<120; ++i) {
          grad[i] = hz[i] + work->Prob.inner_g[i];
        }
    }
}
static void algoOuter_oracle(ex10_Work *work, ex10_Params *params, realtype *v, realtype *fval, realtype *grad, ex10_Settings *settings) {
    /* << data of inner problem >> */
    {
        /* (work->Prob.inner_g):= (work->Prob.Ae)^T*(v)+(params->g);   // (120x80)*(80x1),(120x1) */
        int i,k;
        realtype tmp;
        for (i=0; i<120; ++i) {
            tmp = 0.0;
            for (k=0; k<80; ++k) {
              tmp += work->Prob.Ae[k+i*80]*v[k];
            }
            work->Prob.inner_g[i] = tmp + params->g[i];
        }
    }
    {
        /* (work->Prob.inner_c):= -(v)^T*(params->be)+(params->c);   // (1x80)*(80x1),(1x1) */
        int k;
        realtype tmp;
            tmp = 0.0;
            for (k=0; k<80; ++k) {
              tmp -= v[k]*params->be[k];
            }
            work->Prob.inner_c[0] = tmp + params->c[0];
    }

    /* << inner algorithm >> */
    /* AlgoFgm */
    {
        int stopgNext;
        stopgNext = 1;
        work->algoInner.res_stopcode = 0;
        {
            realtype z[120];
            realtype zp[120];
            realtype y[120];
            realtype grad[120];
            int iter;
            int icoord;
            realtype alpha,alpha_p;
            realtype aamul,muLinv;
            realtype beta;
            
            iter =0;
            
            copyvec120(z,work->algoInner.init);  /* (z):=(work->algoInner.init) */
            copyvec120(y,z);  /* (y):=(z) */
            alpha = 1;
            muLinv = work->algoInner.glob_mu*work->algoInner.glob_Linv;
            copyvec120(zp,z);  /* (zp):=(z) */
            
            while (iter<settings->algoInner.maxit) {
                ++iter;
            
                algoInner_oracle(work,params,y,NULL,grad);
                for (icoord=0; icoord<120; ++icoord) {
                    zp[icoord] = y[icoord] - work->algoInner.glob_Linv*grad[icoord];
                }
                algoInner_project(zp,work,params);
            
                if (iter==stopgNext) {
                    int icoord;
                    realtype gradmapi;
                    realtype normsq;
                    normsq = 0;
                    for (icoord=0; icoord<120; ++icoord) {
                        gradmapi=(y[icoord]-zp[icoord]);
                        normsq += gradmapi * gradmapi;
                    }
                    normsq *= 1.0/(work->algoInner.glob_Linv*work->algoInner.glob_Linv);
                    if ( settings->algoInner.stopgEps>=0 && normsq <= settings->algoInner.stopgEps * settings->algoInner.stopgEps ) {
                        work->algoInner.res_stopcode = 2;
                        break;
                    }
                    stopgNext += settings->algoInner.stopgStride;
                }
            
                aamul = alpha*alpha - muLinv;
                alpha_p= -0.5 * aamul + sqrt( aamul*aamul * 0.25 + alpha*alpha);
                beta = alpha*(1-alpha)/(alpha*alpha+alpha_p);
            
                for (icoord=0; icoord<120; ++icoord) {
                    y[icoord] = zp[icoord] + beta*(zp[icoord]-z[icoord]);
                }
            
                copyvec120(z,zp);  /* (z):=(zp) */
                alpha = alpha_p;
            }
            copyvec120(work->algoInner.res_z,zp);  /* (work->algoInner.res_z):=(zp) */
            work->algoInner.res_iter = iter;
        }
    }

    /* << outer gradient >> */
    if (NULL!=grad) {
        {
            /* (grad):= (work->Prob.Ae)*(work->algoInner.res_z)-(params->be);   // (80x120)*(120x1),(80x1) */
            int i,k;
            realtype tmp;
            for (i=0; i<80; ++i) {
                tmp = 0.0;
                for (k=0; k<120; ++k) {
                  tmp += work->Prob.Ae[i+k*80]*work->algoInner.res_z[k];
                }
                grad[i] = tmp - params->be[i];
            }
        }
    }

    /* << dual function value >> */
    if (NULL!=fval) {
        algoInner_oracle(work,params,work->algoInner.res_z,fval,NULL);
    }

}

/* <<< SOLVE >>> */
void ex10_solve(ex10_Params *params, ex10_Settings *settings, ex10_Result *result, ex10_Work *work) {

    /* << prepare data >> */
    {
        /* === initial points === */
        copyvec120(work->algoInner.init,settings->algoInner.init);  /* (work->algoInner.init):=(settings->algoInner.init) */
        algoInner_project(work->algoInner.init,work,params);
        copyvec80(work->algoOuter.init,settings->algoOuter.init);  /* (work->algoOuter.init):=(settings->algoOuter.init) */
        
    }

    /* << main algorithm >> */
    /* AlgoFgm */
    {
        int stopgNext;
        stopgNext = 1;
        work->algoOuter.res_stopcode = 0;
        {
            realtype z[80];
            realtype zp[80];
            realtype y[80];
            realtype grad[80];
            int iter;
            int icoord;
            realtype alpha,alpha_p;
            realtype beta;
            
            iter =0;
            
            copyvec80(z,work->algoOuter.init);  /* (z):=(work->algoOuter.init) */
            copyvec80(y,z);  /* (y):=(z) */
            alpha = 1;
            copyvec80(zp,z);  /* (zp):=(z) */
            
            while (iter<settings->algoOuter.maxit) {
                ++iter;
            
                algoOuter_oracle(work,params,y,NULL,grad,settings);
                if ( 1==settings->approach.warmstartInner) {  /* reinit inner */
                    copyvec120(work->algoInner.init,work->algoInner.res_z);  /* (work->algoInner.init):=(work->algoInner.res_z) */
                }
                for (icoord=0; icoord<80; ++icoord) {
                    zp[icoord] = y[icoord] + work->algoOuter.glob_Linv*grad[icoord];
                }
            
                if (iter==stopgNext) {
                    int icoord;
                    realtype gradmapi;
                    realtype normsq;
                    normsq = 0;
                    for (icoord=0; icoord<80; ++icoord) {
                        gradmapi=(y[icoord]-zp[icoord]);
                        normsq += gradmapi * gradmapi;
                    }
                    normsq *= 1.0/(work->algoOuter.glob_Linv*work->algoOuter.glob_Linv);
                    if ( settings->algoOuter.stopgEps>=0 && normsq <= settings->algoOuter.stopgEps * settings->algoOuter.stopgEps ) {
                        work->algoOuter.res_stopcode = 2;
                        break;
                    }
                    stopgNext += settings->algoOuter.stopgStride;
                }
            
                alpha_p= 0.5*alpha*(sqrt(alpha*alpha+4)-alpha);
                beta = alpha*(1-alpha)/(alpha*alpha+alpha_p);
            
                for (icoord=0; icoord<80; ++icoord) {
                    y[icoord] = zp[icoord] + beta*(zp[icoord]-z[icoord]);
                }
            
                copyvec80(z,zp);  /* (z):=(zp) */
                alpha = alpha_p;
            }
            copyvec80(work->algoOuter.res_z,zp);  /* (work->algoOuter.res_z):=(zp) */
            work->algoOuter.res_iter = iter;
        }
    }
    
    
    /* << finalize result >> */
    copyvec80(result->la,work->algoOuter.res_z);  /* (result->la):=(work->algoOuter.res_z) */
    algoOuter_oracle(work,params,work->algoOuter.res_z,&(result->d),NULL,settings);
    copyvec120(result->x,work->algoInner.res_z);  /* (result->x):=(work->algoInner.res_z) */
    result->iter = work->algoOuter.res_iter;
    result->exitflag = work->algoOuter.res_stopcode;

}



/* <<< INIT >>> */
void ex10_init(ex10_Params *params, ex10_Settings *settings, ex10_Result *result, ex10_Work *work) {
work->Prob.H[0] = (realtype) 1.0000000000000000e+00;
work->Prob.H[1] = (realtype) 1.0000000000000000e+00;
work->Prob.H[2] = (realtype) 1.0000000000000000e+00;
work->Prob.H[3] = (realtype) 1.0000000000000000e+00;
work->Prob.H[4] = (realtype) 1.0000000000000000e+00;
work->Prob.H[5] = (realtype) 1.0000000000000000e+00;
work->Prob.H[6] = (realtype) 1.0000000000000000e+00;
work->Prob.H[7] = (realtype) 1.0000000000000000e+00;
work->Prob.H[8] = (realtype) 1.0000000000000000e+00;
work->Prob.H[9] = (realtype) 1.0000000000000000e+00;
work->Prob.H[10] = (realtype) 1.0000000000000000e+00;
work->Prob.H[11] = (realtype) 1.0000000000000000e+00;
work->Prob.H[12] = (realtype) 1.0000000000000000e+00;
work->Prob.H[13] = (realtype) 1.0000000000000000e+00;
work->Prob.H[14] = (realtype) 1.0000000000000000e+00;
work->Prob.H[15] = (realtype) 1.0000000000000000e+00;
work->Prob.H[16] = (realtype) 1.0000000000000000e+00;
work->Prob.H[17] = (realtype) 1.0000000000000000e+00;
work->Prob.H[18] = (realtype) 1.0000000000000000e+00;
work->Prob.H[19] = (realtype) 1.0000000000000000e+00;
work->Prob.H[20] = (realtype) 1.0000000000000000e+00;
work->Prob.H[21] = (realtype) 1.0000000000000000e+00;
work->Prob.H[22] = (realtype) 1.0000000000000000e+00;
work->Prob.H[23] = (realtype) 1.0000000000000000e+00;
work->Prob.H[24] = (realtype) 1.0000000000000000e+00;
work->Prob.H[25] = (realtype) 1.0000000000000000e+00;
work->Prob.H[26] = (realtype) 1.0000000000000000e+00;
work->Prob.H[27] = (realtype) 1.0000000000000000e+00;
work->Prob.H[28] = (realtype) 1.0000000000000000e+00;
work->Prob.H[29] = (realtype) 1.0000000000000000e+00;
work->Prob.H[30] = (realtype) 1.0000000000000000e+00;
work->Prob.H[31] = (realtype) 1.0000000000000000e+00;
work->Prob.H[32] = (realtype) 1.0000000000000000e+00;
work->Prob.H[33] = (realtype) 1.0000000000000000e+00;
work->Prob.H[34] = (realtype) 1.0000000000000000e+00;
work->Prob.H[35] = (realtype) 1.0000000000000000e+00;
work->Prob.H[36] = (realtype) 1.0000000000000000e+00;
work->Prob.H[37] = (realtype) 1.0000000000000000e+00;
work->Prob.H[38] = (realtype) 1.0000000000000000e+00;
work->Prob.H[39] = (realtype) 1.0000000000000000e+00;
work->Prob.H[40] = (realtype) 1.0000000000000000e+00;
work->Prob.H[41] = (realtype) 1.0000000000000000e+00;
work->Prob.H[42] = (realtype) 1.0000000000000000e+00;
work->Prob.H[43] = (realtype) 1.0000000000000000e+00;
work->Prob.H[44] = (realtype) 1.0000000000000000e+00;
work->Prob.H[45] = (realtype) 1.0000000000000000e+00;
work->Prob.H[46] = (realtype) 1.0000000000000000e+00;
work->Prob.H[47] = (realtype) 1.0000000000000000e+00;
work->Prob.H[48] = (realtype) 1.0000000000000000e+00;
work->Prob.H[49] = (realtype) 1.0000000000000000e+00;
work->Prob.H[50] = (realtype) 1.0000000000000000e+00;
work->Prob.H[51] = (realtype) 1.0000000000000000e+00;
work->Prob.H[52] = (realtype) 1.0000000000000000e+00;
work->Prob.H[53] = (realtype) 1.0000000000000000e+00;
work->Prob.H[54] = (realtype) 1.0000000000000000e+00;
work->Prob.H[55] = (realtype) 1.0000000000000000e+00;
work->Prob.H[56] = (realtype) 1.0000000000000000e+00;
work->Prob.H[57] = (realtype) 1.0000000000000000e+00;
work->Prob.H[58] = (realtype) 1.0000000000000000e+00;
work->Prob.H[59] = (realtype) 1.0000000000000000e+00;
work->Prob.H[60] = (realtype) 1.0000000000000000e+00;
work->Prob.H[61] = (realtype) 1.0000000000000000e+00;
work->Prob.H[62] = (realtype) 1.0000000000000000e+00;
work->Prob.H[63] = (realtype) 1.0000000000000000e+00;
work->Prob.H[64] = (realtype) 1.0000000000000000e+00;
work->Prob.H[65] = (realtype) 1.0000000000000000e+00;
work->Prob.H[66] = (realtype) 1.0000000000000000e+00;
work->Prob.H[67] = (realtype) 1.0000000000000000e+00;
work->Prob.H[68] = (realtype) 1.0000000000000000e+00;
work->Prob.H[69] = (realtype) 1.0000000000000000e+00;
work->Prob.H[70] = (realtype) 1.0000000000000000e+00;
work->Prob.H[71] = (realtype) 1.0000000000000000e+00;
work->Prob.H[72] = (realtype) 1.0000000000000000e+00;
work->Prob.H[73] = (realtype) 1.0000000000000000e+00;
work->Prob.H[74] = (realtype) 1.0000000000000000e+00;
work->Prob.H[75] = (realtype) 1.0000000000000000e+00;
work->Prob.H[76] = (realtype) 1.0000000000000000e+00;
work->Prob.H[77] = (realtype) 1.0000000000000000e+00;
work->Prob.H[78] = (realtype) 1.0000000000000000e+00;
work->Prob.H[79] = (realtype) 1.0000000000000000e+00;
work->Prob.H[80] = (realtype) 1.0000000000000000e+00;
work->Prob.H[81] = (realtype) 1.0000000000000000e+00;
work->Prob.H[82] = (realtype) 1.0000000000000000e+00;
work->Prob.H[83] = (realtype) 1.0000000000000000e+00;
work->Prob.H[84] = (realtype) 1.0000000000000000e+00;
work->Prob.H[85] = (realtype) 1.0000000000000000e+00;
work->Prob.H[86] = (realtype) 1.0000000000000000e+00;
work->Prob.H[87] = (realtype) 1.0000000000000000e+00;
work->Prob.H[88] = (realtype) 1.0000000000000000e+00;
work->Prob.H[89] = (realtype) 1.0000000000000000e+00;
work->Prob.H[90] = (realtype) 1.0000000000000000e+00;
work->Prob.H[91] = (realtype) 1.0000000000000000e+00;
work->Prob.H[92] = (realtype) 1.0000000000000000e+00;
work->Prob.H[93] = (realtype) 1.0000000000000000e+00;
work->Prob.H[94] = (realtype) 1.0000000000000000e+00;
work->Prob.H[95] = (realtype) 1.0000000000000000e+00;
work->Prob.H[96] = (realtype) 1.0000000000000000e+00;
work->Prob.H[97] = (realtype) 1.0000000000000000e+00;
work->Prob.H[98] = (realtype) 1.0000000000000000e+00;
work->Prob.H[99] = (realtype) 1.0000000000000000e+00;
work->Prob.H[100] = (realtype) 1.0000000000000000e+00;
work->Prob.H[101] = (realtype) 1.0000000000000000e+00;
work->Prob.H[102] = (realtype) 1.0000000000000000e+00;
work->Prob.H[103] = (realtype) 1.0000000000000000e+00;
work->Prob.H[104] = (realtype) 1.0000000000000000e+00;
work->Prob.H[105] = (realtype) 1.0000000000000000e+00;
work->Prob.H[106] = (realtype) 1.0000000000000000e+00;
work->Prob.H[107] = (realtype) 1.0000000000000000e+00;
work->Prob.H[108] = (realtype) 1.0000000000000000e+00;
work->Prob.H[109] = (realtype) 1.0000000000000000e+00;
work->Prob.H[110] = (realtype) 1.0000000000000000e+00;
work->Prob.H[111] = (realtype) 1.0000000000000000e+00;
work->Prob.H[112] = (realtype) 1.0000000000000000e+00;
work->Prob.H[113] = (realtype) 1.0000000000000000e+00;
work->Prob.H[114] = (realtype) 1.0000000000000000e+00;
work->Prob.H[115] = (realtype) 1.0000000000000000e+00;
work->Prob.H[116] = (realtype) 1.0000000000000000e+00;
work->Prob.H[117] = (realtype) 1.0000000000000000e+00;
work->Prob.H[118] = (realtype) 1.0000000000000000e+00;
work->Prob.H[119] = (realtype) 1.0000000000000000e+00;
{int i; for (i=0;i<9600;++i) {work->Prob.Ae[i] = (realtype) 0.0;}}
work->Prob.Ae[0] = (realtype) 1.5190000000000001e-01;
work->Prob.Ae[1] = (realtype) -1.6122000000000001e+00;
work->Prob.Ae[2] = (realtype) 1.1580000000000000e-01;
work->Prob.Ae[3] = (realtype) -8.8200000000000001e-02;
work->Prob.Ae[4] = (realtype) -1.7692000000000001e+00;
work->Prob.Ae[5] = (realtype) -9.9050000000000005e-01;
work->Prob.Ae[6] = (realtype) 3.4339999999999998e-01;
work->Prob.Ae[7] = (realtype) -8.0930000000000002e-01;
work->Prob.Ae[80] = (realtype) -8.2999999999999996e-01;
work->Prob.Ae[81] = (realtype) -1.0810999999999999e+00;
work->Prob.Ae[82] = (realtype) -7.1870000000000001e-01;
work->Prob.Ae[83] = (realtype) 8.1850000000000001e-01;
work->Prob.Ae[84] = (realtype) 9.9319999999999997e-01;
work->Prob.Ae[85] = (realtype) 7.4519999999999997e-01;
work->Prob.Ae[86] = (realtype) -1.8550000000000000e-01;
work->Prob.Ae[87] = (realtype) -6.2819999999999998e-01;
work->Prob.Ae[160] = (realtype) -7.2980000000000000e-01;
work->Prob.Ae[161] = (realtype) 1.1590000000000000e+00;
work->Prob.Ae[162] = (realtype) 1.3983000000000001e+00;
work->Prob.Ae[163] = (realtype) -5.9099999999999997e-01;
work->Prob.Ae[164] = (realtype) -1.7640000000000000e-01;
work->Prob.Ae[165] = (realtype) 2.0600000000000000e-02;
work->Prob.Ae[166] = (realtype) -8.2650000000000001e-01;
work->Prob.Ae[167] = (realtype) -7.1650000000000003e-01;
work->Prob.Ae[240] = (realtype) 1.4262999999999999e+00;
work->Prob.Ae[241] = (realtype) -1.8850000000000000e-01;
work->Prob.Ae[242] = (realtype) 9.1200000000000003e-01;
work->Prob.Ae[243] = (realtype) -3.3250000000000002e-01;
work->Prob.Ae[244] = (realtype) 9.7609999999999997e-01;
work->Prob.Ae[245] = (realtype) -3.4489999999999998e-01;
work->Prob.Ae[246] = (realtype) 1.9641999999999999e+00;
work->Prob.Ae[247] = (realtype) -2.1750000000000000e-01;
work->Prob.Ae[328] = (realtype) 1.5190000000000001e-01;
work->Prob.Ae[329] = (realtype) -1.6122000000000001e+00;
work->Prob.Ae[330] = (realtype) 1.1580000000000000e-01;
work->Prob.Ae[331] = (realtype) -8.8200000000000001e-02;
work->Prob.Ae[332] = (realtype) -1.7692000000000001e+00;
work->Prob.Ae[333] = (realtype) -9.9050000000000005e-01;
work->Prob.Ae[334] = (realtype) 3.4339999999999998e-01;
work->Prob.Ae[335] = (realtype) -8.0930000000000002e-01;
work->Prob.Ae[408] = (realtype) -8.2999999999999996e-01;
work->Prob.Ae[409] = (realtype) -1.0810999999999999e+00;
work->Prob.Ae[410] = (realtype) -7.1870000000000001e-01;
work->Prob.Ae[411] = (realtype) 8.1850000000000001e-01;
work->Prob.Ae[412] = (realtype) 9.9319999999999997e-01;
work->Prob.Ae[413] = (realtype) 7.4519999999999997e-01;
work->Prob.Ae[414] = (realtype) -1.8550000000000000e-01;
work->Prob.Ae[415] = (realtype) -6.2819999999999998e-01;
work->Prob.Ae[488] = (realtype) -7.2980000000000000e-01;
work->Prob.Ae[489] = (realtype) 1.1590000000000000e+00;
work->Prob.Ae[490] = (realtype) 1.3983000000000001e+00;
work->Prob.Ae[491] = (realtype) -5.9099999999999997e-01;
work->Prob.Ae[492] = (realtype) -1.7640000000000000e-01;
work->Prob.Ae[493] = (realtype) 2.0600000000000000e-02;
work->Prob.Ae[494] = (realtype) -8.2650000000000001e-01;
work->Prob.Ae[495] = (realtype) -7.1650000000000003e-01;
work->Prob.Ae[568] = (realtype) 1.4262999999999999e+00;
work->Prob.Ae[569] = (realtype) -1.8850000000000000e-01;
work->Prob.Ae[570] = (realtype) 9.1200000000000003e-01;
work->Prob.Ae[571] = (realtype) -3.3250000000000002e-01;
work->Prob.Ae[572] = (realtype) 9.7609999999999997e-01;
work->Prob.Ae[573] = (realtype) -3.4489999999999998e-01;
work->Prob.Ae[574] = (realtype) 1.9641999999999999e+00;
work->Prob.Ae[575] = (realtype) -2.1750000000000000e-01;
work->Prob.Ae[656] = (realtype) 1.5190000000000001e-01;
work->Prob.Ae[657] = (realtype) -1.6122000000000001e+00;
work->Prob.Ae[658] = (realtype) 1.1580000000000000e-01;
work->Prob.Ae[659] = (realtype) -8.8200000000000001e-02;
work->Prob.Ae[660] = (realtype) -1.7692000000000001e+00;
work->Prob.Ae[661] = (realtype) -9.9050000000000005e-01;
work->Prob.Ae[662] = (realtype) 3.4339999999999998e-01;
work->Prob.Ae[663] = (realtype) -8.0930000000000002e-01;
work->Prob.Ae[736] = (realtype) -8.2999999999999996e-01;
work->Prob.Ae[737] = (realtype) -1.0810999999999999e+00;
work->Prob.Ae[738] = (realtype) -7.1870000000000001e-01;
work->Prob.Ae[739] = (realtype) 8.1850000000000001e-01;
work->Prob.Ae[740] = (realtype) 9.9319999999999997e-01;
work->Prob.Ae[741] = (realtype) 7.4519999999999997e-01;
work->Prob.Ae[742] = (realtype) -1.8550000000000000e-01;
work->Prob.Ae[743] = (realtype) -6.2819999999999998e-01;
work->Prob.Ae[816] = (realtype) -7.2980000000000000e-01;
work->Prob.Ae[817] = (realtype) 1.1590000000000000e+00;
work->Prob.Ae[818] = (realtype) 1.3983000000000001e+00;
work->Prob.Ae[819] = (realtype) -5.9099999999999997e-01;
work->Prob.Ae[820] = (realtype) -1.7640000000000000e-01;
work->Prob.Ae[821] = (realtype) 2.0600000000000000e-02;
work->Prob.Ae[822] = (realtype) -8.2650000000000001e-01;
work->Prob.Ae[823] = (realtype) -7.1650000000000003e-01;
work->Prob.Ae[896] = (realtype) 1.4262999999999999e+00;
work->Prob.Ae[897] = (realtype) -1.8850000000000000e-01;
work->Prob.Ae[898] = (realtype) 9.1200000000000003e-01;
work->Prob.Ae[899] = (realtype) -3.3250000000000002e-01;
work->Prob.Ae[900] = (realtype) 9.7609999999999997e-01;
work->Prob.Ae[901] = (realtype) -3.4489999999999998e-01;
work->Prob.Ae[902] = (realtype) 1.9641999999999999e+00;
work->Prob.Ae[903] = (realtype) -2.1750000000000000e-01;
work->Prob.Ae[984] = (realtype) 1.5190000000000001e-01;
work->Prob.Ae[985] = (realtype) -1.6122000000000001e+00;
work->Prob.Ae[986] = (realtype) 1.1580000000000000e-01;
work->Prob.Ae[987] = (realtype) -8.8200000000000001e-02;
work->Prob.Ae[988] = (realtype) -1.7692000000000001e+00;
work->Prob.Ae[989] = (realtype) -9.9050000000000005e-01;
work->Prob.Ae[990] = (realtype) 3.4339999999999998e-01;
work->Prob.Ae[991] = (realtype) -8.0930000000000002e-01;
work->Prob.Ae[1064] = (realtype) -8.2999999999999996e-01;
work->Prob.Ae[1065] = (realtype) -1.0810999999999999e+00;
work->Prob.Ae[1066] = (realtype) -7.1870000000000001e-01;
work->Prob.Ae[1067] = (realtype) 8.1850000000000001e-01;
work->Prob.Ae[1068] = (realtype) 9.9319999999999997e-01;
work->Prob.Ae[1069] = (realtype) 7.4519999999999997e-01;
work->Prob.Ae[1070] = (realtype) -1.8550000000000000e-01;
work->Prob.Ae[1071] = (realtype) -6.2819999999999998e-01;
work->Prob.Ae[1144] = (realtype) -7.2980000000000000e-01;
work->Prob.Ae[1145] = (realtype) 1.1590000000000000e+00;
work->Prob.Ae[1146] = (realtype) 1.3983000000000001e+00;
work->Prob.Ae[1147] = (realtype) -5.9099999999999997e-01;
work->Prob.Ae[1148] = (realtype) -1.7640000000000000e-01;
work->Prob.Ae[1149] = (realtype) 2.0600000000000000e-02;
work->Prob.Ae[1150] = (realtype) -8.2650000000000001e-01;
work->Prob.Ae[1151] = (realtype) -7.1650000000000003e-01;
work->Prob.Ae[1224] = (realtype) 1.4262999999999999e+00;
work->Prob.Ae[1225] = (realtype) -1.8850000000000000e-01;
work->Prob.Ae[1226] = (realtype) 9.1200000000000003e-01;
work->Prob.Ae[1227] = (realtype) -3.3250000000000002e-01;
work->Prob.Ae[1228] = (realtype) 9.7609999999999997e-01;
work->Prob.Ae[1229] = (realtype) -3.4489999999999998e-01;
work->Prob.Ae[1230] = (realtype) 1.9641999999999999e+00;
work->Prob.Ae[1231] = (realtype) -2.1750000000000000e-01;
work->Prob.Ae[1312] = (realtype) 1.5190000000000001e-01;
work->Prob.Ae[1313] = (realtype) -1.6122000000000001e+00;
work->Prob.Ae[1314] = (realtype) 1.1580000000000000e-01;
work->Prob.Ae[1315] = (realtype) -8.8200000000000001e-02;
work->Prob.Ae[1316] = (realtype) -1.7692000000000001e+00;
work->Prob.Ae[1317] = (realtype) -9.9050000000000005e-01;
work->Prob.Ae[1318] = (realtype) 3.4339999999999998e-01;
work->Prob.Ae[1319] = (realtype) -8.0930000000000002e-01;
work->Prob.Ae[1392] = (realtype) -8.2999999999999996e-01;
work->Prob.Ae[1393] = (realtype) -1.0810999999999999e+00;
work->Prob.Ae[1394] = (realtype) -7.1870000000000001e-01;
work->Prob.Ae[1395] = (realtype) 8.1850000000000001e-01;
work->Prob.Ae[1396] = (realtype) 9.9319999999999997e-01;
work->Prob.Ae[1397] = (realtype) 7.4519999999999997e-01;
work->Prob.Ae[1398] = (realtype) -1.8550000000000000e-01;
work->Prob.Ae[1399] = (realtype) -6.2819999999999998e-01;
work->Prob.Ae[1472] = (realtype) -7.2980000000000000e-01;
work->Prob.Ae[1473] = (realtype) 1.1590000000000000e+00;
work->Prob.Ae[1474] = (realtype) 1.3983000000000001e+00;
work->Prob.Ae[1475] = (realtype) -5.9099999999999997e-01;
work->Prob.Ae[1476] = (realtype) -1.7640000000000000e-01;
work->Prob.Ae[1477] = (realtype) 2.0600000000000000e-02;
work->Prob.Ae[1478] = (realtype) -8.2650000000000001e-01;
work->Prob.Ae[1479] = (realtype) -7.1650000000000003e-01;
work->Prob.Ae[1552] = (realtype) 1.4262999999999999e+00;
work->Prob.Ae[1553] = (realtype) -1.8850000000000000e-01;
work->Prob.Ae[1554] = (realtype) 9.1200000000000003e-01;
work->Prob.Ae[1555] = (realtype) -3.3250000000000002e-01;
work->Prob.Ae[1556] = (realtype) 9.7609999999999997e-01;
work->Prob.Ae[1557] = (realtype) -3.4489999999999998e-01;
work->Prob.Ae[1558] = (realtype) 1.9641999999999999e+00;
work->Prob.Ae[1559] = (realtype) -2.1750000000000000e-01;
work->Prob.Ae[1640] = (realtype) 1.5190000000000001e-01;
work->Prob.Ae[1641] = (realtype) -1.6122000000000001e+00;
work->Prob.Ae[1642] = (realtype) 1.1580000000000000e-01;
work->Prob.Ae[1643] = (realtype) -8.8200000000000001e-02;
work->Prob.Ae[1644] = (realtype) -1.7692000000000001e+00;
work->Prob.Ae[1645] = (realtype) -9.9050000000000005e-01;
work->Prob.Ae[1646] = (realtype) 3.4339999999999998e-01;
work->Prob.Ae[1647] = (realtype) -8.0930000000000002e-01;
work->Prob.Ae[1720] = (realtype) -8.2999999999999996e-01;
work->Prob.Ae[1721] = (realtype) -1.0810999999999999e+00;
work->Prob.Ae[1722] = (realtype) -7.1870000000000001e-01;
work->Prob.Ae[1723] = (realtype) 8.1850000000000001e-01;
work->Prob.Ae[1724] = (realtype) 9.9319999999999997e-01;
work->Prob.Ae[1725] = (realtype) 7.4519999999999997e-01;
work->Prob.Ae[1726] = (realtype) -1.8550000000000000e-01;
work->Prob.Ae[1727] = (realtype) -6.2819999999999998e-01;
work->Prob.Ae[1800] = (realtype) -7.2980000000000000e-01;
work->Prob.Ae[1801] = (realtype) 1.1590000000000000e+00;
work->Prob.Ae[1802] = (realtype) 1.3983000000000001e+00;
work->Prob.Ae[1803] = (realtype) -5.9099999999999997e-01;
work->Prob.Ae[1804] = (realtype) -1.7640000000000000e-01;
work->Prob.Ae[1805] = (realtype) 2.0600000000000000e-02;
work->Prob.Ae[1806] = (realtype) -8.2650000000000001e-01;
work->Prob.Ae[1807] = (realtype) -7.1650000000000003e-01;
work->Prob.Ae[1880] = (realtype) 1.4262999999999999e+00;
work->Prob.Ae[1881] = (realtype) -1.8850000000000000e-01;
work->Prob.Ae[1882] = (realtype) 9.1200000000000003e-01;
work->Prob.Ae[1883] = (realtype) -3.3250000000000002e-01;
work->Prob.Ae[1884] = (realtype) 9.7609999999999997e-01;
work->Prob.Ae[1885] = (realtype) -3.4489999999999998e-01;
work->Prob.Ae[1886] = (realtype) 1.9641999999999999e+00;
work->Prob.Ae[1887] = (realtype) -2.1750000000000000e-01;
work->Prob.Ae[1968] = (realtype) 1.5190000000000001e-01;
work->Prob.Ae[1969] = (realtype) -1.6122000000000001e+00;
work->Prob.Ae[1970] = (realtype) 1.1580000000000000e-01;
work->Prob.Ae[1971] = (realtype) -8.8200000000000001e-02;
work->Prob.Ae[1972] = (realtype) -1.7692000000000001e+00;
work->Prob.Ae[1973] = (realtype) -9.9050000000000005e-01;
work->Prob.Ae[1974] = (realtype) 3.4339999999999998e-01;
work->Prob.Ae[1975] = (realtype) -8.0930000000000002e-01;
work->Prob.Ae[2048] = (realtype) -8.2999999999999996e-01;
work->Prob.Ae[2049] = (realtype) -1.0810999999999999e+00;
work->Prob.Ae[2050] = (realtype) -7.1870000000000001e-01;
work->Prob.Ae[2051] = (realtype) 8.1850000000000001e-01;
work->Prob.Ae[2052] = (realtype) 9.9319999999999997e-01;
work->Prob.Ae[2053] = (realtype) 7.4519999999999997e-01;
work->Prob.Ae[2054] = (realtype) -1.8550000000000000e-01;
work->Prob.Ae[2055] = (realtype) -6.2819999999999998e-01;
work->Prob.Ae[2128] = (realtype) -7.2980000000000000e-01;
work->Prob.Ae[2129] = (realtype) 1.1590000000000000e+00;
work->Prob.Ae[2130] = (realtype) 1.3983000000000001e+00;
work->Prob.Ae[2131] = (realtype) -5.9099999999999997e-01;
work->Prob.Ae[2132] = (realtype) -1.7640000000000000e-01;
work->Prob.Ae[2133] = (realtype) 2.0600000000000000e-02;
work->Prob.Ae[2134] = (realtype) -8.2650000000000001e-01;
work->Prob.Ae[2135] = (realtype) -7.1650000000000003e-01;
work->Prob.Ae[2208] = (realtype) 1.4262999999999999e+00;
work->Prob.Ae[2209] = (realtype) -1.8850000000000000e-01;
work->Prob.Ae[2210] = (realtype) 9.1200000000000003e-01;
work->Prob.Ae[2211] = (realtype) -3.3250000000000002e-01;
work->Prob.Ae[2212] = (realtype) 9.7609999999999997e-01;
work->Prob.Ae[2213] = (realtype) -3.4489999999999998e-01;
work->Prob.Ae[2214] = (realtype) 1.9641999999999999e+00;
work->Prob.Ae[2215] = (realtype) -2.1750000000000000e-01;
work->Prob.Ae[2296] = (realtype) 1.5190000000000001e-01;
work->Prob.Ae[2297] = (realtype) -1.6122000000000001e+00;
work->Prob.Ae[2298] = (realtype) 1.1580000000000000e-01;
work->Prob.Ae[2299] = (realtype) -8.8200000000000001e-02;
work->Prob.Ae[2300] = (realtype) -1.7692000000000001e+00;
work->Prob.Ae[2301] = (realtype) -9.9050000000000005e-01;
work->Prob.Ae[2302] = (realtype) 3.4339999999999998e-01;
work->Prob.Ae[2303] = (realtype) -8.0930000000000002e-01;
work->Prob.Ae[2376] = (realtype) -8.2999999999999996e-01;
work->Prob.Ae[2377] = (realtype) -1.0810999999999999e+00;
work->Prob.Ae[2378] = (realtype) -7.1870000000000001e-01;
work->Prob.Ae[2379] = (realtype) 8.1850000000000001e-01;
work->Prob.Ae[2380] = (realtype) 9.9319999999999997e-01;
work->Prob.Ae[2381] = (realtype) 7.4519999999999997e-01;
work->Prob.Ae[2382] = (realtype) -1.8550000000000000e-01;
work->Prob.Ae[2383] = (realtype) -6.2819999999999998e-01;
work->Prob.Ae[2456] = (realtype) -7.2980000000000000e-01;
work->Prob.Ae[2457] = (realtype) 1.1590000000000000e+00;
work->Prob.Ae[2458] = (realtype) 1.3983000000000001e+00;
work->Prob.Ae[2459] = (realtype) -5.9099999999999997e-01;
work->Prob.Ae[2460] = (realtype) -1.7640000000000000e-01;
work->Prob.Ae[2461] = (realtype) 2.0600000000000000e-02;
work->Prob.Ae[2462] = (realtype) -8.2650000000000001e-01;
work->Prob.Ae[2463] = (realtype) -7.1650000000000003e-01;
work->Prob.Ae[2536] = (realtype) 1.4262999999999999e+00;
work->Prob.Ae[2537] = (realtype) -1.8850000000000000e-01;
work->Prob.Ae[2538] = (realtype) 9.1200000000000003e-01;
work->Prob.Ae[2539] = (realtype) -3.3250000000000002e-01;
work->Prob.Ae[2540] = (realtype) 9.7609999999999997e-01;
work->Prob.Ae[2541] = (realtype) -3.4489999999999998e-01;
work->Prob.Ae[2542] = (realtype) 1.9641999999999999e+00;
work->Prob.Ae[2543] = (realtype) -2.1750000000000000e-01;
work->Prob.Ae[2624] = (realtype) 1.5190000000000001e-01;
work->Prob.Ae[2625] = (realtype) -1.6122000000000001e+00;
work->Prob.Ae[2626] = (realtype) 1.1580000000000000e-01;
work->Prob.Ae[2627] = (realtype) -8.8200000000000001e-02;
work->Prob.Ae[2628] = (realtype) -1.7692000000000001e+00;
work->Prob.Ae[2629] = (realtype) -9.9050000000000005e-01;
work->Prob.Ae[2630] = (realtype) 3.4339999999999998e-01;
work->Prob.Ae[2631] = (realtype) -8.0930000000000002e-01;
work->Prob.Ae[2704] = (realtype) -8.2999999999999996e-01;
work->Prob.Ae[2705] = (realtype) -1.0810999999999999e+00;
work->Prob.Ae[2706] = (realtype) -7.1870000000000001e-01;
work->Prob.Ae[2707] = (realtype) 8.1850000000000001e-01;
work->Prob.Ae[2708] = (realtype) 9.9319999999999997e-01;
work->Prob.Ae[2709] = (realtype) 7.4519999999999997e-01;
work->Prob.Ae[2710] = (realtype) -1.8550000000000000e-01;
work->Prob.Ae[2711] = (realtype) -6.2819999999999998e-01;
work->Prob.Ae[2784] = (realtype) -7.2980000000000000e-01;
work->Prob.Ae[2785] = (realtype) 1.1590000000000000e+00;
work->Prob.Ae[2786] = (realtype) 1.3983000000000001e+00;
work->Prob.Ae[2787] = (realtype) -5.9099999999999997e-01;
work->Prob.Ae[2788] = (realtype) -1.7640000000000000e-01;
work->Prob.Ae[2789] = (realtype) 2.0600000000000000e-02;
work->Prob.Ae[2790] = (realtype) -8.2650000000000001e-01;
work->Prob.Ae[2791] = (realtype) -7.1650000000000003e-01;
work->Prob.Ae[2864] = (realtype) 1.4262999999999999e+00;
work->Prob.Ae[2865] = (realtype) -1.8850000000000000e-01;
work->Prob.Ae[2866] = (realtype) 9.1200000000000003e-01;
work->Prob.Ae[2867] = (realtype) -3.3250000000000002e-01;
work->Prob.Ae[2868] = (realtype) 9.7609999999999997e-01;
work->Prob.Ae[2869] = (realtype) -3.4489999999999998e-01;
work->Prob.Ae[2870] = (realtype) 1.9641999999999999e+00;
work->Prob.Ae[2871] = (realtype) -2.1750000000000000e-01;
work->Prob.Ae[2952] = (realtype) 1.5190000000000001e-01;
work->Prob.Ae[2953] = (realtype) -1.6122000000000001e+00;
work->Prob.Ae[2954] = (realtype) 1.1580000000000000e-01;
work->Prob.Ae[2955] = (realtype) -8.8200000000000001e-02;
work->Prob.Ae[2956] = (realtype) -1.7692000000000001e+00;
work->Prob.Ae[2957] = (realtype) -9.9050000000000005e-01;
work->Prob.Ae[2958] = (realtype) 3.4339999999999998e-01;
work->Prob.Ae[2959] = (realtype) -8.0930000000000002e-01;
work->Prob.Ae[3032] = (realtype) -8.2999999999999996e-01;
work->Prob.Ae[3033] = (realtype) -1.0810999999999999e+00;
work->Prob.Ae[3034] = (realtype) -7.1870000000000001e-01;
work->Prob.Ae[3035] = (realtype) 8.1850000000000001e-01;
work->Prob.Ae[3036] = (realtype) 9.9319999999999997e-01;
work->Prob.Ae[3037] = (realtype) 7.4519999999999997e-01;
work->Prob.Ae[3038] = (realtype) -1.8550000000000000e-01;
work->Prob.Ae[3039] = (realtype) -6.2819999999999998e-01;
work->Prob.Ae[3112] = (realtype) -7.2980000000000000e-01;
work->Prob.Ae[3113] = (realtype) 1.1590000000000000e+00;
work->Prob.Ae[3114] = (realtype) 1.3983000000000001e+00;
work->Prob.Ae[3115] = (realtype) -5.9099999999999997e-01;
work->Prob.Ae[3116] = (realtype) -1.7640000000000000e-01;
work->Prob.Ae[3117] = (realtype) 2.0600000000000000e-02;
work->Prob.Ae[3118] = (realtype) -8.2650000000000001e-01;
work->Prob.Ae[3119] = (realtype) -7.1650000000000003e-01;
work->Prob.Ae[3192] = (realtype) 1.4262999999999999e+00;
work->Prob.Ae[3193] = (realtype) -1.8850000000000000e-01;
work->Prob.Ae[3194] = (realtype) 9.1200000000000003e-01;
work->Prob.Ae[3195] = (realtype) -3.3250000000000002e-01;
work->Prob.Ae[3196] = (realtype) 9.7609999999999997e-01;
work->Prob.Ae[3197] = (realtype) -3.4489999999999998e-01;
work->Prob.Ae[3198] = (realtype) 1.9641999999999999e+00;
work->Prob.Ae[3199] = (realtype) -2.1750000000000000e-01;
work->Prob.Ae[3200] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[3208] = (realtype) -3.7999999999999999e-02;
work->Prob.Ae[3209] = (realtype) 7.6700000000000004e-02;
work->Prob.Ae[3210] = (realtype) 3.1309999999999999e-01;
work->Prob.Ae[3211] = (realtype) -8.6900000000000005e-02;
work->Prob.Ae[3212] = (realtype) -3.2710000000000000e-01;
work->Prob.Ae[3213] = (realtype) -3.9500000000000000e-02;
work->Prob.Ae[3214] = (realtype) 2.6929999999999998e-01;
work->Prob.Ae[3215] = (realtype) 1.4010000000000000e-01;
work->Prob.Ae[3281] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[3288] = (realtype) -3.4700000000000002e-02;
work->Prob.Ae[3289] = (realtype) 5.6020000000000003e-01;
work->Prob.Ae[3290] = (realtype) -1.8379999999999999e-01;
work->Prob.Ae[3291] = (realtype) 5.2900000000000003e-02;
work->Prob.Ae[3292] = (realtype) 3.6309999999999998e-01;
work->Prob.Ae[3293] = (realtype) -1.2340000000000000e-01;
work->Prob.Ae[3294] = (realtype) 1.9199999999999998e-02;
work->Prob.Ae[3295] = (realtype) 1.1269999999999999e-01;
work->Prob.Ae[3362] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[3368] = (realtype) -1.5700000000000000e-01;
work->Prob.Ae[3369] = (realtype) 1.3400000000000000e-02;
work->Prob.Ae[3370] = (realtype) 1.7540000000000000e-01;
work->Prob.Ae[3371] = (realtype) -2.2439999999999999e-01;
work->Prob.Ae[3372] = (realtype) -1.9800000000000002e-02;
work->Prob.Ae[3373] = (realtype) -3.4010000000000001e-01;
work->Prob.Ae[3374] = (realtype) 1.3530000000000000e-01;
work->Prob.Ae[3375] = (realtype) -1.4230000000000001e-01;
work->Prob.Ae[3443] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[3448] = (realtype) 7.0499999999999993e-02;
work->Prob.Ae[3449] = (realtype) -4.9299999999999999e-01;
work->Prob.Ae[3450] = (realtype) 1.7100000000000001e-02;
work->Prob.Ae[3451] = (realtype) 5.5599999999999997e-02;
work->Prob.Ae[3452] = (realtype) 1.5900000000000001e-02;
work->Prob.Ae[3453] = (realtype) -2.3400000000000001e-01;
work->Prob.Ae[3454] = (realtype) 2.1950000000000000e-01;
work->Prob.Ae[3455] = (realtype) -3.1830000000000003e-01;
work->Prob.Ae[3524] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[3528] = (realtype) 7.0000000000000001e-03;
work->Prob.Ae[3529] = (realtype) -2.8000000000000001e-02;
work->Prob.Ae[3530] = (realtype) -1.7200000000000000e-02;
work->Prob.Ae[3531] = (realtype) -4.9230000000000002e-01;
work->Prob.Ae[3532] = (realtype) -1.2889999999999999e-01;
work->Prob.Ae[3533] = (realtype) -1.4699999999999999e-01;
work->Prob.Ae[3534] = (realtype) 1.2360000000000000e-01;
work->Prob.Ae[3535] = (realtype) -1.0220000000000000e-01;
work->Prob.Ae[3605] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[3608] = (realtype) -1.3700000000000000e-02;
work->Prob.Ae[3609] = (realtype) 2.5499999999999998e-02;
work->Prob.Ae[3610] = (realtype) 1.5640000000000001e-01;
work->Prob.Ae[3611] = (realtype) -3.3900000000000000e-02;
work->Prob.Ae[3612] = (realtype) -2.1859999999999999e-01;
work->Prob.Ae[3613] = (realtype) 2.0300000000000001e-01;
work->Prob.Ae[3614] = (realtype) -1.6299999999999999e-02;
work->Prob.Ae[3615] = (realtype) 5.7799999999999997e-02;
work->Prob.Ae[3686] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[3688] = (realtype) 1.7230000000000001e-01;
work->Prob.Ae[3689] = (realtype) 3.9360000000000001e-01;
work->Prob.Ae[3690] = (realtype) -1.8200000000000001e-02;
work->Prob.Ae[3691] = (realtype) 1.5340000000000001e-01;
work->Prob.Ae[3692] = (realtype) -4.6399999999999997e-02;
work->Prob.Ae[3693] = (realtype) -9.7999999999999997e-03;
work->Prob.Ae[3694] = (realtype) -5.1700000000000003e-02;
work->Prob.Ae[3695] = (realtype) 1.2320000000000000e-01;
work->Prob.Ae[3767] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[3768] = (realtype) 1.6650000000000001e-01;
work->Prob.Ae[3769] = (realtype) -1.6289999999999999e-01;
work->Prob.Ae[3770] = (realtype) -1.4999999999999999e-01;
work->Prob.Ae[3771] = (realtype) -1.4870000000000000e-01;
work->Prob.Ae[3772] = (realtype) 4.4000000000000003e-03;
work->Prob.Ae[3773] = (realtype) 2.1600000000000000e-01;
work->Prob.Ae[3774] = (realtype) -7.7000000000000002e-03;
work->Prob.Ae[3775] = (realtype) -1.1100000000000000e-02;
work->Prob.Ae[3848] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[3856] = (realtype) -3.7999999999999999e-02;
work->Prob.Ae[3857] = (realtype) 7.6700000000000004e-02;
work->Prob.Ae[3858] = (realtype) 3.1309999999999999e-01;
work->Prob.Ae[3859] = (realtype) -8.6900000000000005e-02;
work->Prob.Ae[3860] = (realtype) -3.2710000000000000e-01;
work->Prob.Ae[3861] = (realtype) -3.9500000000000000e-02;
work->Prob.Ae[3862] = (realtype) 2.6929999999999998e-01;
work->Prob.Ae[3863] = (realtype) 1.4010000000000000e-01;
work->Prob.Ae[3929] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[3936] = (realtype) -3.4700000000000002e-02;
work->Prob.Ae[3937] = (realtype) 5.6020000000000003e-01;
work->Prob.Ae[3938] = (realtype) -1.8379999999999999e-01;
work->Prob.Ae[3939] = (realtype) 5.2900000000000003e-02;
work->Prob.Ae[3940] = (realtype) 3.6309999999999998e-01;
work->Prob.Ae[3941] = (realtype) -1.2340000000000000e-01;
work->Prob.Ae[3942] = (realtype) 1.9199999999999998e-02;
work->Prob.Ae[3943] = (realtype) 1.1269999999999999e-01;
work->Prob.Ae[4010] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[4016] = (realtype) -1.5700000000000000e-01;
work->Prob.Ae[4017] = (realtype) 1.3400000000000000e-02;
work->Prob.Ae[4018] = (realtype) 1.7540000000000000e-01;
work->Prob.Ae[4019] = (realtype) -2.2439999999999999e-01;
work->Prob.Ae[4020] = (realtype) -1.9800000000000002e-02;
work->Prob.Ae[4021] = (realtype) -3.4010000000000001e-01;
work->Prob.Ae[4022] = (realtype) 1.3530000000000000e-01;
work->Prob.Ae[4023] = (realtype) -1.4230000000000001e-01;
work->Prob.Ae[4091] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[4096] = (realtype) 7.0499999999999993e-02;
work->Prob.Ae[4097] = (realtype) -4.9299999999999999e-01;
work->Prob.Ae[4098] = (realtype) 1.7100000000000001e-02;
work->Prob.Ae[4099] = (realtype) 5.5599999999999997e-02;
work->Prob.Ae[4100] = (realtype) 1.5900000000000001e-02;
work->Prob.Ae[4101] = (realtype) -2.3400000000000001e-01;
work->Prob.Ae[4102] = (realtype) 2.1950000000000000e-01;
work->Prob.Ae[4103] = (realtype) -3.1830000000000003e-01;
work->Prob.Ae[4172] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[4176] = (realtype) 7.0000000000000001e-03;
work->Prob.Ae[4177] = (realtype) -2.8000000000000001e-02;
work->Prob.Ae[4178] = (realtype) -1.7200000000000000e-02;
work->Prob.Ae[4179] = (realtype) -4.9230000000000002e-01;
work->Prob.Ae[4180] = (realtype) -1.2889999999999999e-01;
work->Prob.Ae[4181] = (realtype) -1.4699999999999999e-01;
work->Prob.Ae[4182] = (realtype) 1.2360000000000000e-01;
work->Prob.Ae[4183] = (realtype) -1.0220000000000000e-01;
work->Prob.Ae[4253] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[4256] = (realtype) -1.3700000000000000e-02;
work->Prob.Ae[4257] = (realtype) 2.5499999999999998e-02;
work->Prob.Ae[4258] = (realtype) 1.5640000000000001e-01;
work->Prob.Ae[4259] = (realtype) -3.3900000000000000e-02;
work->Prob.Ae[4260] = (realtype) -2.1859999999999999e-01;
work->Prob.Ae[4261] = (realtype) 2.0300000000000001e-01;
work->Prob.Ae[4262] = (realtype) -1.6299999999999999e-02;
work->Prob.Ae[4263] = (realtype) 5.7799999999999997e-02;
work->Prob.Ae[4334] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[4336] = (realtype) 1.7230000000000001e-01;
work->Prob.Ae[4337] = (realtype) 3.9360000000000001e-01;
work->Prob.Ae[4338] = (realtype) -1.8200000000000001e-02;
work->Prob.Ae[4339] = (realtype) 1.5340000000000001e-01;
work->Prob.Ae[4340] = (realtype) -4.6399999999999997e-02;
work->Prob.Ae[4341] = (realtype) -9.7999999999999997e-03;
work->Prob.Ae[4342] = (realtype) -5.1700000000000003e-02;
work->Prob.Ae[4343] = (realtype) 1.2320000000000000e-01;
work->Prob.Ae[4415] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[4416] = (realtype) 1.6650000000000001e-01;
work->Prob.Ae[4417] = (realtype) -1.6289999999999999e-01;
work->Prob.Ae[4418] = (realtype) -1.4999999999999999e-01;
work->Prob.Ae[4419] = (realtype) -1.4870000000000000e-01;
work->Prob.Ae[4420] = (realtype) 4.4000000000000003e-03;
work->Prob.Ae[4421] = (realtype) 2.1600000000000000e-01;
work->Prob.Ae[4422] = (realtype) -7.7000000000000002e-03;
work->Prob.Ae[4423] = (realtype) -1.1100000000000000e-02;
work->Prob.Ae[4496] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[4504] = (realtype) -3.7999999999999999e-02;
work->Prob.Ae[4505] = (realtype) 7.6700000000000004e-02;
work->Prob.Ae[4506] = (realtype) 3.1309999999999999e-01;
work->Prob.Ae[4507] = (realtype) -8.6900000000000005e-02;
work->Prob.Ae[4508] = (realtype) -3.2710000000000000e-01;
work->Prob.Ae[4509] = (realtype) -3.9500000000000000e-02;
work->Prob.Ae[4510] = (realtype) 2.6929999999999998e-01;
work->Prob.Ae[4511] = (realtype) 1.4010000000000000e-01;
work->Prob.Ae[4577] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[4584] = (realtype) -3.4700000000000002e-02;
work->Prob.Ae[4585] = (realtype) 5.6020000000000003e-01;
work->Prob.Ae[4586] = (realtype) -1.8379999999999999e-01;
work->Prob.Ae[4587] = (realtype) 5.2900000000000003e-02;
work->Prob.Ae[4588] = (realtype) 3.6309999999999998e-01;
work->Prob.Ae[4589] = (realtype) -1.2340000000000000e-01;
work->Prob.Ae[4590] = (realtype) 1.9199999999999998e-02;
work->Prob.Ae[4591] = (realtype) 1.1269999999999999e-01;
work->Prob.Ae[4658] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[4664] = (realtype) -1.5700000000000000e-01;
work->Prob.Ae[4665] = (realtype) 1.3400000000000000e-02;
work->Prob.Ae[4666] = (realtype) 1.7540000000000000e-01;
work->Prob.Ae[4667] = (realtype) -2.2439999999999999e-01;
work->Prob.Ae[4668] = (realtype) -1.9800000000000002e-02;
work->Prob.Ae[4669] = (realtype) -3.4010000000000001e-01;
work->Prob.Ae[4670] = (realtype) 1.3530000000000000e-01;
work->Prob.Ae[4671] = (realtype) -1.4230000000000001e-01;
work->Prob.Ae[4739] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[4744] = (realtype) 7.0499999999999993e-02;
work->Prob.Ae[4745] = (realtype) -4.9299999999999999e-01;
work->Prob.Ae[4746] = (realtype) 1.7100000000000001e-02;
work->Prob.Ae[4747] = (realtype) 5.5599999999999997e-02;
work->Prob.Ae[4748] = (realtype) 1.5900000000000001e-02;
work->Prob.Ae[4749] = (realtype) -2.3400000000000001e-01;
work->Prob.Ae[4750] = (realtype) 2.1950000000000000e-01;
work->Prob.Ae[4751] = (realtype) -3.1830000000000003e-01;
work->Prob.Ae[4820] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[4824] = (realtype) 7.0000000000000001e-03;
work->Prob.Ae[4825] = (realtype) -2.8000000000000001e-02;
work->Prob.Ae[4826] = (realtype) -1.7200000000000000e-02;
work->Prob.Ae[4827] = (realtype) -4.9230000000000002e-01;
work->Prob.Ae[4828] = (realtype) -1.2889999999999999e-01;
work->Prob.Ae[4829] = (realtype) -1.4699999999999999e-01;
work->Prob.Ae[4830] = (realtype) 1.2360000000000000e-01;
work->Prob.Ae[4831] = (realtype) -1.0220000000000000e-01;
work->Prob.Ae[4901] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[4904] = (realtype) -1.3700000000000000e-02;
work->Prob.Ae[4905] = (realtype) 2.5499999999999998e-02;
work->Prob.Ae[4906] = (realtype) 1.5640000000000001e-01;
work->Prob.Ae[4907] = (realtype) -3.3900000000000000e-02;
work->Prob.Ae[4908] = (realtype) -2.1859999999999999e-01;
work->Prob.Ae[4909] = (realtype) 2.0300000000000001e-01;
work->Prob.Ae[4910] = (realtype) -1.6299999999999999e-02;
work->Prob.Ae[4911] = (realtype) 5.7799999999999997e-02;
work->Prob.Ae[4982] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[4984] = (realtype) 1.7230000000000001e-01;
work->Prob.Ae[4985] = (realtype) 3.9360000000000001e-01;
work->Prob.Ae[4986] = (realtype) -1.8200000000000001e-02;
work->Prob.Ae[4987] = (realtype) 1.5340000000000001e-01;
work->Prob.Ae[4988] = (realtype) -4.6399999999999997e-02;
work->Prob.Ae[4989] = (realtype) -9.7999999999999997e-03;
work->Prob.Ae[4990] = (realtype) -5.1700000000000003e-02;
work->Prob.Ae[4991] = (realtype) 1.2320000000000000e-01;
work->Prob.Ae[5063] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[5064] = (realtype) 1.6650000000000001e-01;
work->Prob.Ae[5065] = (realtype) -1.6289999999999999e-01;
work->Prob.Ae[5066] = (realtype) -1.4999999999999999e-01;
work->Prob.Ae[5067] = (realtype) -1.4870000000000000e-01;
work->Prob.Ae[5068] = (realtype) 4.4000000000000003e-03;
work->Prob.Ae[5069] = (realtype) 2.1600000000000000e-01;
work->Prob.Ae[5070] = (realtype) -7.7000000000000002e-03;
work->Prob.Ae[5071] = (realtype) -1.1100000000000000e-02;
work->Prob.Ae[5144] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[5152] = (realtype) -3.7999999999999999e-02;
work->Prob.Ae[5153] = (realtype) 7.6700000000000004e-02;
work->Prob.Ae[5154] = (realtype) 3.1309999999999999e-01;
work->Prob.Ae[5155] = (realtype) -8.6900000000000005e-02;
work->Prob.Ae[5156] = (realtype) -3.2710000000000000e-01;
work->Prob.Ae[5157] = (realtype) -3.9500000000000000e-02;
work->Prob.Ae[5158] = (realtype) 2.6929999999999998e-01;
work->Prob.Ae[5159] = (realtype) 1.4010000000000000e-01;
work->Prob.Ae[5225] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[5232] = (realtype) -3.4700000000000002e-02;
work->Prob.Ae[5233] = (realtype) 5.6020000000000003e-01;
work->Prob.Ae[5234] = (realtype) -1.8379999999999999e-01;
work->Prob.Ae[5235] = (realtype) 5.2900000000000003e-02;
work->Prob.Ae[5236] = (realtype) 3.6309999999999998e-01;
work->Prob.Ae[5237] = (realtype) -1.2340000000000000e-01;
work->Prob.Ae[5238] = (realtype) 1.9199999999999998e-02;
work->Prob.Ae[5239] = (realtype) 1.1269999999999999e-01;
work->Prob.Ae[5306] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[5312] = (realtype) -1.5700000000000000e-01;
work->Prob.Ae[5313] = (realtype) 1.3400000000000000e-02;
work->Prob.Ae[5314] = (realtype) 1.7540000000000000e-01;
work->Prob.Ae[5315] = (realtype) -2.2439999999999999e-01;
work->Prob.Ae[5316] = (realtype) -1.9800000000000002e-02;
work->Prob.Ae[5317] = (realtype) -3.4010000000000001e-01;
work->Prob.Ae[5318] = (realtype) 1.3530000000000000e-01;
work->Prob.Ae[5319] = (realtype) -1.4230000000000001e-01;
work->Prob.Ae[5387] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[5392] = (realtype) 7.0499999999999993e-02;
work->Prob.Ae[5393] = (realtype) -4.9299999999999999e-01;
work->Prob.Ae[5394] = (realtype) 1.7100000000000001e-02;
work->Prob.Ae[5395] = (realtype) 5.5599999999999997e-02;
work->Prob.Ae[5396] = (realtype) 1.5900000000000001e-02;
work->Prob.Ae[5397] = (realtype) -2.3400000000000001e-01;
work->Prob.Ae[5398] = (realtype) 2.1950000000000000e-01;
work->Prob.Ae[5399] = (realtype) -3.1830000000000003e-01;
work->Prob.Ae[5468] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[5472] = (realtype) 7.0000000000000001e-03;
work->Prob.Ae[5473] = (realtype) -2.8000000000000001e-02;
work->Prob.Ae[5474] = (realtype) -1.7200000000000000e-02;
work->Prob.Ae[5475] = (realtype) -4.9230000000000002e-01;
work->Prob.Ae[5476] = (realtype) -1.2889999999999999e-01;
work->Prob.Ae[5477] = (realtype) -1.4699999999999999e-01;
work->Prob.Ae[5478] = (realtype) 1.2360000000000000e-01;
work->Prob.Ae[5479] = (realtype) -1.0220000000000000e-01;
work->Prob.Ae[5549] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[5552] = (realtype) -1.3700000000000000e-02;
work->Prob.Ae[5553] = (realtype) 2.5499999999999998e-02;
work->Prob.Ae[5554] = (realtype) 1.5640000000000001e-01;
work->Prob.Ae[5555] = (realtype) -3.3900000000000000e-02;
work->Prob.Ae[5556] = (realtype) -2.1859999999999999e-01;
work->Prob.Ae[5557] = (realtype) 2.0300000000000001e-01;
work->Prob.Ae[5558] = (realtype) -1.6299999999999999e-02;
work->Prob.Ae[5559] = (realtype) 5.7799999999999997e-02;
work->Prob.Ae[5630] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[5632] = (realtype) 1.7230000000000001e-01;
work->Prob.Ae[5633] = (realtype) 3.9360000000000001e-01;
work->Prob.Ae[5634] = (realtype) -1.8200000000000001e-02;
work->Prob.Ae[5635] = (realtype) 1.5340000000000001e-01;
work->Prob.Ae[5636] = (realtype) -4.6399999999999997e-02;
work->Prob.Ae[5637] = (realtype) -9.7999999999999997e-03;
work->Prob.Ae[5638] = (realtype) -5.1700000000000003e-02;
work->Prob.Ae[5639] = (realtype) 1.2320000000000000e-01;
work->Prob.Ae[5711] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[5712] = (realtype) 1.6650000000000001e-01;
work->Prob.Ae[5713] = (realtype) -1.6289999999999999e-01;
work->Prob.Ae[5714] = (realtype) -1.4999999999999999e-01;
work->Prob.Ae[5715] = (realtype) -1.4870000000000000e-01;
work->Prob.Ae[5716] = (realtype) 4.4000000000000003e-03;
work->Prob.Ae[5717] = (realtype) 2.1600000000000000e-01;
work->Prob.Ae[5718] = (realtype) -7.7000000000000002e-03;
work->Prob.Ae[5719] = (realtype) -1.1100000000000000e-02;
work->Prob.Ae[5792] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[5800] = (realtype) -3.7999999999999999e-02;
work->Prob.Ae[5801] = (realtype) 7.6700000000000004e-02;
work->Prob.Ae[5802] = (realtype) 3.1309999999999999e-01;
work->Prob.Ae[5803] = (realtype) -8.6900000000000005e-02;
work->Prob.Ae[5804] = (realtype) -3.2710000000000000e-01;
work->Prob.Ae[5805] = (realtype) -3.9500000000000000e-02;
work->Prob.Ae[5806] = (realtype) 2.6929999999999998e-01;
work->Prob.Ae[5807] = (realtype) 1.4010000000000000e-01;
work->Prob.Ae[5873] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[5880] = (realtype) -3.4700000000000002e-02;
work->Prob.Ae[5881] = (realtype) 5.6020000000000003e-01;
work->Prob.Ae[5882] = (realtype) -1.8379999999999999e-01;
work->Prob.Ae[5883] = (realtype) 5.2900000000000003e-02;
work->Prob.Ae[5884] = (realtype) 3.6309999999999998e-01;
work->Prob.Ae[5885] = (realtype) -1.2340000000000000e-01;
work->Prob.Ae[5886] = (realtype) 1.9199999999999998e-02;
work->Prob.Ae[5887] = (realtype) 1.1269999999999999e-01;
work->Prob.Ae[5954] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[5960] = (realtype) -1.5700000000000000e-01;
work->Prob.Ae[5961] = (realtype) 1.3400000000000000e-02;
work->Prob.Ae[5962] = (realtype) 1.7540000000000000e-01;
work->Prob.Ae[5963] = (realtype) -2.2439999999999999e-01;
work->Prob.Ae[5964] = (realtype) -1.9800000000000002e-02;
work->Prob.Ae[5965] = (realtype) -3.4010000000000001e-01;
work->Prob.Ae[5966] = (realtype) 1.3530000000000000e-01;
work->Prob.Ae[5967] = (realtype) -1.4230000000000001e-01;
work->Prob.Ae[6035] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[6040] = (realtype) 7.0499999999999993e-02;
work->Prob.Ae[6041] = (realtype) -4.9299999999999999e-01;
work->Prob.Ae[6042] = (realtype) 1.7100000000000001e-02;
work->Prob.Ae[6043] = (realtype) 5.5599999999999997e-02;
work->Prob.Ae[6044] = (realtype) 1.5900000000000001e-02;
work->Prob.Ae[6045] = (realtype) -2.3400000000000001e-01;
work->Prob.Ae[6046] = (realtype) 2.1950000000000000e-01;
work->Prob.Ae[6047] = (realtype) -3.1830000000000003e-01;
work->Prob.Ae[6116] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[6120] = (realtype) 7.0000000000000001e-03;
work->Prob.Ae[6121] = (realtype) -2.8000000000000001e-02;
work->Prob.Ae[6122] = (realtype) -1.7200000000000000e-02;
work->Prob.Ae[6123] = (realtype) -4.9230000000000002e-01;
work->Prob.Ae[6124] = (realtype) -1.2889999999999999e-01;
work->Prob.Ae[6125] = (realtype) -1.4699999999999999e-01;
work->Prob.Ae[6126] = (realtype) 1.2360000000000000e-01;
work->Prob.Ae[6127] = (realtype) -1.0220000000000000e-01;
work->Prob.Ae[6197] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[6200] = (realtype) -1.3700000000000000e-02;
work->Prob.Ae[6201] = (realtype) 2.5499999999999998e-02;
work->Prob.Ae[6202] = (realtype) 1.5640000000000001e-01;
work->Prob.Ae[6203] = (realtype) -3.3900000000000000e-02;
work->Prob.Ae[6204] = (realtype) -2.1859999999999999e-01;
work->Prob.Ae[6205] = (realtype) 2.0300000000000001e-01;
work->Prob.Ae[6206] = (realtype) -1.6299999999999999e-02;
work->Prob.Ae[6207] = (realtype) 5.7799999999999997e-02;
work->Prob.Ae[6278] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[6280] = (realtype) 1.7230000000000001e-01;
work->Prob.Ae[6281] = (realtype) 3.9360000000000001e-01;
work->Prob.Ae[6282] = (realtype) -1.8200000000000001e-02;
work->Prob.Ae[6283] = (realtype) 1.5340000000000001e-01;
work->Prob.Ae[6284] = (realtype) -4.6399999999999997e-02;
work->Prob.Ae[6285] = (realtype) -9.7999999999999997e-03;
work->Prob.Ae[6286] = (realtype) -5.1700000000000003e-02;
work->Prob.Ae[6287] = (realtype) 1.2320000000000000e-01;
work->Prob.Ae[6359] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[6360] = (realtype) 1.6650000000000001e-01;
work->Prob.Ae[6361] = (realtype) -1.6289999999999999e-01;
work->Prob.Ae[6362] = (realtype) -1.4999999999999999e-01;
work->Prob.Ae[6363] = (realtype) -1.4870000000000000e-01;
work->Prob.Ae[6364] = (realtype) 4.4000000000000003e-03;
work->Prob.Ae[6365] = (realtype) 2.1600000000000000e-01;
work->Prob.Ae[6366] = (realtype) -7.7000000000000002e-03;
work->Prob.Ae[6367] = (realtype) -1.1100000000000000e-02;
work->Prob.Ae[6440] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[6448] = (realtype) -3.7999999999999999e-02;
work->Prob.Ae[6449] = (realtype) 7.6700000000000004e-02;
work->Prob.Ae[6450] = (realtype) 3.1309999999999999e-01;
work->Prob.Ae[6451] = (realtype) -8.6900000000000005e-02;
work->Prob.Ae[6452] = (realtype) -3.2710000000000000e-01;
work->Prob.Ae[6453] = (realtype) -3.9500000000000000e-02;
work->Prob.Ae[6454] = (realtype) 2.6929999999999998e-01;
work->Prob.Ae[6455] = (realtype) 1.4010000000000000e-01;
work->Prob.Ae[6521] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[6528] = (realtype) -3.4700000000000002e-02;
work->Prob.Ae[6529] = (realtype) 5.6020000000000003e-01;
work->Prob.Ae[6530] = (realtype) -1.8379999999999999e-01;
work->Prob.Ae[6531] = (realtype) 5.2900000000000003e-02;
work->Prob.Ae[6532] = (realtype) 3.6309999999999998e-01;
work->Prob.Ae[6533] = (realtype) -1.2340000000000000e-01;
work->Prob.Ae[6534] = (realtype) 1.9199999999999998e-02;
work->Prob.Ae[6535] = (realtype) 1.1269999999999999e-01;
work->Prob.Ae[6602] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[6608] = (realtype) -1.5700000000000000e-01;
work->Prob.Ae[6609] = (realtype) 1.3400000000000000e-02;
work->Prob.Ae[6610] = (realtype) 1.7540000000000000e-01;
work->Prob.Ae[6611] = (realtype) -2.2439999999999999e-01;
work->Prob.Ae[6612] = (realtype) -1.9800000000000002e-02;
work->Prob.Ae[6613] = (realtype) -3.4010000000000001e-01;
work->Prob.Ae[6614] = (realtype) 1.3530000000000000e-01;
work->Prob.Ae[6615] = (realtype) -1.4230000000000001e-01;
work->Prob.Ae[6683] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[6688] = (realtype) 7.0499999999999993e-02;
work->Prob.Ae[6689] = (realtype) -4.9299999999999999e-01;
work->Prob.Ae[6690] = (realtype) 1.7100000000000001e-02;
work->Prob.Ae[6691] = (realtype) 5.5599999999999997e-02;
work->Prob.Ae[6692] = (realtype) 1.5900000000000001e-02;
work->Prob.Ae[6693] = (realtype) -2.3400000000000001e-01;
work->Prob.Ae[6694] = (realtype) 2.1950000000000000e-01;
work->Prob.Ae[6695] = (realtype) -3.1830000000000003e-01;
work->Prob.Ae[6764] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[6768] = (realtype) 7.0000000000000001e-03;
work->Prob.Ae[6769] = (realtype) -2.8000000000000001e-02;
work->Prob.Ae[6770] = (realtype) -1.7200000000000000e-02;
work->Prob.Ae[6771] = (realtype) -4.9230000000000002e-01;
work->Prob.Ae[6772] = (realtype) -1.2889999999999999e-01;
work->Prob.Ae[6773] = (realtype) -1.4699999999999999e-01;
work->Prob.Ae[6774] = (realtype) 1.2360000000000000e-01;
work->Prob.Ae[6775] = (realtype) -1.0220000000000000e-01;
work->Prob.Ae[6845] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[6848] = (realtype) -1.3700000000000000e-02;
work->Prob.Ae[6849] = (realtype) 2.5499999999999998e-02;
work->Prob.Ae[6850] = (realtype) 1.5640000000000001e-01;
work->Prob.Ae[6851] = (realtype) -3.3900000000000000e-02;
work->Prob.Ae[6852] = (realtype) -2.1859999999999999e-01;
work->Prob.Ae[6853] = (realtype) 2.0300000000000001e-01;
work->Prob.Ae[6854] = (realtype) -1.6299999999999999e-02;
work->Prob.Ae[6855] = (realtype) 5.7799999999999997e-02;
work->Prob.Ae[6926] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[6928] = (realtype) 1.7230000000000001e-01;
work->Prob.Ae[6929] = (realtype) 3.9360000000000001e-01;
work->Prob.Ae[6930] = (realtype) -1.8200000000000001e-02;
work->Prob.Ae[6931] = (realtype) 1.5340000000000001e-01;
work->Prob.Ae[6932] = (realtype) -4.6399999999999997e-02;
work->Prob.Ae[6933] = (realtype) -9.7999999999999997e-03;
work->Prob.Ae[6934] = (realtype) -5.1700000000000003e-02;
work->Prob.Ae[6935] = (realtype) 1.2320000000000000e-01;
work->Prob.Ae[7007] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[7008] = (realtype) 1.6650000000000001e-01;
work->Prob.Ae[7009] = (realtype) -1.6289999999999999e-01;
work->Prob.Ae[7010] = (realtype) -1.4999999999999999e-01;
work->Prob.Ae[7011] = (realtype) -1.4870000000000000e-01;
work->Prob.Ae[7012] = (realtype) 4.4000000000000003e-03;
work->Prob.Ae[7013] = (realtype) 2.1600000000000000e-01;
work->Prob.Ae[7014] = (realtype) -7.7000000000000002e-03;
work->Prob.Ae[7015] = (realtype) -1.1100000000000000e-02;
work->Prob.Ae[7088] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[7096] = (realtype) -3.7999999999999999e-02;
work->Prob.Ae[7097] = (realtype) 7.6700000000000004e-02;
work->Prob.Ae[7098] = (realtype) 3.1309999999999999e-01;
work->Prob.Ae[7099] = (realtype) -8.6900000000000005e-02;
work->Prob.Ae[7100] = (realtype) -3.2710000000000000e-01;
work->Prob.Ae[7101] = (realtype) -3.9500000000000000e-02;
work->Prob.Ae[7102] = (realtype) 2.6929999999999998e-01;
work->Prob.Ae[7103] = (realtype) 1.4010000000000000e-01;
work->Prob.Ae[7169] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[7176] = (realtype) -3.4700000000000002e-02;
work->Prob.Ae[7177] = (realtype) 5.6020000000000003e-01;
work->Prob.Ae[7178] = (realtype) -1.8379999999999999e-01;
work->Prob.Ae[7179] = (realtype) 5.2900000000000003e-02;
work->Prob.Ae[7180] = (realtype) 3.6309999999999998e-01;
work->Prob.Ae[7181] = (realtype) -1.2340000000000000e-01;
work->Prob.Ae[7182] = (realtype) 1.9199999999999998e-02;
work->Prob.Ae[7183] = (realtype) 1.1269999999999999e-01;
work->Prob.Ae[7250] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[7256] = (realtype) -1.5700000000000000e-01;
work->Prob.Ae[7257] = (realtype) 1.3400000000000000e-02;
work->Prob.Ae[7258] = (realtype) 1.7540000000000000e-01;
work->Prob.Ae[7259] = (realtype) -2.2439999999999999e-01;
work->Prob.Ae[7260] = (realtype) -1.9800000000000002e-02;
work->Prob.Ae[7261] = (realtype) -3.4010000000000001e-01;
work->Prob.Ae[7262] = (realtype) 1.3530000000000000e-01;
work->Prob.Ae[7263] = (realtype) -1.4230000000000001e-01;
work->Prob.Ae[7331] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[7336] = (realtype) 7.0499999999999993e-02;
work->Prob.Ae[7337] = (realtype) -4.9299999999999999e-01;
work->Prob.Ae[7338] = (realtype) 1.7100000000000001e-02;
work->Prob.Ae[7339] = (realtype) 5.5599999999999997e-02;
work->Prob.Ae[7340] = (realtype) 1.5900000000000001e-02;
work->Prob.Ae[7341] = (realtype) -2.3400000000000001e-01;
work->Prob.Ae[7342] = (realtype) 2.1950000000000000e-01;
work->Prob.Ae[7343] = (realtype) -3.1830000000000003e-01;
work->Prob.Ae[7412] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[7416] = (realtype) 7.0000000000000001e-03;
work->Prob.Ae[7417] = (realtype) -2.8000000000000001e-02;
work->Prob.Ae[7418] = (realtype) -1.7200000000000000e-02;
work->Prob.Ae[7419] = (realtype) -4.9230000000000002e-01;
work->Prob.Ae[7420] = (realtype) -1.2889999999999999e-01;
work->Prob.Ae[7421] = (realtype) -1.4699999999999999e-01;
work->Prob.Ae[7422] = (realtype) 1.2360000000000000e-01;
work->Prob.Ae[7423] = (realtype) -1.0220000000000000e-01;
work->Prob.Ae[7493] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[7496] = (realtype) -1.3700000000000000e-02;
work->Prob.Ae[7497] = (realtype) 2.5499999999999998e-02;
work->Prob.Ae[7498] = (realtype) 1.5640000000000001e-01;
work->Prob.Ae[7499] = (realtype) -3.3900000000000000e-02;
work->Prob.Ae[7500] = (realtype) -2.1859999999999999e-01;
work->Prob.Ae[7501] = (realtype) 2.0300000000000001e-01;
work->Prob.Ae[7502] = (realtype) -1.6299999999999999e-02;
work->Prob.Ae[7503] = (realtype) 5.7799999999999997e-02;
work->Prob.Ae[7574] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[7576] = (realtype) 1.7230000000000001e-01;
work->Prob.Ae[7577] = (realtype) 3.9360000000000001e-01;
work->Prob.Ae[7578] = (realtype) -1.8200000000000001e-02;
work->Prob.Ae[7579] = (realtype) 1.5340000000000001e-01;
work->Prob.Ae[7580] = (realtype) -4.6399999999999997e-02;
work->Prob.Ae[7581] = (realtype) -9.7999999999999997e-03;
work->Prob.Ae[7582] = (realtype) -5.1700000000000003e-02;
work->Prob.Ae[7583] = (realtype) 1.2320000000000000e-01;
work->Prob.Ae[7655] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[7656] = (realtype) 1.6650000000000001e-01;
work->Prob.Ae[7657] = (realtype) -1.6289999999999999e-01;
work->Prob.Ae[7658] = (realtype) -1.4999999999999999e-01;
work->Prob.Ae[7659] = (realtype) -1.4870000000000000e-01;
work->Prob.Ae[7660] = (realtype) 4.4000000000000003e-03;
work->Prob.Ae[7661] = (realtype) 2.1600000000000000e-01;
work->Prob.Ae[7662] = (realtype) -7.7000000000000002e-03;
work->Prob.Ae[7663] = (realtype) -1.1100000000000000e-02;
work->Prob.Ae[7736] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[7744] = (realtype) -3.7999999999999999e-02;
work->Prob.Ae[7745] = (realtype) 7.6700000000000004e-02;
work->Prob.Ae[7746] = (realtype) 3.1309999999999999e-01;
work->Prob.Ae[7747] = (realtype) -8.6900000000000005e-02;
work->Prob.Ae[7748] = (realtype) -3.2710000000000000e-01;
work->Prob.Ae[7749] = (realtype) -3.9500000000000000e-02;
work->Prob.Ae[7750] = (realtype) 2.6929999999999998e-01;
work->Prob.Ae[7751] = (realtype) 1.4010000000000000e-01;
work->Prob.Ae[7817] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[7824] = (realtype) -3.4700000000000002e-02;
work->Prob.Ae[7825] = (realtype) 5.6020000000000003e-01;
work->Prob.Ae[7826] = (realtype) -1.8379999999999999e-01;
work->Prob.Ae[7827] = (realtype) 5.2900000000000003e-02;
work->Prob.Ae[7828] = (realtype) 3.6309999999999998e-01;
work->Prob.Ae[7829] = (realtype) -1.2340000000000000e-01;
work->Prob.Ae[7830] = (realtype) 1.9199999999999998e-02;
work->Prob.Ae[7831] = (realtype) 1.1269999999999999e-01;
work->Prob.Ae[7898] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[7904] = (realtype) -1.5700000000000000e-01;
work->Prob.Ae[7905] = (realtype) 1.3400000000000000e-02;
work->Prob.Ae[7906] = (realtype) 1.7540000000000000e-01;
work->Prob.Ae[7907] = (realtype) -2.2439999999999999e-01;
work->Prob.Ae[7908] = (realtype) -1.9800000000000002e-02;
work->Prob.Ae[7909] = (realtype) -3.4010000000000001e-01;
work->Prob.Ae[7910] = (realtype) 1.3530000000000000e-01;
work->Prob.Ae[7911] = (realtype) -1.4230000000000001e-01;
work->Prob.Ae[7979] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[7984] = (realtype) 7.0499999999999993e-02;
work->Prob.Ae[7985] = (realtype) -4.9299999999999999e-01;
work->Prob.Ae[7986] = (realtype) 1.7100000000000001e-02;
work->Prob.Ae[7987] = (realtype) 5.5599999999999997e-02;
work->Prob.Ae[7988] = (realtype) 1.5900000000000001e-02;
work->Prob.Ae[7989] = (realtype) -2.3400000000000001e-01;
work->Prob.Ae[7990] = (realtype) 2.1950000000000000e-01;
work->Prob.Ae[7991] = (realtype) -3.1830000000000003e-01;
work->Prob.Ae[8060] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[8064] = (realtype) 7.0000000000000001e-03;
work->Prob.Ae[8065] = (realtype) -2.8000000000000001e-02;
work->Prob.Ae[8066] = (realtype) -1.7200000000000000e-02;
work->Prob.Ae[8067] = (realtype) -4.9230000000000002e-01;
work->Prob.Ae[8068] = (realtype) -1.2889999999999999e-01;
work->Prob.Ae[8069] = (realtype) -1.4699999999999999e-01;
work->Prob.Ae[8070] = (realtype) 1.2360000000000000e-01;
work->Prob.Ae[8071] = (realtype) -1.0220000000000000e-01;
work->Prob.Ae[8141] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[8144] = (realtype) -1.3700000000000000e-02;
work->Prob.Ae[8145] = (realtype) 2.5499999999999998e-02;
work->Prob.Ae[8146] = (realtype) 1.5640000000000001e-01;
work->Prob.Ae[8147] = (realtype) -3.3900000000000000e-02;
work->Prob.Ae[8148] = (realtype) -2.1859999999999999e-01;
work->Prob.Ae[8149] = (realtype) 2.0300000000000001e-01;
work->Prob.Ae[8150] = (realtype) -1.6299999999999999e-02;
work->Prob.Ae[8151] = (realtype) 5.7799999999999997e-02;
work->Prob.Ae[8222] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[8224] = (realtype) 1.7230000000000001e-01;
work->Prob.Ae[8225] = (realtype) 3.9360000000000001e-01;
work->Prob.Ae[8226] = (realtype) -1.8200000000000001e-02;
work->Prob.Ae[8227] = (realtype) 1.5340000000000001e-01;
work->Prob.Ae[8228] = (realtype) -4.6399999999999997e-02;
work->Prob.Ae[8229] = (realtype) -9.7999999999999997e-03;
work->Prob.Ae[8230] = (realtype) -5.1700000000000003e-02;
work->Prob.Ae[8231] = (realtype) 1.2320000000000000e-01;
work->Prob.Ae[8303] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[8304] = (realtype) 1.6650000000000001e-01;
work->Prob.Ae[8305] = (realtype) -1.6289999999999999e-01;
work->Prob.Ae[8306] = (realtype) -1.4999999999999999e-01;
work->Prob.Ae[8307] = (realtype) -1.4870000000000000e-01;
work->Prob.Ae[8308] = (realtype) 4.4000000000000003e-03;
work->Prob.Ae[8309] = (realtype) 2.1600000000000000e-01;
work->Prob.Ae[8310] = (realtype) -7.7000000000000002e-03;
work->Prob.Ae[8311] = (realtype) -1.1100000000000000e-02;
work->Prob.Ae[8384] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[8392] = (realtype) -3.7999999999999999e-02;
work->Prob.Ae[8393] = (realtype) 7.6700000000000004e-02;
work->Prob.Ae[8394] = (realtype) 3.1309999999999999e-01;
work->Prob.Ae[8395] = (realtype) -8.6900000000000005e-02;
work->Prob.Ae[8396] = (realtype) -3.2710000000000000e-01;
work->Prob.Ae[8397] = (realtype) -3.9500000000000000e-02;
work->Prob.Ae[8398] = (realtype) 2.6929999999999998e-01;
work->Prob.Ae[8399] = (realtype) 1.4010000000000000e-01;
work->Prob.Ae[8465] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[8472] = (realtype) -3.4700000000000002e-02;
work->Prob.Ae[8473] = (realtype) 5.6020000000000003e-01;
work->Prob.Ae[8474] = (realtype) -1.8379999999999999e-01;
work->Prob.Ae[8475] = (realtype) 5.2900000000000003e-02;
work->Prob.Ae[8476] = (realtype) 3.6309999999999998e-01;
work->Prob.Ae[8477] = (realtype) -1.2340000000000000e-01;
work->Prob.Ae[8478] = (realtype) 1.9199999999999998e-02;
work->Prob.Ae[8479] = (realtype) 1.1269999999999999e-01;
work->Prob.Ae[8546] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[8552] = (realtype) -1.5700000000000000e-01;
work->Prob.Ae[8553] = (realtype) 1.3400000000000000e-02;
work->Prob.Ae[8554] = (realtype) 1.7540000000000000e-01;
work->Prob.Ae[8555] = (realtype) -2.2439999999999999e-01;
work->Prob.Ae[8556] = (realtype) -1.9800000000000002e-02;
work->Prob.Ae[8557] = (realtype) -3.4010000000000001e-01;
work->Prob.Ae[8558] = (realtype) 1.3530000000000000e-01;
work->Prob.Ae[8559] = (realtype) -1.4230000000000001e-01;
work->Prob.Ae[8627] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[8632] = (realtype) 7.0499999999999993e-02;
work->Prob.Ae[8633] = (realtype) -4.9299999999999999e-01;
work->Prob.Ae[8634] = (realtype) 1.7100000000000001e-02;
work->Prob.Ae[8635] = (realtype) 5.5599999999999997e-02;
work->Prob.Ae[8636] = (realtype) 1.5900000000000001e-02;
work->Prob.Ae[8637] = (realtype) -2.3400000000000001e-01;
work->Prob.Ae[8638] = (realtype) 2.1950000000000000e-01;
work->Prob.Ae[8639] = (realtype) -3.1830000000000003e-01;
work->Prob.Ae[8708] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[8712] = (realtype) 7.0000000000000001e-03;
work->Prob.Ae[8713] = (realtype) -2.8000000000000001e-02;
work->Prob.Ae[8714] = (realtype) -1.7200000000000000e-02;
work->Prob.Ae[8715] = (realtype) -4.9230000000000002e-01;
work->Prob.Ae[8716] = (realtype) -1.2889999999999999e-01;
work->Prob.Ae[8717] = (realtype) -1.4699999999999999e-01;
work->Prob.Ae[8718] = (realtype) 1.2360000000000000e-01;
work->Prob.Ae[8719] = (realtype) -1.0220000000000000e-01;
work->Prob.Ae[8789] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[8792] = (realtype) -1.3700000000000000e-02;
work->Prob.Ae[8793] = (realtype) 2.5499999999999998e-02;
work->Prob.Ae[8794] = (realtype) 1.5640000000000001e-01;
work->Prob.Ae[8795] = (realtype) -3.3900000000000000e-02;
work->Prob.Ae[8796] = (realtype) -2.1859999999999999e-01;
work->Prob.Ae[8797] = (realtype) 2.0300000000000001e-01;
work->Prob.Ae[8798] = (realtype) -1.6299999999999999e-02;
work->Prob.Ae[8799] = (realtype) 5.7799999999999997e-02;
work->Prob.Ae[8870] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[8872] = (realtype) 1.7230000000000001e-01;
work->Prob.Ae[8873] = (realtype) 3.9360000000000001e-01;
work->Prob.Ae[8874] = (realtype) -1.8200000000000001e-02;
work->Prob.Ae[8875] = (realtype) 1.5340000000000001e-01;
work->Prob.Ae[8876] = (realtype) -4.6399999999999997e-02;
work->Prob.Ae[8877] = (realtype) -9.7999999999999997e-03;
work->Prob.Ae[8878] = (realtype) -5.1700000000000003e-02;
work->Prob.Ae[8879] = (realtype) 1.2320000000000000e-01;
work->Prob.Ae[8951] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[8952] = (realtype) 1.6650000000000001e-01;
work->Prob.Ae[8953] = (realtype) -1.6289999999999999e-01;
work->Prob.Ae[8954] = (realtype) -1.4999999999999999e-01;
work->Prob.Ae[8955] = (realtype) -1.4870000000000000e-01;
work->Prob.Ae[8956] = (realtype) 4.4000000000000003e-03;
work->Prob.Ae[8957] = (realtype) 2.1600000000000000e-01;
work->Prob.Ae[8958] = (realtype) -7.7000000000000002e-03;
work->Prob.Ae[8959] = (realtype) -1.1100000000000000e-02;
work->Prob.Ae[9032] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[9113] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[9194] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[9275] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[9356] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[9437] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[9518] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[9599] = (realtype) 1.0000000000000000e+00;
work->Prob.X1.l[0] = (realtype) -5.0000000000000000e+00;
work->Prob.X1.l[1] = (realtype) -5.0000000000000000e+00;
work->Prob.X1.l[2] = (realtype) -5.0000000000000000e+00;
work->Prob.X1.l[3] = (realtype) -5.0000000000000000e+00;
work->Prob.X1.u[0] = (realtype) 5.0000000000000000e+00;
work->Prob.X1.u[1] = (realtype) 5.0000000000000000e+00;
work->Prob.X1.u[2] = (realtype) 5.0000000000000000e+00;
work->Prob.X1.u[3] = (realtype) 5.0000000000000000e+00;
work->Prob.X2.l[0] = (realtype) -5.0000000000000000e+00;
work->Prob.X2.l[1] = (realtype) -5.0000000000000000e+00;
work->Prob.X2.l[2] = (realtype) -5.0000000000000000e+00;
work->Prob.X2.l[3] = (realtype) -5.0000000000000000e+00;
work->Prob.X2.u[0] = (realtype) 5.0000000000000000e+00;
work->Prob.X2.u[1] = (realtype) 5.0000000000000000e+00;
work->Prob.X2.u[2] = (realtype) 5.0000000000000000e+00;
work->Prob.X2.u[3] = (realtype) 5.0000000000000000e+00;
work->Prob.X3.l[0] = (realtype) -5.0000000000000000e+00;
work->Prob.X3.l[1] = (realtype) -5.0000000000000000e+00;
work->Prob.X3.l[2] = (realtype) -5.0000000000000000e+00;
work->Prob.X3.l[3] = (realtype) -5.0000000000000000e+00;
work->Prob.X3.u[0] = (realtype) 5.0000000000000000e+00;
work->Prob.X3.u[1] = (realtype) 5.0000000000000000e+00;
work->Prob.X3.u[2] = (realtype) 5.0000000000000000e+00;
work->Prob.X3.u[3] = (realtype) 5.0000000000000000e+00;
work->Prob.X4.l[0] = (realtype) -5.0000000000000000e+00;
work->Prob.X4.l[1] = (realtype) -5.0000000000000000e+00;
work->Prob.X4.l[2] = (realtype) -5.0000000000000000e+00;
work->Prob.X4.l[3] = (realtype) -5.0000000000000000e+00;
work->Prob.X4.u[0] = (realtype) 5.0000000000000000e+00;
work->Prob.X4.u[1] = (realtype) 5.0000000000000000e+00;
work->Prob.X4.u[2] = (realtype) 5.0000000000000000e+00;
work->Prob.X4.u[3] = (realtype) 5.0000000000000000e+00;
work->Prob.X5.l[0] = (realtype) -5.0000000000000000e+00;
work->Prob.X5.l[1] = (realtype) -5.0000000000000000e+00;
work->Prob.X5.l[2] = (realtype) -5.0000000000000000e+00;
work->Prob.X5.l[3] = (realtype) -5.0000000000000000e+00;
work->Prob.X5.u[0] = (realtype) 5.0000000000000000e+00;
work->Prob.X5.u[1] = (realtype) 5.0000000000000000e+00;
work->Prob.X5.u[2] = (realtype) 5.0000000000000000e+00;
work->Prob.X5.u[3] = (realtype) 5.0000000000000000e+00;
work->Prob.X6.l[0] = (realtype) -5.0000000000000000e+00;
work->Prob.X6.l[1] = (realtype) -5.0000000000000000e+00;
work->Prob.X6.l[2] = (realtype) -5.0000000000000000e+00;
work->Prob.X6.l[3] = (realtype) -5.0000000000000000e+00;
work->Prob.X6.u[0] = (realtype) 5.0000000000000000e+00;
work->Prob.X6.u[1] = (realtype) 5.0000000000000000e+00;
work->Prob.X6.u[2] = (realtype) 5.0000000000000000e+00;
work->Prob.X6.u[3] = (realtype) 5.0000000000000000e+00;
work->Prob.X7.l[0] = (realtype) -5.0000000000000000e+00;
work->Prob.X7.l[1] = (realtype) -5.0000000000000000e+00;
work->Prob.X7.l[2] = (realtype) -5.0000000000000000e+00;
work->Prob.X7.l[3] = (realtype) -5.0000000000000000e+00;
work->Prob.X7.u[0] = (realtype) 5.0000000000000000e+00;
work->Prob.X7.u[1] = (realtype) 5.0000000000000000e+00;
work->Prob.X7.u[2] = (realtype) 5.0000000000000000e+00;
work->Prob.X7.u[3] = (realtype) 5.0000000000000000e+00;
work->Prob.X8.l[0] = (realtype) -5.0000000000000000e+00;
work->Prob.X8.l[1] = (realtype) -5.0000000000000000e+00;
work->Prob.X8.l[2] = (realtype) -5.0000000000000000e+00;
work->Prob.X8.l[3] = (realtype) -5.0000000000000000e+00;
work->Prob.X8.u[0] = (realtype) 5.0000000000000000e+00;
work->Prob.X8.u[1] = (realtype) 5.0000000000000000e+00;
work->Prob.X8.u[2] = (realtype) 5.0000000000000000e+00;
work->Prob.X8.u[3] = (realtype) 5.0000000000000000e+00;
work->Prob.X9.l[0] = (realtype) -5.0000000000000000e+00;
work->Prob.X9.l[1] = (realtype) -5.0000000000000000e+00;
work->Prob.X9.l[2] = (realtype) -5.0000000000000000e+00;
work->Prob.X9.l[3] = (realtype) -5.0000000000000000e+00;
work->Prob.X9.u[0] = (realtype) 5.0000000000000000e+00;
work->Prob.X9.u[1] = (realtype) 5.0000000000000000e+00;
work->Prob.X9.u[2] = (realtype) 5.0000000000000000e+00;
work->Prob.X9.u[3] = (realtype) 5.0000000000000000e+00;
work->Prob.X10.l[0] = (realtype) -5.0000000000000000e+00;
work->Prob.X10.l[1] = (realtype) -5.0000000000000000e+00;
work->Prob.X10.l[2] = (realtype) -5.0000000000000000e+00;
work->Prob.X10.l[3] = (realtype) -5.0000000000000000e+00;
work->Prob.X10.u[0] = (realtype) 5.0000000000000000e+00;
work->Prob.X10.u[1] = (realtype) 5.0000000000000000e+00;
work->Prob.X10.u[2] = (realtype) 5.0000000000000000e+00;
work->Prob.X10.u[3] = (realtype) 5.0000000000000000e+00;
work->Prob.X11.l[0] = (realtype) -3.0000000000000000e+00;
work->Prob.X11.l[1] = (realtype) -3.0000000000000000e+00;
work->Prob.X11.l[2] = (realtype) -3.0000000000000000e+00;
work->Prob.X11.l[3] = (realtype) -3.0000000000000000e+00;
work->Prob.X11.l[4] = (realtype) -3.0000000000000000e+00;
work->Prob.X11.l[5] = (realtype) -3.0000000000000000e+00;
work->Prob.X11.l[6] = (realtype) -3.0000000000000000e+00;
work->Prob.X11.l[7] = (realtype) -3.0000000000000000e+00;
work->Prob.X11.u[0] = (realtype) 3.0000000000000000e+00;
work->Prob.X11.u[1] = (realtype) 3.0000000000000000e+00;
work->Prob.X11.u[2] = (realtype) 3.0000000000000000e+00;
work->Prob.X11.u[3] = (realtype) 3.0000000000000000e+00;
work->Prob.X11.u[4] = (realtype) 3.0000000000000000e+00;
work->Prob.X11.u[5] = (realtype) 3.0000000000000000e+00;
work->Prob.X11.u[6] = (realtype) 3.0000000000000000e+00;
work->Prob.X11.u[7] = (realtype) 3.0000000000000000e+00;
work->Prob.X12.l[0] = (realtype) -3.0000000000000000e+00;
work->Prob.X12.l[1] = (realtype) -3.0000000000000000e+00;
work->Prob.X12.l[2] = (realtype) -3.0000000000000000e+00;
work->Prob.X12.l[3] = (realtype) -3.0000000000000000e+00;
work->Prob.X12.l[4] = (realtype) -3.0000000000000000e+00;
work->Prob.X12.l[5] = (realtype) -3.0000000000000000e+00;
work->Prob.X12.l[6] = (realtype) -3.0000000000000000e+00;
work->Prob.X12.l[7] = (realtype) -3.0000000000000000e+00;
work->Prob.X12.u[0] = (realtype) 3.0000000000000000e+00;
work->Prob.X12.u[1] = (realtype) 3.0000000000000000e+00;
work->Prob.X12.u[2] = (realtype) 3.0000000000000000e+00;
work->Prob.X12.u[3] = (realtype) 3.0000000000000000e+00;
work->Prob.X12.u[4] = (realtype) 3.0000000000000000e+00;
work->Prob.X12.u[5] = (realtype) 3.0000000000000000e+00;
work->Prob.X12.u[6] = (realtype) 3.0000000000000000e+00;
work->Prob.X12.u[7] = (realtype) 3.0000000000000000e+00;
work->Prob.X13.l[0] = (realtype) -3.0000000000000000e+00;
work->Prob.X13.l[1] = (realtype) -3.0000000000000000e+00;
work->Prob.X13.l[2] = (realtype) -3.0000000000000000e+00;
work->Prob.X13.l[3] = (realtype) -3.0000000000000000e+00;
work->Prob.X13.l[4] = (realtype) -3.0000000000000000e+00;
work->Prob.X13.l[5] = (realtype) -3.0000000000000000e+00;
work->Prob.X13.l[6] = (realtype) -3.0000000000000000e+00;
work->Prob.X13.l[7] = (realtype) -3.0000000000000000e+00;
work->Prob.X13.u[0] = (realtype) 3.0000000000000000e+00;
work->Prob.X13.u[1] = (realtype) 3.0000000000000000e+00;
work->Prob.X13.u[2] = (realtype) 3.0000000000000000e+00;
work->Prob.X13.u[3] = (realtype) 3.0000000000000000e+00;
work->Prob.X13.u[4] = (realtype) 3.0000000000000000e+00;
work->Prob.X13.u[5] = (realtype) 3.0000000000000000e+00;
work->Prob.X13.u[6] = (realtype) 3.0000000000000000e+00;
work->Prob.X13.u[7] = (realtype) 3.0000000000000000e+00;
work->Prob.X14.l[0] = (realtype) -3.0000000000000000e+00;
work->Prob.X14.l[1] = (realtype) -3.0000000000000000e+00;
work->Prob.X14.l[2] = (realtype) -3.0000000000000000e+00;
work->Prob.X14.l[3] = (realtype) -3.0000000000000000e+00;
work->Prob.X14.l[4] = (realtype) -3.0000000000000000e+00;
work->Prob.X14.l[5] = (realtype) -3.0000000000000000e+00;
work->Prob.X14.l[6] = (realtype) -3.0000000000000000e+00;
work->Prob.X14.l[7] = (realtype) -3.0000000000000000e+00;
work->Prob.X14.u[0] = (realtype) 3.0000000000000000e+00;
work->Prob.X14.u[1] = (realtype) 3.0000000000000000e+00;
work->Prob.X14.u[2] = (realtype) 3.0000000000000000e+00;
work->Prob.X14.u[3] = (realtype) 3.0000000000000000e+00;
work->Prob.X14.u[4] = (realtype) 3.0000000000000000e+00;
work->Prob.X14.u[5] = (realtype) 3.0000000000000000e+00;
work->Prob.X14.u[6] = (realtype) 3.0000000000000000e+00;
work->Prob.X14.u[7] = (realtype) 3.0000000000000000e+00;
work->Prob.X15.l[0] = (realtype) -3.0000000000000000e+00;
work->Prob.X15.l[1] = (realtype) -3.0000000000000000e+00;
work->Prob.X15.l[2] = (realtype) -3.0000000000000000e+00;
work->Prob.X15.l[3] = (realtype) -3.0000000000000000e+00;
work->Prob.X15.l[4] = (realtype) -3.0000000000000000e+00;
work->Prob.X15.l[5] = (realtype) -3.0000000000000000e+00;
work->Prob.X15.l[6] = (realtype) -3.0000000000000000e+00;
work->Prob.X15.l[7] = (realtype) -3.0000000000000000e+00;
work->Prob.X15.u[0] = (realtype) 3.0000000000000000e+00;
work->Prob.X15.u[1] = (realtype) 3.0000000000000000e+00;
work->Prob.X15.u[2] = (realtype) 3.0000000000000000e+00;
work->Prob.X15.u[3] = (realtype) 3.0000000000000000e+00;
work->Prob.X15.u[4] = (realtype) 3.0000000000000000e+00;
work->Prob.X15.u[5] = (realtype) 3.0000000000000000e+00;
work->Prob.X15.u[6] = (realtype) 3.0000000000000000e+00;
work->Prob.X15.u[7] = (realtype) 3.0000000000000000e+00;
work->Prob.X16.l[0] = (realtype) -3.0000000000000000e+00;
work->Prob.X16.l[1] = (realtype) -3.0000000000000000e+00;
work->Prob.X16.l[2] = (realtype) -3.0000000000000000e+00;
work->Prob.X16.l[3] = (realtype) -3.0000000000000000e+00;
work->Prob.X16.l[4] = (realtype) -3.0000000000000000e+00;
work->Prob.X16.l[5] = (realtype) -3.0000000000000000e+00;
work->Prob.X16.l[6] = (realtype) -3.0000000000000000e+00;
work->Prob.X16.l[7] = (realtype) -3.0000000000000000e+00;
work->Prob.X16.u[0] = (realtype) 3.0000000000000000e+00;
work->Prob.X16.u[1] = (realtype) 3.0000000000000000e+00;
work->Prob.X16.u[2] = (realtype) 3.0000000000000000e+00;
work->Prob.X16.u[3] = (realtype) 3.0000000000000000e+00;
work->Prob.X16.u[4] = (realtype) 3.0000000000000000e+00;
work->Prob.X16.u[5] = (realtype) 3.0000000000000000e+00;
work->Prob.X16.u[6] = (realtype) 3.0000000000000000e+00;
work->Prob.X16.u[7] = (realtype) 3.0000000000000000e+00;
work->Prob.X17.l[0] = (realtype) -3.0000000000000000e+00;
work->Prob.X17.l[1] = (realtype) -3.0000000000000000e+00;
work->Prob.X17.l[2] = (realtype) -3.0000000000000000e+00;
work->Prob.X17.l[3] = (realtype) -3.0000000000000000e+00;
work->Prob.X17.l[4] = (realtype) -3.0000000000000000e+00;
work->Prob.X17.l[5] = (realtype) -3.0000000000000000e+00;
work->Prob.X17.l[6] = (realtype) -3.0000000000000000e+00;
work->Prob.X17.l[7] = (realtype) -3.0000000000000000e+00;
work->Prob.X17.u[0] = (realtype) 3.0000000000000000e+00;
work->Prob.X17.u[1] = (realtype) 3.0000000000000000e+00;
work->Prob.X17.u[2] = (realtype) 3.0000000000000000e+00;
work->Prob.X17.u[3] = (realtype) 3.0000000000000000e+00;
work->Prob.X17.u[4] = (realtype) 3.0000000000000000e+00;
work->Prob.X17.u[5] = (realtype) 3.0000000000000000e+00;
work->Prob.X17.u[6] = (realtype) 3.0000000000000000e+00;
work->Prob.X17.u[7] = (realtype) 3.0000000000000000e+00;
work->Prob.X18.l[0] = (realtype) -3.0000000000000000e+00;
work->Prob.X18.l[1] = (realtype) -3.0000000000000000e+00;
work->Prob.X18.l[2] = (realtype) -3.0000000000000000e+00;
work->Prob.X18.l[3] = (realtype) -3.0000000000000000e+00;
work->Prob.X18.l[4] = (realtype) -3.0000000000000000e+00;
work->Prob.X18.l[5] = (realtype) -3.0000000000000000e+00;
work->Prob.X18.l[6] = (realtype) -3.0000000000000000e+00;
work->Prob.X18.l[7] = (realtype) -3.0000000000000000e+00;
work->Prob.X18.u[0] = (realtype) 3.0000000000000000e+00;
work->Prob.X18.u[1] = (realtype) 3.0000000000000000e+00;
work->Prob.X18.u[2] = (realtype) 3.0000000000000000e+00;
work->Prob.X18.u[3] = (realtype) 3.0000000000000000e+00;
work->Prob.X18.u[4] = (realtype) 3.0000000000000000e+00;
work->Prob.X18.u[5] = (realtype) 3.0000000000000000e+00;
work->Prob.X18.u[6] = (realtype) 3.0000000000000000e+00;
work->Prob.X18.u[7] = (realtype) 3.0000000000000000e+00;
work->Prob.X19.l[0] = (realtype) -3.0000000000000000e+00;
work->Prob.X19.l[1] = (realtype) -3.0000000000000000e+00;
work->Prob.X19.l[2] = (realtype) -3.0000000000000000e+00;
work->Prob.X19.l[3] = (realtype) -3.0000000000000000e+00;
work->Prob.X19.l[4] = (realtype) -3.0000000000000000e+00;
work->Prob.X19.l[5] = (realtype) -3.0000000000000000e+00;
work->Prob.X19.l[6] = (realtype) -3.0000000000000000e+00;
work->Prob.X19.l[7] = (realtype) -3.0000000000000000e+00;
work->Prob.X19.u[0] = (realtype) 3.0000000000000000e+00;
work->Prob.X19.u[1] = (realtype) 3.0000000000000000e+00;
work->Prob.X19.u[2] = (realtype) 3.0000000000000000e+00;
work->Prob.X19.u[3] = (realtype) 3.0000000000000000e+00;
work->Prob.X19.u[4] = (realtype) 3.0000000000000000e+00;
work->Prob.X19.u[5] = (realtype) 3.0000000000000000e+00;
work->Prob.X19.u[6] = (realtype) 3.0000000000000000e+00;
work->Prob.X19.u[7] = (realtype) 3.0000000000000000e+00;
work->Prob.X20.l[0] = (realtype) -3.0000000000000000e+00;
work->Prob.X20.l[1] = (realtype) -3.0000000000000000e+00;
work->Prob.X20.l[2] = (realtype) -3.0000000000000000e+00;
work->Prob.X20.l[3] = (realtype) -3.0000000000000000e+00;
work->Prob.X20.l[4] = (realtype) -3.0000000000000000e+00;
work->Prob.X20.l[5] = (realtype) -3.0000000000000000e+00;
work->Prob.X20.l[6] = (realtype) -3.0000000000000000e+00;
work->Prob.X20.l[7] = (realtype) -3.0000000000000000e+00;
work->Prob.X20.u[0] = (realtype) 3.0000000000000000e+00;
work->Prob.X20.u[1] = (realtype) 3.0000000000000000e+00;
work->Prob.X20.u[2] = (realtype) 3.0000000000000000e+00;
work->Prob.X20.u[3] = (realtype) 3.0000000000000000e+00;
work->Prob.X20.u[4] = (realtype) 3.0000000000000000e+00;
work->Prob.X20.u[5] = (realtype) 3.0000000000000000e+00;
work->Prob.X20.u[6] = (realtype) 3.0000000000000000e+00;
work->Prob.X20.u[7] = (realtype) 3.0000000000000000e+00;
work->algoInner.glob_Linv = (realtype) 1.0000000000000000e+00;
work->algoInner.glob_mu = (realtype) 1.0000000000000000e+00;
work->algoOuter.glob_Linv = (realtype) 9.2772710138516790e-02;
settings->approach.warmstartInner = 1;
{int i; for (i=0;i<120;++i) {settings->algoInner.init[i] = (realtype) 0.0;}}
settings->algoInner.maxit = 5000;
settings->algoInner.stopgEps = (realtype) 5.0000000000000001e-03;
settings->algoInner.stopgStride = 1;
{int i; for (i=0;i<80;++i) {settings->algoOuter.init[i] = (realtype) 0.0;}}
settings->algoOuter.maxit = 5000;
settings->algoOuter.stopgEps = (realtype) 2.0000000000000000e-03;
settings->algoOuter.stopgStride = 1;
}

