% Compiling:
%     ex1_mex_make
% 
% 
% Usage:
%     mres = ex1_mex(mparams)
%     mres = ex1_mex(mparams,msetgs)
% 
%   Inputs:
%     mparams: struct for parametric problem data, required
%     msetgs: struct for settings, optional
% 
%   Template for mparams (each listed field is required):
%     mparams = struct();
%     mparams.g; %[10x1]
%     mparams.c; %[1x1]
% 
%   Template for msetgs (each listed field is optional):
%     msetgs = struct();
%     msetgs.algo.init; %[10x1]
%     msetgs.algo.maxit = 5000;
%     msetgs.algo.stopgEps = 1.0000000000000000e-03;
%     msetgs.algo.stopgStride = 1;


% 
% This file is generated by FiOrdOs, a program licensed under GPL
% by copyright holder Automatic Control Laboratory, ETH Zurich.
% 
% If you are interested in using this file commercially,
% please contact the copyright holder.
% 

