/**
 * This file is generated by FiOrdOs, a program licensed under GPL
 * by copyright holder Automatic Control Laboratory, ETH Zurich.
 * 
 * If you are interested in using this file commercially,
 * please contact the copyright holder.
 */

#ifndef EX1_SOLVER_H
#define EX1_SOLVER_H

#ifdef USE_REALTYPE_SINGLE
  typedef float realtype;
#else
  typedef double realtype;
#endif

/* <<< struct Params >>> */
#if defined(USE_PARAMSMODE_PTR)  && !(defined(MATLAB_MEX_FILE) || defined(RT))
#  define PARAMS_MACRO(name,len) const realtype *name;
#else /* the default */
#  define PARAMS_MACRO(name,len) realtype name[len];
#endif
typedef struct {
    PARAMS_MACRO(g,10)
    PARAMS_MACRO(c,1)
} ex1_Params;
#undef PARAMS_MACRO

/* <<< struct Settings >>> */
typedef struct {
    struct {
        realtype init[10];
        int maxit;
        realtype stopgEps;
        int stopgStride;
    } algo;
} ex1_Settings;

/* <<< struct Result >>> */
typedef struct {
    realtype x[10];
    realtype f;
    int iter;
    int exitflag;
} ex1_Result;

/* <<< struct Work >>> */
typedef struct {
    struct {
        realtype H[100];
        struct {
            realtype l[1];
            realtype u[1];
        } X1;
        struct {
            realtype l[1];
            realtype u[1];
        } X2;
        struct {
            realtype l[1];
            realtype u[1];
        } X3;
        struct {
            realtype l[1];
            realtype u[1];
        } X4;
        struct {
            realtype l[1];
            realtype u[1];
        } X5;
        struct {
            realtype l[1];
            realtype u[1];
        } X6;
        struct {
            realtype l[1];
            realtype u[1];
        } X7;
        struct {
            realtype l[1];
            realtype u[1];
        } X8;
        struct {
            realtype l[1];
            realtype u[1];
        } X9;
        struct {
            realtype l[1];
            realtype u[1];
        } X10;
    } Prob;
    struct {
        realtype init[10];
        realtype glob_Linv;
        realtype glob_mu;
        realtype res_z[10];
        int res_stopcode;
        int res_iter;
    } algo;
} ex1_Work;

/* <<< solver INTERFACE >>> */
void ex1_init(ex1_Params *params, ex1_Settings *settings, ex1_Result *result, ex1_Work *work);
void ex1_solve(ex1_Params *params, ex1_Settings *settings, ex1_Result *result, ex1_Work *work);
#endif
