/**
 * This file is generated by FiOrdOs, a program licensed under GPL
 * by copyright holder Automatic Control Laboratory, ETH Zurich.
 * 
 * If you are interested in using this file commercially,
 * please contact the copyright holder.
 */

#include <string.h>
#include "ex1_solver.h"
#include "mex.h"

/* input and output arguments */
#define MPARAMS prhs[0]
#define MSETGS prhs[1]
#define MRES plhs[0]

/* copying */
void copyCArrayToM(realtype *src, double *dest, int dim) {
    while (dim--) {
        *dest++ = (double)*src++;
    }
}
void copyMArrayToC(double *src, realtype *dest, int dim) {
    while (dim--) {
        *dest++ = (realtype)*src++;
    }
}


/* THE mex-function */
void mexFunction( int nlhs, mxArray *plhs[],
                  int nrhs, const mxArray *prhs[] )  {

    /* define variables for structs */
    ex1_Work work ={0};
    ex1_Params params ={0};
    ex1_Settings settings = {0};
    ex1_Result result = {0};

    /* initialize structs */
    ex1_init(&params, &settings, &result, &work);

    /* Check for proper number of arguments */
    if (nrhs != 1 && nrhs!=2) {
        mexErrMsgTxt("One or two input arguments required.");
    }
    if (nlhs > 1) {
        mexErrMsgTxt("Too many output arguments.");
    }

    /* set params according to mparams from prhs */
    {
    
    mxArray *tmp1;
    int i;
    const char *fname;
    
    if (!mxIsStruct(MPARAMS)) {
        mexErrMsgTxt("MPARAMS must be a structure.");
    }
    for (i=0; i<mxGetNumberOfFields(MPARAMS); ++i) {
        fname= mxGetFieldNameByNumber(MPARAMS, i);
        if (0==strcmp(fname,"g"));
        else
        if (0==strcmp(fname,"c"));
        else
            mexPrintf("Warning: MPARAMS contains the superfluous field '%s'.\n",fname);
    }
    
        tmp1=mxGetField(MPARAMS,0,"g");
        if (NULL==tmp1){
            mexErrMsgTxt("MPARAMS.g is missing.");
        }
        if (!mxIsDouble(tmp1)) {
            mexErrMsgTxt("MPARAMS.g must be a double.");
        }
        if ( mxGetM(tmp1) != 10 || mxGetN(tmp1) != 1 ) {
            mexErrMsgTxt("MPARAMS.g must be matrix of dimension 10x1.");
        }
        copyMArrayToC(mxGetPr(tmp1),params.g,10 );
        
        tmp1=mxGetField(MPARAMS,0,"c");
        if (NULL==tmp1){
            mexErrMsgTxt("MPARAMS.c is missing.");
        }
        if (!mxIsDouble(tmp1)) {
            mexErrMsgTxt("MPARAMS.c must be a double.");
        }
        if ( mxGetM(tmp1) != 1 || mxGetN(tmp1) != 1 ) {
            mexErrMsgTxt("MPARAMS.c must be matrix of dimension 1x1.");
        }
        copyMArrayToC(mxGetPr(tmp1),params.c,1 );
        
    
    }

    /* change settings according to msetgs in prhs (if given)*/
    if (nrhs==2) {
    {
    
    mxArray *tmp1;
    int i1;
    const char *fname1;
    mxArray *tmp2;
    int i2;
    const char *fname2;
    
    if (!mxIsStruct(MSETGS)) {
        mexErrMsgTxt("MSETGS must be a structure.");
    }
    for (i1=0; i1<mxGetNumberOfFields(MSETGS); ++i1) {
        fname1 = mxGetFieldNameByNumber(MSETGS, i1);
        tmp1 = mxGetField(MSETGS,0,fname1);
        if ( 0 == strcmp(fname1,"algo")) {
            if (!mxIsStruct(tmp1)) {
                mexErrMsgTxt("MSETGS.algo must be a structure.");
            }
            for (i2=0; i2<mxGetNumberOfFields(tmp1); ++i2) {
                fname2 = mxGetFieldNameByNumber(tmp1, i2);
                tmp2 = mxGetField(tmp1,0,fname2);
                if ( 0 == strcmp(fname2,"init")) {
                    if (!mxIsDouble(tmp2)) {
                        mexErrMsgTxt("MSETGS.algo.init must be a double.");
                    }
                    if ( mxGetM(tmp2) != 10 || mxGetN(tmp2) != 1 ) {
                        mexErrMsgTxt("MSETGS.algo.init must be matrix of dimension 10x1.");
                    }
                    copyMArrayToC(mxGetPr(tmp2),settings.algo.init,10);
                }
                else
                if ( 0 == strcmp(fname2,"maxit")) {
                    if (!mxIsDouble(tmp2)) {
                        mexErrMsgTxt("MSETGS.algo.maxit must be a double.");
                    }
                    if ( mxGetM(tmp2) != 1 || mxGetN(tmp2) != 1 ) {
                        mexErrMsgTxt("MSETGS.algo.maxit must be matrix of dimension 1x1.");
                    }
                    settings.algo.maxit = (int) *mxGetPr(tmp2);
                }
                else
                if ( 0 == strcmp(fname2,"stopgEps")) {
                    if (!mxIsDouble(tmp2)) {
                        mexErrMsgTxt("MSETGS.algo.stopgEps must be a double.");
                    }
                    if ( mxGetM(tmp2) != 1 || mxGetN(tmp2) != 1 ) {
                        mexErrMsgTxt("MSETGS.algo.stopgEps must be matrix of dimension 1x1.");
                    }
                    settings.algo.stopgEps = (realtype) *mxGetPr(tmp2);
                }
                else
                if ( 0 == strcmp(fname2,"stopgStride")) {
                    if (!mxIsDouble(tmp2)) {
                        mexErrMsgTxt("MSETGS.algo.stopgStride must be a double.");
                    }
                    if ( mxGetM(tmp2) != 1 || mxGetN(tmp2) != 1 ) {
                        mexErrMsgTxt("MSETGS.algo.stopgStride must be matrix of dimension 1x1.");
                    }
                    settings.algo.stopgStride = (int) *mxGetPr(tmp2);
                }
                else
                {
                    mexPrintf("Warning: MSETGS.algo contains the superfluous field '%s'.\n",fname2);
                }
            }
        }
        else
        {
            mexPrintf("Warning: MSETGS contains the superfluous field '%s'.\n",fname1);
        }
    }
    
    }
    }

    /* call the solver */
    ex1_solve(&params, &settings, &result, &work);

    /*write result to mresult in plhs */
    {
    
    mxArray *tmp1;
    
    {
    const char *fnames[] = {"x", "f", "iter", "exitflag"};
    MRES = mxCreateStructMatrix(1,1, 4, fnames);
        tmp1 = mxCreateDoubleMatrix(10,1,mxREAL);
        copyCArrayToM( result.x, mxGetPr(tmp1), 10 );
        mxSetField(MRES, 0, "x", tmp1);
    
        tmp1 = mxCreateDoubleMatrix(1,1,mxREAL);
        *mxGetPr(tmp1) = (double) result.f;
        mxSetField(MRES, 0, "f", tmp1);
    
        tmp1 = mxCreateDoubleMatrix(1,1,mxREAL);
        *mxGetPr(tmp1) = (double) result.iter;
        mxSetField(MRES, 0, "iter", tmp1);
    
        tmp1 = mxCreateDoubleMatrix(1,1,mxREAL);
        *mxGetPr(tmp1) = (double) result.exitflag;
        mxSetField(MRES, 0, "exitflag", tmp1);
    
    }
    
    }

}
