/**
 * This file is generated by FiOrdOs, a program licensed under GPL
 * by copyright holder Automatic Control Laboratory, ETH Zurich.
 * 
 * If you are interested in using this file commercially,
 * please contact the copyright holder.
 */

#ifndef EX12_SOLVER_H
#define EX12_SOLVER_H

#ifdef USE_REALTYPE_SINGLE
  typedef float realtype;
#else
  typedef double realtype;
#endif

/* <<< struct Params >>> */
#if defined(USE_PARAMSMODE_PTR)  && !(defined(MATLAB_MEX_FILE) || defined(RT))
#  define PARAMS_MACRO(name,len) const realtype *name;
#else /* the default */
#  define PARAMS_MACRO(name,len) realtype name[len];
#endif
typedef struct {
    PARAMS_MACRO(g,300)
    PARAMS_MACRO(c,1)
    PARAMS_MACRO(be,200)
} ex12_Params;
#undef PARAMS_MACRO

/* <<< struct Settings >>> */
typedef struct {
    struct {
        int warmstartInner;
    } approach;
    struct {
        realtype init[300];
        int maxit;
        realtype stopgEps;
        int stopgStride;
    } algoInner;
    struct {
        realtype init[200];
        int maxit;
        realtype stopgEps;
        int stopgStride;
    } algoOuter;
} ex12_Settings;

/* <<< struct Result >>> */
typedef struct {
    realtype la[200];
    realtype x[300];
    realtype d;
    int iter;
    int exitflag;
} ex12_Result;

/* <<< struct Work >>> */
typedef struct {
    struct {
        realtype H[300];
        realtype Ae[60000];
        realtype inner_g[300];
        realtype inner_c[1];
        struct {
            realtype l[10];
            realtype u[10];
        } X1;
        struct {
            realtype l[10];
            realtype u[10];
        } X2;
        struct {
            realtype l[10];
            realtype u[10];
        } X3;
        struct {
            realtype l[10];
            realtype u[10];
        } X4;
        struct {
            realtype l[10];
            realtype u[10];
        } X5;
        struct {
            realtype l[10];
            realtype u[10];
        } X6;
        struct {
            realtype l[10];
            realtype u[10];
        } X7;
        struct {
            realtype l[10];
            realtype u[10];
        } X8;
        struct {
            realtype l[10];
            realtype u[10];
        } X9;
        struct {
            realtype l[10];
            realtype u[10];
        } X10;
        struct {
            realtype l[20];
            realtype u[20];
        } X11;
        struct {
            realtype l[20];
            realtype u[20];
        } X12;
        struct {
            realtype l[20];
            realtype u[20];
        } X13;
        struct {
            realtype l[20];
            realtype u[20];
        } X14;
        struct {
            realtype l[20];
            realtype u[20];
        } X15;
        struct {
            realtype l[20];
            realtype u[20];
        } X16;
        struct {
            realtype l[20];
            realtype u[20];
        } X17;
        struct {
            realtype l[20];
            realtype u[20];
        } X18;
        struct {
            realtype l[20];
            realtype u[20];
        } X19;
        struct {
            realtype l[20];
            realtype u[20];
        } X20;
    } Prob;
    struct {
        realtype init[300];
        realtype glob_Linv;
        realtype glob_mu;
        realtype res_z[300];
        int res_stopcode;
        int res_iter;
    } algoInner;
    struct {
        realtype init[200];
        realtype glob_Linv;
        realtype res_z[200];
        int res_stopcode;
        int res_iter;
    } algoOuter;
} ex12_Work;

/* <<< solver INTERFACE >>> */
void ex12_init(ex12_Params *params, ex12_Settings *settings, ex12_Result *result, ex12_Work *work);
void ex12_solve(ex12_Params *params, ex12_Settings *settings, ex12_Result *result, ex12_Work *work);
#endif
