function B = compute_B(in1,in2,s,in4,in5,alphmdt)
%compute_B
%    B = compute_B(IN1,IN2,S,IN4,IN5,ALPHMDT)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    19-Jan-2023 15:15:22

J_B1 = in4(1,:);
J_B2 = in4(2,:);
J_B3 = in4(3,:);
T_B1 = in2(1,:);
T_B2 = in2(2,:);
T_B3 = in2(3,:);
m = in1(1,:);
q1 = in1(8,:);
q2 = in1(9,:);
q3 = in1(10,:);
q4 = in1(11,:);
r_TB1 = in5(1,:);
r_TB2 = in5(2,:);
r_TB3 = in5(3,:);
t2 = q1.*q2;
t3 = q1.*q3;
t4 = q1.*q4;
t5 = q2.*q3;
t6 = q2.*q4;
t7 = q3.*q4;
t8 = T_B1.^2;
t9 = T_B2.^2;
t10 = T_B3.^2;
t11 = q1.^2;
t12 = q2.^2;
t13 = q3.^2;
t14 = q4.^2;
t15 = 1.0./J_B1;
t16 = 1.0./J_B2;
t17 = 1.0./J_B3;
t18 = 1.0./m;
t19 = -t12;
t20 = -t13;
t21 = -t14;
t22 = t8+t9+t10;
t23 = 1.0./sqrt(t22);
B = reshape([-T_B1.*alphmdt.*s.*t23,0.0,0.0,0.0,s.*t18.*(t11+t14+t19+t20),s.*t18.*(t2+t7).*2.0,s.*t18.*(t3-t6).*2.0,0.0,0.0,0.0,0.0,0.0,r_TB3.*s.*t16,-r_TB2.*s.*t17,-T_B2.*alphmdt.*s.*t23,0.0,0.0,0.0,s.*t18.*(t2-t7).*2.0,-s.*t18.*(t11+t13+t19+t21),s.*t18.*(t4+t5).*2.0,0.0,0.0,0.0,0.0,-r_TB3.*s.*t15,0.0,r_TB1.*s.*t17,-T_B3.*alphmdt.*s.*t23,0.0,0.0,0.0,s.*t18.*(t3+t6).*2.0,s.*t18.*(t4-t5).*-2.0,-s.*t18.*(t11+t12+t20+t21),0.0,0.0,0.0,0.0,r_TB2.*s.*t15,-r_TB1.*s.*t16,0.0],[14,3]);
