/**
 * This file is generated by FiOrdOs, a program licensed under GPL
 * by copyright holder Automatic Control Laboratory, ETH Zurich.
 * 
 * If you are interested in using this file commercially,
 * please contact the copyright holder.
 */

#include "ex10_solver.h"
#include <stdio.h>
#include <math.h>
#include <string.h>

#ifdef MATLAB_MEX_FILE
#include "mex.h"
#endif

/* <<< print >>> */
static void printArray(realtype *arr, int dim) {
  int i;
  printf("[\n"); ;
  for (i=0; i<dim; i++) {
    printf("%8.16e\n",*arr++);
  }
  printf("]\n\n");
}

static void printArrayNamed(realtype *arr, int dim, char *txt) {
  printf("%s = ",txt);
  printArray(arr,dim);
}

/* <<< copy vectors >>> */
static void copyvec120(realtype *dest, const realtype *src) {
    {
        int i;
        for (i=0; i<120; ++i) {
            dest[i] = src[i];
        }
    }
}
static void copyvec40(realtype *dest, const realtype *src) {
    {
        int i;
        for (i=0; i<40; ++i) {
            dest[i] = src[i];
        }
    }
}

/* <<< projection >>> */
static void algoInner_project(realtype *thevec, ex10_Work *work, ex10_Params *params) {
    realtype *theveci;

    /* ====== EssBox X1 ====== */
    theveci = thevec;
    /* ------ projection ------ */
    {
        int icoord;
        for (icoord=0; icoord<8; ++icoord) {
          if (theveci[icoord] < work->Prob.X1.l[icoord]) {
            theveci[icoord] = work->Prob.X1.l[icoord];
          }
          else if (theveci[icoord] > work->Prob.X1.u[icoord]) {
            theveci[icoord] = work->Prob.X1.u[icoord];
          }
        }
    }
    /* ====== EssBox X2 ====== */
    theveci = thevec+8;
    /* ------ projection ------ */
    {
        int icoord;
        for (icoord=0; icoord<8; ++icoord) {
          if (theveci[icoord] < work->Prob.X2.l[icoord]) {
            theveci[icoord] = work->Prob.X2.l[icoord];
          }
          else if (theveci[icoord] > work->Prob.X2.u[icoord]) {
            theveci[icoord] = work->Prob.X2.u[icoord];
          }
        }
    }
    /* ====== EssBox X3 ====== */
    theveci = thevec+16;
    /* ------ projection ------ */
    {
        int icoord;
        for (icoord=0; icoord<8; ++icoord) {
          if (theveci[icoord] < work->Prob.X3.l[icoord]) {
            theveci[icoord] = work->Prob.X3.l[icoord];
          }
          else if (theveci[icoord] > work->Prob.X3.u[icoord]) {
            theveci[icoord] = work->Prob.X3.u[icoord];
          }
        }
    }
    /* ====== EssBox X4 ====== */
    theveci = thevec+24;
    /* ------ projection ------ */
    {
        int icoord;
        for (icoord=0; icoord<8; ++icoord) {
          if (theveci[icoord] < work->Prob.X4.l[icoord]) {
            theveci[icoord] = work->Prob.X4.l[icoord];
          }
          else if (theveci[icoord] > work->Prob.X4.u[icoord]) {
            theveci[icoord] = work->Prob.X4.u[icoord];
          }
        }
    }
    /* ====== EssBox X5 ====== */
    theveci = thevec+32;
    /* ------ projection ------ */
    {
        int icoord;
        for (icoord=0; icoord<8; ++icoord) {
          if (theveci[icoord] < work->Prob.X5.l[icoord]) {
            theveci[icoord] = work->Prob.X5.l[icoord];
          }
          else if (theveci[icoord] > work->Prob.X5.u[icoord]) {
            theveci[icoord] = work->Prob.X5.u[icoord];
          }
        }
    }
    /* ====== EssBox X6 ====== */
    theveci = thevec+40;
    /* ------ projection ------ */
    {
        int icoord;
        for (icoord=0; icoord<8; ++icoord) {
          if (theveci[icoord] < work->Prob.X6.l[icoord]) {
            theveci[icoord] = work->Prob.X6.l[icoord];
          }
          else if (theveci[icoord] > work->Prob.X6.u[icoord]) {
            theveci[icoord] = work->Prob.X6.u[icoord];
          }
        }
    }
    /* ====== EssBox X7 ====== */
    theveci = thevec+48;
    /* ------ projection ------ */
    {
        int icoord;
        for (icoord=0; icoord<8; ++icoord) {
          if (theveci[icoord] < work->Prob.X7.l[icoord]) {
            theveci[icoord] = work->Prob.X7.l[icoord];
          }
          else if (theveci[icoord] > work->Prob.X7.u[icoord]) {
            theveci[icoord] = work->Prob.X7.u[icoord];
          }
        }
    }
    /* ====== EssBox X8 ====== */
    theveci = thevec+56;
    /* ------ projection ------ */
    {
        int icoord;
        for (icoord=0; icoord<8; ++icoord) {
          if (theveci[icoord] < work->Prob.X8.l[icoord]) {
            theveci[icoord] = work->Prob.X8.l[icoord];
          }
          else if (theveci[icoord] > work->Prob.X8.u[icoord]) {
            theveci[icoord] = work->Prob.X8.u[icoord];
          }
        }
    }
    /* ====== EssBox X9 ====== */
    theveci = thevec+64;
    /* ------ projection ------ */
    {
        int icoord;
        for (icoord=0; icoord<8; ++icoord) {
          if (theveci[icoord] < work->Prob.X9.l[icoord]) {
            theveci[icoord] = work->Prob.X9.l[icoord];
          }
          else if (theveci[icoord] > work->Prob.X9.u[icoord]) {
            theveci[icoord] = work->Prob.X9.u[icoord];
          }
        }
    }
    /* ====== EssBox X10 ====== */
    theveci = thevec+72;
    /* ------ projection ------ */
    {
        int icoord;
        for (icoord=0; icoord<8; ++icoord) {
          if (theveci[icoord] < work->Prob.X10.l[icoord]) {
            theveci[icoord] = work->Prob.X10.l[icoord];
          }
          else if (theveci[icoord] > work->Prob.X10.u[icoord]) {
            theveci[icoord] = work->Prob.X10.u[icoord];
          }
        }
    }
}

/* <<< oracle >>> */
static void algoInner_oracle(ex10_Work *work, ex10_Params *params, realtype *z, realtype *fval, realtype *grad) {
    realtype hz[120];
    {
        /* (hz):= (work->Prob.H)^T*(z);   // (120x120)*(120x1) */
        {
            int k;
            for (k=0; k<120; ++k) {
              hz[k] = (+work->Prob.H[k]) * z[k];
            }
        }
    }

    if (NULL!=fval) {
        int i;
        realtype tmp;
        tmp = 0.0;
        for (i=0; i<120; ++i) {
          tmp += (0.5*hz[i] + work->Prob.inner_g[i]) * z[i];
        }
        fval[0] = tmp + work->Prob.inner_c[0];
    }

    if (NULL!=grad) {
        int i;
        for (i=0; i<120; ++i) {
          grad[i] = hz[i] + work->Prob.inner_g[i];
        }
    }
}
static void algoOuter_oracle(ex10_Work *work, ex10_Params *params, realtype *v, realtype *fval, realtype *grad, ex10_Settings *settings) {
    /* << data of inner problem >> */
    {
        /* (work->Prob.inner_g):= (work->Prob.Ae)^T*(v)+(params->g);   // (120x40)*(40x1),(120x1) */
        int i,k;
        realtype tmp;
        for (i=0; i<120; ++i) {
            tmp = 0.0;
            for (k=0; k<40; ++k) {
              tmp += work->Prob.Ae[k+i*40]*v[k];
            }
            work->Prob.inner_g[i] = tmp + params->g[i];
        }
    }
    {
        /* (work->Prob.inner_c):= -(v)^T*(params->be)+(params->c);   // (1x40)*(40x1),(1x1) */
        int k;
        realtype tmp;
            tmp = 0.0;
            for (k=0; k<40; ++k) {
              tmp -= v[k]*params->be[k];
            }
            work->Prob.inner_c[0] = tmp + params->c[0];
    }

    /* << inner algorithm >> */
    /* AlgoFgm */
    {
        int stopgNext;
        stopgNext = 1;
        work->algoInner.res_stopcode = 0;
        {
            realtype z[120];
            realtype zp[120];
            realtype y[120];
            realtype grad[120];
            int iter;
            int icoord;
            realtype alpha,alpha_p;
            realtype aamul,muLinv;
            realtype beta;
            
            iter =0;
            
            copyvec120(z,work->algoInner.init);  /* (z):=(work->algoInner.init) */
            copyvec120(y,z);  /* (y):=(z) */
            alpha = 1;
            muLinv = work->algoInner.glob_mu*work->algoInner.glob_Linv;
            copyvec120(zp,z);  /* (zp):=(z) */
            
            while (iter<settings->algoInner.maxit) {
                ++iter;
            
                algoInner_oracle(work,params,y,NULL,grad);
                for (icoord=0; icoord<120; ++icoord) {
                    zp[icoord] = y[icoord] - work->algoInner.glob_Linv*grad[icoord];
                }
                algoInner_project(zp,work,params);
            
                if (iter==stopgNext) {
                    int icoord;
                    realtype gradmapi;
                    realtype normsq;
                    normsq = 0;
                    for (icoord=0; icoord<120; ++icoord) {
                        gradmapi=(y[icoord]-zp[icoord]);
                        normsq += gradmapi * gradmapi;
                    }
                    normsq *= 1.0/(work->algoInner.glob_Linv*work->algoInner.glob_Linv);
                    if ( settings->algoInner.stopgEps>=0 && normsq <= settings->algoInner.stopgEps * settings->algoInner.stopgEps ) {
                        work->algoInner.res_stopcode = 2;
                        break;
                    }
                    stopgNext += settings->algoInner.stopgStride;
                }
            
                aamul = alpha*alpha - muLinv;
                alpha_p= -0.5 * aamul + sqrt( aamul*aamul * 0.25 + alpha*alpha);
                beta = alpha*(1-alpha)/(alpha*alpha+alpha_p);
            
                for (icoord=0; icoord<120; ++icoord) {
                    y[icoord] = zp[icoord] + beta*(zp[icoord]-z[icoord]);
                }
            
                copyvec120(z,zp);  /* (z):=(zp) */
                alpha = alpha_p;
            }
            copyvec120(work->algoInner.res_z,zp);  /* (work->algoInner.res_z):=(zp) */
            work->algoInner.res_iter = iter;
        }
    }

    /* << outer gradient >> */
    if (NULL!=grad) {
        {
            /* (grad):= (work->Prob.Ae)*(work->algoInner.res_z)-(params->be);   // (40x120)*(120x1),(40x1) */
            int i,k;
            realtype tmp;
            for (i=0; i<40; ++i) {
                tmp = 0.0;
                for (k=0; k<120; ++k) {
                  tmp += work->Prob.Ae[i+k*40]*work->algoInner.res_z[k];
                }
                grad[i] = tmp - params->be[i];
            }
        }
    }

    /* << dual function value >> */
    if (NULL!=fval) {
        algoInner_oracle(work,params,work->algoInner.res_z,fval,NULL);
    }

}

/* <<< SOLVE >>> */
void ex10_solve(ex10_Params *params, ex10_Settings *settings, ex10_Result *result, ex10_Work *work) {

    /* << prepare data >> */
    {
        /* === initial points === */
        copyvec120(work->algoInner.init,settings->algoInner.init);  /* (work->algoInner.init):=(settings->algoInner.init) */
        algoInner_project(work->algoInner.init,work,params);
        copyvec40(work->algoOuter.init,settings->algoOuter.init);  /* (work->algoOuter.init):=(settings->algoOuter.init) */
        
    }

    /* << main algorithm >> */
    /* AlgoFgm */
    {
        int stopgNext;
        stopgNext = 1;
        work->algoOuter.res_stopcode = 0;
        {
            realtype z[40];
            realtype zp[40];
            realtype y[40];
            realtype grad[40];
            int iter;
            int icoord;
            realtype alpha,alpha_p;
            realtype beta;
            
            iter =0;
            
            copyvec40(z,work->algoOuter.init);  /* (z):=(work->algoOuter.init) */
            copyvec40(y,z);  /* (y):=(z) */
            alpha = 1;
            copyvec40(zp,z);  /* (zp):=(z) */
            
            while (iter<settings->algoOuter.maxit) {
                ++iter;
            
                algoOuter_oracle(work,params,y,NULL,grad,settings);
                if ( 1==settings->approach.warmstartInner) {  /* reinit inner */
                    copyvec120(work->algoInner.init,work->algoInner.res_z);  /* (work->algoInner.init):=(work->algoInner.res_z) */
                }
                for (icoord=0; icoord<40; ++icoord) {
                    zp[icoord] = y[icoord] + work->algoOuter.glob_Linv*grad[icoord];
                }
            
                if (iter==stopgNext) {
                    int icoord;
                    realtype gradmapi;
                    realtype normsq;
                    normsq = 0;
                    for (icoord=0; icoord<40; ++icoord) {
                        gradmapi=(y[icoord]-zp[icoord]);
                        normsq += gradmapi * gradmapi;
                    }
                    normsq *= 1.0/(work->algoOuter.glob_Linv*work->algoOuter.glob_Linv);
                    if ( settings->algoOuter.stopgEps>=0 && normsq <= settings->algoOuter.stopgEps * settings->algoOuter.stopgEps ) {
                        work->algoOuter.res_stopcode = 2;
                        break;
                    }
                    stopgNext += settings->algoOuter.stopgStride;
                }
            
                alpha_p= 0.5*alpha*(sqrt(alpha*alpha+4)-alpha);
                beta = alpha*(1-alpha)/(alpha*alpha+alpha_p);
            
                for (icoord=0; icoord<40; ++icoord) {
                    y[icoord] = zp[icoord] + beta*(zp[icoord]-z[icoord]);
                }
            
                copyvec40(z,zp);  /* (z):=(zp) */
                alpha = alpha_p;
            }
            copyvec40(work->algoOuter.res_z,zp);  /* (work->algoOuter.res_z):=(zp) */
            work->algoOuter.res_iter = iter;
        }
    }
    
    
    /* << finalize result >> */
    copyvec40(result->la,work->algoOuter.res_z);  /* (result->la):=(work->algoOuter.res_z) */
    algoOuter_oracle(work,params,work->algoOuter.res_z,&(result->d),NULL,settings);
    copyvec120(result->x,work->algoInner.res_z);  /* (result->x):=(work->algoInner.res_z) */
    result->iter = work->algoOuter.res_iter;
    result->exitflag = work->algoOuter.res_stopcode;

}



/* <<< INIT >>> */
void ex10_init(ex10_Params *params, ex10_Settings *settings, ex10_Result *result, ex10_Work *work) {
work->Prob.H[0] = (realtype) 1.0000000000000000e+00;
work->Prob.H[1] = (realtype) 1.0000000000000000e+00;
work->Prob.H[2] = (realtype) 1.0000000000000000e+00;
work->Prob.H[3] = (realtype) 1.0000000000000000e+00;
work->Prob.H[4] = (realtype) 1.0000000000000000e+00;
work->Prob.H[5] = (realtype) 1.0000000000000000e+00;
work->Prob.H[6] = (realtype) 1.0000000000000000e+00;
work->Prob.H[7] = (realtype) 1.0000000000000000e+00;
work->Prob.H[8] = (realtype) 1.0000000000000000e+00;
work->Prob.H[9] = (realtype) 1.0000000000000000e+00;
work->Prob.H[10] = (realtype) 1.0000000000000000e+00;
work->Prob.H[11] = (realtype) 1.0000000000000000e+00;
work->Prob.H[12] = (realtype) 1.0000000000000000e+00;
work->Prob.H[13] = (realtype) 1.0000000000000000e+00;
work->Prob.H[14] = (realtype) 1.0000000000000000e+00;
work->Prob.H[15] = (realtype) 1.0000000000000000e+00;
work->Prob.H[16] = (realtype) 1.0000000000000000e+00;
work->Prob.H[17] = (realtype) 1.0000000000000000e+00;
work->Prob.H[18] = (realtype) 1.0000000000000000e+00;
work->Prob.H[19] = (realtype) 1.0000000000000000e+00;
work->Prob.H[20] = (realtype) 1.0000000000000000e+00;
work->Prob.H[21] = (realtype) 1.0000000000000000e+00;
work->Prob.H[22] = (realtype) 1.0000000000000000e+00;
work->Prob.H[23] = (realtype) 1.0000000000000000e+00;
work->Prob.H[24] = (realtype) 1.0000000000000000e+00;
work->Prob.H[25] = (realtype) 1.0000000000000000e+00;
work->Prob.H[26] = (realtype) 1.0000000000000000e+00;
work->Prob.H[27] = (realtype) 1.0000000000000000e+00;
work->Prob.H[28] = (realtype) 1.0000000000000000e+00;
work->Prob.H[29] = (realtype) 1.0000000000000000e+00;
work->Prob.H[30] = (realtype) 1.0000000000000000e+00;
work->Prob.H[31] = (realtype) 1.0000000000000000e+00;
work->Prob.H[32] = (realtype) 1.0000000000000000e+00;
work->Prob.H[33] = (realtype) 1.0000000000000000e+00;
work->Prob.H[34] = (realtype) 1.0000000000000000e+00;
work->Prob.H[35] = (realtype) 1.0000000000000000e+00;
work->Prob.H[36] = (realtype) 1.0000000000000000e+00;
work->Prob.H[37] = (realtype) 1.0000000000000000e+00;
work->Prob.H[38] = (realtype) 1.0000000000000000e+00;
work->Prob.H[39] = (realtype) 1.0000000000000000e+00;
work->Prob.H[40] = (realtype) 1.0000000000000000e+00;
work->Prob.H[41] = (realtype) 1.0000000000000000e+00;
work->Prob.H[42] = (realtype) 1.0000000000000000e+00;
work->Prob.H[43] = (realtype) 1.0000000000000000e+00;
work->Prob.H[44] = (realtype) 1.0000000000000000e+00;
work->Prob.H[45] = (realtype) 1.0000000000000000e+00;
work->Prob.H[46] = (realtype) 1.0000000000000000e+00;
work->Prob.H[47] = (realtype) 1.0000000000000000e+00;
work->Prob.H[48] = (realtype) 1.0000000000000000e+00;
work->Prob.H[49] = (realtype) 1.0000000000000000e+00;
work->Prob.H[50] = (realtype) 1.0000000000000000e+00;
work->Prob.H[51] = (realtype) 1.0000000000000000e+00;
work->Prob.H[52] = (realtype) 1.0000000000000000e+00;
work->Prob.H[53] = (realtype) 1.0000000000000000e+00;
work->Prob.H[54] = (realtype) 1.0000000000000000e+00;
work->Prob.H[55] = (realtype) 1.0000000000000000e+00;
work->Prob.H[56] = (realtype) 1.0000000000000000e+00;
work->Prob.H[57] = (realtype) 1.0000000000000000e+00;
work->Prob.H[58] = (realtype) 1.0000000000000000e+00;
work->Prob.H[59] = (realtype) 1.0000000000000000e+00;
work->Prob.H[60] = (realtype) 1.0000000000000000e+00;
work->Prob.H[61] = (realtype) 1.0000000000000000e+00;
work->Prob.H[62] = (realtype) 1.0000000000000000e+00;
work->Prob.H[63] = (realtype) 1.0000000000000000e+00;
work->Prob.H[64] = (realtype) 1.0000000000000000e+00;
work->Prob.H[65] = (realtype) 1.0000000000000000e+00;
work->Prob.H[66] = (realtype) 1.0000000000000000e+00;
work->Prob.H[67] = (realtype) 1.0000000000000000e+00;
work->Prob.H[68] = (realtype) 1.0000000000000000e+00;
work->Prob.H[69] = (realtype) 1.0000000000000000e+00;
work->Prob.H[70] = (realtype) 1.0000000000000000e+00;
work->Prob.H[71] = (realtype) 1.0000000000000000e+00;
work->Prob.H[72] = (realtype) 1.0000000000000000e+00;
work->Prob.H[73] = (realtype) 1.0000000000000000e+00;
work->Prob.H[74] = (realtype) 1.0000000000000000e+00;
work->Prob.H[75] = (realtype) 1.0000000000000000e+00;
work->Prob.H[76] = (realtype) 1.0000000000000000e+00;
work->Prob.H[77] = (realtype) 1.0000000000000000e+00;
work->Prob.H[78] = (realtype) 1.0000000000000000e+00;
work->Prob.H[79] = (realtype) 1.0000000000000000e+00;
work->Prob.H[80] = (realtype) 1.0000000000000000e+00;
work->Prob.H[81] = (realtype) 1.0000000000000000e+00;
work->Prob.H[82] = (realtype) 1.0000000000000000e+00;
work->Prob.H[83] = (realtype) 1.0000000000000000e+00;
work->Prob.H[84] = (realtype) 1.0000000000000000e+00;
work->Prob.H[85] = (realtype) 1.0000000000000000e+00;
work->Prob.H[86] = (realtype) 1.0000000000000000e+00;
work->Prob.H[87] = (realtype) 1.0000000000000000e+00;
work->Prob.H[88] = (realtype) 1.0000000000000000e+00;
work->Prob.H[89] = (realtype) 1.0000000000000000e+00;
work->Prob.H[90] = (realtype) 1.0000000000000000e+00;
work->Prob.H[91] = (realtype) 1.0000000000000000e+00;
work->Prob.H[92] = (realtype) 1.0000000000000000e+00;
work->Prob.H[93] = (realtype) 1.0000000000000000e+00;
work->Prob.H[94] = (realtype) 1.0000000000000000e+00;
work->Prob.H[95] = (realtype) 1.0000000000000000e+00;
work->Prob.H[96] = (realtype) 1.0000000000000000e+00;
work->Prob.H[97] = (realtype) 1.0000000000000000e+00;
work->Prob.H[98] = (realtype) 1.0000000000000000e+00;
work->Prob.H[99] = (realtype) 1.0000000000000000e+00;
work->Prob.H[100] = (realtype) 1.0000000000000000e+00;
work->Prob.H[101] = (realtype) 1.0000000000000000e+00;
work->Prob.H[102] = (realtype) 1.0000000000000000e+00;
work->Prob.H[103] = (realtype) 1.0000000000000000e+00;
work->Prob.H[104] = (realtype) 1.0000000000000000e+00;
work->Prob.H[105] = (realtype) 1.0000000000000000e+00;
work->Prob.H[106] = (realtype) 1.0000000000000000e+00;
work->Prob.H[107] = (realtype) 1.0000000000000000e+00;
work->Prob.H[108] = (realtype) 1.0000000000000000e+00;
work->Prob.H[109] = (realtype) 1.0000000000000000e+00;
work->Prob.H[110] = (realtype) 1.0000000000000000e+00;
work->Prob.H[111] = (realtype) 1.0000000000000000e+00;
work->Prob.H[112] = (realtype) 1.0000000000000000e+00;
work->Prob.H[113] = (realtype) 1.0000000000000000e+00;
work->Prob.H[114] = (realtype) 1.0000000000000000e+00;
work->Prob.H[115] = (realtype) 1.0000000000000000e+00;
work->Prob.H[116] = (realtype) 1.0000000000000000e+00;
work->Prob.H[117] = (realtype) 1.0000000000000000e+00;
work->Prob.H[118] = (realtype) 1.0000000000000000e+00;
work->Prob.H[119] = (realtype) 1.0000000000000000e+00;
{int i; for (i=0;i<4800;++i) {work->Prob.Ae[i] = (realtype) 0.0;}}
work->Prob.Ae[0] = (realtype) -7.7364281893375786e-01;
work->Prob.Ae[1] = (realtype) -2.8387796751443783e-01;
work->Prob.Ae[2] = (realtype) -2.1964304529332286e+00;
work->Prob.Ae[3] = (realtype) -1.8752673644971860e-01;
work->Prob.Ae[40] = (realtype) -1.0162249319013750e+00;
work->Prob.Ae[41] = (realtype) -1.1118743076821114e+00;
work->Prob.Ae[42] = (realtype) -1.3369464168334997e+00;
work->Prob.Ae[43] = (realtype) -9.5933225134066616e-02;
work->Prob.Ae[80] = (realtype) 1.8362345259632476e-01;
work->Prob.Ae[81] = (realtype) 3.8809349529954229e-01;
work->Prob.Ae[82] = (realtype) -1.2137026243403307e-01;
work->Prob.Ae[83] = (realtype) 8.9907805001539953e-01;
work->Prob.Ae[120] = (realtype) 5.4982276497308902e-01;
work->Prob.Ae[121] = (realtype) -6.0099714127186632e-01;
work->Prob.Ae[122] = (realtype) 1.6900102834521025e+00;
work->Prob.Ae[123] = (realtype) 1.1686191146041705e+00;
work->Prob.Ae[160] = (realtype) -1.4967466996724184e+00;
work->Prob.Ae[161] = (realtype) -1.6560124735546085e+00;
work->Prob.Ae[162] = (realtype) -8.8495879219418472e-01;
work->Prob.Ae[163] = (realtype) 2.1787817396978837e+00;
work->Prob.Ae[200] = (realtype) -2.1174127086103121e+00;
work->Prob.Ae[201] = (realtype) -2.5004160442750079e-01;
work->Prob.Ae[202] = (realtype) -1.2806434955104790e-01;
work->Prob.Ae[203] = (realtype) -2.9341583512465685e-01;
work->Prob.Ae[240] = (realtype) -2.5160876398724069e-01;
work->Prob.Ae[241] = (realtype) -3.5968343828761734e-01;
work->Prob.Ae[242] = (realtype) 1.0956847940072119e+00;
work->Prob.Ae[243] = (realtype) 8.5689400586403264e-01;
work->Prob.Ae[280] = (realtype) 8.0939558401405343e-01;
work->Prob.Ae[281] = (realtype) -5.3385909811798404e-01;
work->Prob.Ae[282] = (realtype) 6.4910346030655353e-01;
work->Prob.Ae[283] = (realtype) 6.5834026750400165e-01;
work->Prob.Ae[324] = (realtype) -7.7364281893375786e-01;
work->Prob.Ae[325] = (realtype) -2.8387796751443783e-01;
work->Prob.Ae[326] = (realtype) -2.1964304529332286e+00;
work->Prob.Ae[327] = (realtype) -1.8752673644971860e-01;
work->Prob.Ae[364] = (realtype) -1.0162249319013750e+00;
work->Prob.Ae[365] = (realtype) -1.1118743076821114e+00;
work->Prob.Ae[366] = (realtype) -1.3369464168334997e+00;
work->Prob.Ae[367] = (realtype) -9.5933225134066616e-02;
work->Prob.Ae[404] = (realtype) 1.8362345259632476e-01;
work->Prob.Ae[405] = (realtype) 3.8809349529954229e-01;
work->Prob.Ae[406] = (realtype) -1.2137026243403307e-01;
work->Prob.Ae[407] = (realtype) 8.9907805001539953e-01;
work->Prob.Ae[444] = (realtype) 5.4982276497308902e-01;
work->Prob.Ae[445] = (realtype) -6.0099714127186632e-01;
work->Prob.Ae[446] = (realtype) 1.6900102834521025e+00;
work->Prob.Ae[447] = (realtype) 1.1686191146041705e+00;
work->Prob.Ae[484] = (realtype) -1.4967466996724184e+00;
work->Prob.Ae[485] = (realtype) -1.6560124735546085e+00;
work->Prob.Ae[486] = (realtype) -8.8495879219418472e-01;
work->Prob.Ae[487] = (realtype) 2.1787817396978837e+00;
work->Prob.Ae[524] = (realtype) -2.1174127086103121e+00;
work->Prob.Ae[525] = (realtype) -2.5004160442750079e-01;
work->Prob.Ae[526] = (realtype) -1.2806434955104790e-01;
work->Prob.Ae[527] = (realtype) -2.9341583512465685e-01;
work->Prob.Ae[564] = (realtype) -2.5160876398724069e-01;
work->Prob.Ae[565] = (realtype) -3.5968343828761734e-01;
work->Prob.Ae[566] = (realtype) 1.0956847940072119e+00;
work->Prob.Ae[567] = (realtype) 8.5689400586403264e-01;
work->Prob.Ae[604] = (realtype) 8.0939558401405343e-01;
work->Prob.Ae[605] = (realtype) -5.3385909811798404e-01;
work->Prob.Ae[606] = (realtype) 6.4910346030655353e-01;
work->Prob.Ae[607] = (realtype) 6.5834026750400165e-01;
work->Prob.Ae[648] = (realtype) -7.7364281893375786e-01;
work->Prob.Ae[649] = (realtype) -2.8387796751443783e-01;
work->Prob.Ae[650] = (realtype) -2.1964304529332286e+00;
work->Prob.Ae[651] = (realtype) -1.8752673644971860e-01;
work->Prob.Ae[688] = (realtype) -1.0162249319013750e+00;
work->Prob.Ae[689] = (realtype) -1.1118743076821114e+00;
work->Prob.Ae[690] = (realtype) -1.3369464168334997e+00;
work->Prob.Ae[691] = (realtype) -9.5933225134066616e-02;
work->Prob.Ae[728] = (realtype) 1.8362345259632476e-01;
work->Prob.Ae[729] = (realtype) 3.8809349529954229e-01;
work->Prob.Ae[730] = (realtype) -1.2137026243403307e-01;
work->Prob.Ae[731] = (realtype) 8.9907805001539953e-01;
work->Prob.Ae[768] = (realtype) 5.4982276497308902e-01;
work->Prob.Ae[769] = (realtype) -6.0099714127186632e-01;
work->Prob.Ae[770] = (realtype) 1.6900102834521025e+00;
work->Prob.Ae[771] = (realtype) 1.1686191146041705e+00;
work->Prob.Ae[808] = (realtype) -1.4967466996724184e+00;
work->Prob.Ae[809] = (realtype) -1.6560124735546085e+00;
work->Prob.Ae[810] = (realtype) -8.8495879219418472e-01;
work->Prob.Ae[811] = (realtype) 2.1787817396978837e+00;
work->Prob.Ae[848] = (realtype) -2.1174127086103121e+00;
work->Prob.Ae[849] = (realtype) -2.5004160442750079e-01;
work->Prob.Ae[850] = (realtype) -1.2806434955104790e-01;
work->Prob.Ae[851] = (realtype) -2.9341583512465685e-01;
work->Prob.Ae[888] = (realtype) -2.5160876398724069e-01;
work->Prob.Ae[889] = (realtype) -3.5968343828761734e-01;
work->Prob.Ae[890] = (realtype) 1.0956847940072119e+00;
work->Prob.Ae[891] = (realtype) 8.5689400586403264e-01;
work->Prob.Ae[928] = (realtype) 8.0939558401405343e-01;
work->Prob.Ae[929] = (realtype) -5.3385909811798404e-01;
work->Prob.Ae[930] = (realtype) 6.4910346030655353e-01;
work->Prob.Ae[931] = (realtype) 6.5834026750400165e-01;
work->Prob.Ae[972] = (realtype) -7.7364281893375786e-01;
work->Prob.Ae[973] = (realtype) -2.8387796751443783e-01;
work->Prob.Ae[974] = (realtype) -2.1964304529332286e+00;
work->Prob.Ae[975] = (realtype) -1.8752673644971860e-01;
work->Prob.Ae[1012] = (realtype) -1.0162249319013750e+00;
work->Prob.Ae[1013] = (realtype) -1.1118743076821114e+00;
work->Prob.Ae[1014] = (realtype) -1.3369464168334997e+00;
work->Prob.Ae[1015] = (realtype) -9.5933225134066616e-02;
work->Prob.Ae[1052] = (realtype) 1.8362345259632476e-01;
work->Prob.Ae[1053] = (realtype) 3.8809349529954229e-01;
work->Prob.Ae[1054] = (realtype) -1.2137026243403307e-01;
work->Prob.Ae[1055] = (realtype) 8.9907805001539953e-01;
work->Prob.Ae[1092] = (realtype) 5.4982276497308902e-01;
work->Prob.Ae[1093] = (realtype) -6.0099714127186632e-01;
work->Prob.Ae[1094] = (realtype) 1.6900102834521025e+00;
work->Prob.Ae[1095] = (realtype) 1.1686191146041705e+00;
work->Prob.Ae[1132] = (realtype) -1.4967466996724184e+00;
work->Prob.Ae[1133] = (realtype) -1.6560124735546085e+00;
work->Prob.Ae[1134] = (realtype) -8.8495879219418472e-01;
work->Prob.Ae[1135] = (realtype) 2.1787817396978837e+00;
work->Prob.Ae[1172] = (realtype) -2.1174127086103121e+00;
work->Prob.Ae[1173] = (realtype) -2.5004160442750079e-01;
work->Prob.Ae[1174] = (realtype) -1.2806434955104790e-01;
work->Prob.Ae[1175] = (realtype) -2.9341583512465685e-01;
work->Prob.Ae[1212] = (realtype) -2.5160876398724069e-01;
work->Prob.Ae[1213] = (realtype) -3.5968343828761734e-01;
work->Prob.Ae[1214] = (realtype) 1.0956847940072119e+00;
work->Prob.Ae[1215] = (realtype) 8.5689400586403264e-01;
work->Prob.Ae[1252] = (realtype) 8.0939558401405343e-01;
work->Prob.Ae[1253] = (realtype) -5.3385909811798404e-01;
work->Prob.Ae[1254] = (realtype) 6.4910346030655353e-01;
work->Prob.Ae[1255] = (realtype) 6.5834026750400165e-01;
work->Prob.Ae[1296] = (realtype) -7.7364281893375786e-01;
work->Prob.Ae[1297] = (realtype) -2.8387796751443783e-01;
work->Prob.Ae[1298] = (realtype) -2.1964304529332286e+00;
work->Prob.Ae[1299] = (realtype) -1.8752673644971860e-01;
work->Prob.Ae[1336] = (realtype) -1.0162249319013750e+00;
work->Prob.Ae[1337] = (realtype) -1.1118743076821114e+00;
work->Prob.Ae[1338] = (realtype) -1.3369464168334997e+00;
work->Prob.Ae[1339] = (realtype) -9.5933225134066616e-02;
work->Prob.Ae[1376] = (realtype) 1.8362345259632476e-01;
work->Prob.Ae[1377] = (realtype) 3.8809349529954229e-01;
work->Prob.Ae[1378] = (realtype) -1.2137026243403307e-01;
work->Prob.Ae[1379] = (realtype) 8.9907805001539953e-01;
work->Prob.Ae[1416] = (realtype) 5.4982276497308902e-01;
work->Prob.Ae[1417] = (realtype) -6.0099714127186632e-01;
work->Prob.Ae[1418] = (realtype) 1.6900102834521025e+00;
work->Prob.Ae[1419] = (realtype) 1.1686191146041705e+00;
work->Prob.Ae[1456] = (realtype) -1.4967466996724184e+00;
work->Prob.Ae[1457] = (realtype) -1.6560124735546085e+00;
work->Prob.Ae[1458] = (realtype) -8.8495879219418472e-01;
work->Prob.Ae[1459] = (realtype) 2.1787817396978837e+00;
work->Prob.Ae[1496] = (realtype) -2.1174127086103121e+00;
work->Prob.Ae[1497] = (realtype) -2.5004160442750079e-01;
work->Prob.Ae[1498] = (realtype) -1.2806434955104790e-01;
work->Prob.Ae[1499] = (realtype) -2.9341583512465685e-01;
work->Prob.Ae[1536] = (realtype) -2.5160876398724069e-01;
work->Prob.Ae[1537] = (realtype) -3.5968343828761734e-01;
work->Prob.Ae[1538] = (realtype) 1.0956847940072119e+00;
work->Prob.Ae[1539] = (realtype) 8.5689400586403264e-01;
work->Prob.Ae[1576] = (realtype) 8.0939558401405343e-01;
work->Prob.Ae[1577] = (realtype) -5.3385909811798404e-01;
work->Prob.Ae[1578] = (realtype) 6.4910346030655353e-01;
work->Prob.Ae[1579] = (realtype) 6.5834026750400165e-01;
work->Prob.Ae[1620] = (realtype) -7.7364281893375786e-01;
work->Prob.Ae[1621] = (realtype) -2.8387796751443783e-01;
work->Prob.Ae[1622] = (realtype) -2.1964304529332286e+00;
work->Prob.Ae[1623] = (realtype) -1.8752673644971860e-01;
work->Prob.Ae[1660] = (realtype) -1.0162249319013750e+00;
work->Prob.Ae[1661] = (realtype) -1.1118743076821114e+00;
work->Prob.Ae[1662] = (realtype) -1.3369464168334997e+00;
work->Prob.Ae[1663] = (realtype) -9.5933225134066616e-02;
work->Prob.Ae[1700] = (realtype) 1.8362345259632476e-01;
work->Prob.Ae[1701] = (realtype) 3.8809349529954229e-01;
work->Prob.Ae[1702] = (realtype) -1.2137026243403307e-01;
work->Prob.Ae[1703] = (realtype) 8.9907805001539953e-01;
work->Prob.Ae[1740] = (realtype) 5.4982276497308902e-01;
work->Prob.Ae[1741] = (realtype) -6.0099714127186632e-01;
work->Prob.Ae[1742] = (realtype) 1.6900102834521025e+00;
work->Prob.Ae[1743] = (realtype) 1.1686191146041705e+00;
work->Prob.Ae[1780] = (realtype) -1.4967466996724184e+00;
work->Prob.Ae[1781] = (realtype) -1.6560124735546085e+00;
work->Prob.Ae[1782] = (realtype) -8.8495879219418472e-01;
work->Prob.Ae[1783] = (realtype) 2.1787817396978837e+00;
work->Prob.Ae[1820] = (realtype) -2.1174127086103121e+00;
work->Prob.Ae[1821] = (realtype) -2.5004160442750079e-01;
work->Prob.Ae[1822] = (realtype) -1.2806434955104790e-01;
work->Prob.Ae[1823] = (realtype) -2.9341583512465685e-01;
work->Prob.Ae[1860] = (realtype) -2.5160876398724069e-01;
work->Prob.Ae[1861] = (realtype) -3.5968343828761734e-01;
work->Prob.Ae[1862] = (realtype) 1.0956847940072119e+00;
work->Prob.Ae[1863] = (realtype) 8.5689400586403264e-01;
work->Prob.Ae[1900] = (realtype) 8.0939558401405343e-01;
work->Prob.Ae[1901] = (realtype) -5.3385909811798404e-01;
work->Prob.Ae[1902] = (realtype) 6.4910346030655353e-01;
work->Prob.Ae[1903] = (realtype) 6.5834026750400165e-01;
work->Prob.Ae[1944] = (realtype) -7.7364281893375786e-01;
work->Prob.Ae[1945] = (realtype) -2.8387796751443783e-01;
work->Prob.Ae[1946] = (realtype) -2.1964304529332286e+00;
work->Prob.Ae[1947] = (realtype) -1.8752673644971860e-01;
work->Prob.Ae[1984] = (realtype) -1.0162249319013750e+00;
work->Prob.Ae[1985] = (realtype) -1.1118743076821114e+00;
work->Prob.Ae[1986] = (realtype) -1.3369464168334997e+00;
work->Prob.Ae[1987] = (realtype) -9.5933225134066616e-02;
work->Prob.Ae[2024] = (realtype) 1.8362345259632476e-01;
work->Prob.Ae[2025] = (realtype) 3.8809349529954229e-01;
work->Prob.Ae[2026] = (realtype) -1.2137026243403307e-01;
work->Prob.Ae[2027] = (realtype) 8.9907805001539953e-01;
work->Prob.Ae[2064] = (realtype) 5.4982276497308902e-01;
work->Prob.Ae[2065] = (realtype) -6.0099714127186632e-01;
work->Prob.Ae[2066] = (realtype) 1.6900102834521025e+00;
work->Prob.Ae[2067] = (realtype) 1.1686191146041705e+00;
work->Prob.Ae[2104] = (realtype) -1.4967466996724184e+00;
work->Prob.Ae[2105] = (realtype) -1.6560124735546085e+00;
work->Prob.Ae[2106] = (realtype) -8.8495879219418472e-01;
work->Prob.Ae[2107] = (realtype) 2.1787817396978837e+00;
work->Prob.Ae[2144] = (realtype) -2.1174127086103121e+00;
work->Prob.Ae[2145] = (realtype) -2.5004160442750079e-01;
work->Prob.Ae[2146] = (realtype) -1.2806434955104790e-01;
work->Prob.Ae[2147] = (realtype) -2.9341583512465685e-01;
work->Prob.Ae[2184] = (realtype) -2.5160876398724069e-01;
work->Prob.Ae[2185] = (realtype) -3.5968343828761734e-01;
work->Prob.Ae[2186] = (realtype) 1.0956847940072119e+00;
work->Prob.Ae[2187] = (realtype) 8.5689400586403264e-01;
work->Prob.Ae[2224] = (realtype) 8.0939558401405343e-01;
work->Prob.Ae[2225] = (realtype) -5.3385909811798404e-01;
work->Prob.Ae[2226] = (realtype) 6.4910346030655353e-01;
work->Prob.Ae[2227] = (realtype) 6.5834026750400165e-01;
work->Prob.Ae[2268] = (realtype) -7.7364281893375786e-01;
work->Prob.Ae[2269] = (realtype) -2.8387796751443783e-01;
work->Prob.Ae[2270] = (realtype) -2.1964304529332286e+00;
work->Prob.Ae[2271] = (realtype) -1.8752673644971860e-01;
work->Prob.Ae[2308] = (realtype) -1.0162249319013750e+00;
work->Prob.Ae[2309] = (realtype) -1.1118743076821114e+00;
work->Prob.Ae[2310] = (realtype) -1.3369464168334997e+00;
work->Prob.Ae[2311] = (realtype) -9.5933225134066616e-02;
work->Prob.Ae[2348] = (realtype) 1.8362345259632476e-01;
work->Prob.Ae[2349] = (realtype) 3.8809349529954229e-01;
work->Prob.Ae[2350] = (realtype) -1.2137026243403307e-01;
work->Prob.Ae[2351] = (realtype) 8.9907805001539953e-01;
work->Prob.Ae[2388] = (realtype) 5.4982276497308902e-01;
work->Prob.Ae[2389] = (realtype) -6.0099714127186632e-01;
work->Prob.Ae[2390] = (realtype) 1.6900102834521025e+00;
work->Prob.Ae[2391] = (realtype) 1.1686191146041705e+00;
work->Prob.Ae[2428] = (realtype) -1.4967466996724184e+00;
work->Prob.Ae[2429] = (realtype) -1.6560124735546085e+00;
work->Prob.Ae[2430] = (realtype) -8.8495879219418472e-01;
work->Prob.Ae[2431] = (realtype) 2.1787817396978837e+00;
work->Prob.Ae[2468] = (realtype) -2.1174127086103121e+00;
work->Prob.Ae[2469] = (realtype) -2.5004160442750079e-01;
work->Prob.Ae[2470] = (realtype) -1.2806434955104790e-01;
work->Prob.Ae[2471] = (realtype) -2.9341583512465685e-01;
work->Prob.Ae[2508] = (realtype) -2.5160876398724069e-01;
work->Prob.Ae[2509] = (realtype) -3.5968343828761734e-01;
work->Prob.Ae[2510] = (realtype) 1.0956847940072119e+00;
work->Prob.Ae[2511] = (realtype) 8.5689400586403264e-01;
work->Prob.Ae[2548] = (realtype) 8.0939558401405343e-01;
work->Prob.Ae[2549] = (realtype) -5.3385909811798404e-01;
work->Prob.Ae[2550] = (realtype) 6.4910346030655353e-01;
work->Prob.Ae[2551] = (realtype) 6.5834026750400165e-01;
work->Prob.Ae[2592] = (realtype) -7.7364281893375786e-01;
work->Prob.Ae[2593] = (realtype) -2.8387796751443783e-01;
work->Prob.Ae[2594] = (realtype) -2.1964304529332286e+00;
work->Prob.Ae[2595] = (realtype) -1.8752673644971860e-01;
work->Prob.Ae[2632] = (realtype) -1.0162249319013750e+00;
work->Prob.Ae[2633] = (realtype) -1.1118743076821114e+00;
work->Prob.Ae[2634] = (realtype) -1.3369464168334997e+00;
work->Prob.Ae[2635] = (realtype) -9.5933225134066616e-02;
work->Prob.Ae[2672] = (realtype) 1.8362345259632476e-01;
work->Prob.Ae[2673] = (realtype) 3.8809349529954229e-01;
work->Prob.Ae[2674] = (realtype) -1.2137026243403307e-01;
work->Prob.Ae[2675] = (realtype) 8.9907805001539953e-01;
work->Prob.Ae[2712] = (realtype) 5.4982276497308902e-01;
work->Prob.Ae[2713] = (realtype) -6.0099714127186632e-01;
work->Prob.Ae[2714] = (realtype) 1.6900102834521025e+00;
work->Prob.Ae[2715] = (realtype) 1.1686191146041705e+00;
work->Prob.Ae[2752] = (realtype) -1.4967466996724184e+00;
work->Prob.Ae[2753] = (realtype) -1.6560124735546085e+00;
work->Prob.Ae[2754] = (realtype) -8.8495879219418472e-01;
work->Prob.Ae[2755] = (realtype) 2.1787817396978837e+00;
work->Prob.Ae[2792] = (realtype) -2.1174127086103121e+00;
work->Prob.Ae[2793] = (realtype) -2.5004160442750079e-01;
work->Prob.Ae[2794] = (realtype) -1.2806434955104790e-01;
work->Prob.Ae[2795] = (realtype) -2.9341583512465685e-01;
work->Prob.Ae[2832] = (realtype) -2.5160876398724069e-01;
work->Prob.Ae[2833] = (realtype) -3.5968343828761734e-01;
work->Prob.Ae[2834] = (realtype) 1.0956847940072119e+00;
work->Prob.Ae[2835] = (realtype) 8.5689400586403264e-01;
work->Prob.Ae[2872] = (realtype) 8.0939558401405343e-01;
work->Prob.Ae[2873] = (realtype) -5.3385909811798404e-01;
work->Prob.Ae[2874] = (realtype) 6.4910346030655353e-01;
work->Prob.Ae[2875] = (realtype) 6.5834026750400165e-01;
work->Prob.Ae[2916] = (realtype) -7.7364281893375786e-01;
work->Prob.Ae[2917] = (realtype) -2.8387796751443783e-01;
work->Prob.Ae[2918] = (realtype) -2.1964304529332286e+00;
work->Prob.Ae[2919] = (realtype) -1.8752673644971860e-01;
work->Prob.Ae[2956] = (realtype) -1.0162249319013750e+00;
work->Prob.Ae[2957] = (realtype) -1.1118743076821114e+00;
work->Prob.Ae[2958] = (realtype) -1.3369464168334997e+00;
work->Prob.Ae[2959] = (realtype) -9.5933225134066616e-02;
work->Prob.Ae[2996] = (realtype) 1.8362345259632476e-01;
work->Prob.Ae[2997] = (realtype) 3.8809349529954229e-01;
work->Prob.Ae[2998] = (realtype) -1.2137026243403307e-01;
work->Prob.Ae[2999] = (realtype) 8.9907805001539953e-01;
work->Prob.Ae[3036] = (realtype) 5.4982276497308902e-01;
work->Prob.Ae[3037] = (realtype) -6.0099714127186632e-01;
work->Prob.Ae[3038] = (realtype) 1.6900102834521025e+00;
work->Prob.Ae[3039] = (realtype) 1.1686191146041705e+00;
work->Prob.Ae[3076] = (realtype) -1.4967466996724184e+00;
work->Prob.Ae[3077] = (realtype) -1.6560124735546085e+00;
work->Prob.Ae[3078] = (realtype) -8.8495879219418472e-01;
work->Prob.Ae[3079] = (realtype) 2.1787817396978837e+00;
work->Prob.Ae[3116] = (realtype) -2.1174127086103121e+00;
work->Prob.Ae[3117] = (realtype) -2.5004160442750079e-01;
work->Prob.Ae[3118] = (realtype) -1.2806434955104790e-01;
work->Prob.Ae[3119] = (realtype) -2.9341583512465685e-01;
work->Prob.Ae[3156] = (realtype) -2.5160876398724069e-01;
work->Prob.Ae[3157] = (realtype) -3.5968343828761734e-01;
work->Prob.Ae[3158] = (realtype) 1.0956847940072119e+00;
work->Prob.Ae[3159] = (realtype) 8.5689400586403264e-01;
work->Prob.Ae[3196] = (realtype) 8.0939558401405343e-01;
work->Prob.Ae[3197] = (realtype) -5.3385909811798404e-01;
work->Prob.Ae[3198] = (realtype) 6.4910346030655353e-01;
work->Prob.Ae[3199] = (realtype) 6.5834026750400165e-01;
work->Prob.Ae[3200] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[3204] = (realtype) 2.4632148584450467e-01;
work->Prob.Ae[3205] = (realtype) -1.4051874042093079e-01;
work->Prob.Ae[3206] = (realtype) 3.8763803705543670e-01;
work->Prob.Ae[3207] = (realtype) 4.5004627477006331e-01;
work->Prob.Ae[3241] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[3244] = (realtype) 8.1882962328316631e-03;
work->Prob.Ae[3245] = (realtype) 1.3901245683499144e-01;
work->Prob.Ae[3246] = (realtype) 6.8508498371403770e-02;
work->Prob.Ae[3247] = (realtype) 1.0743182431325245e-01;
work->Prob.Ae[3282] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[3284] = (realtype) -1.4675123182301564e-01;
work->Prob.Ae[3285] = (realtype) 4.8217050951708376e-02;
work->Prob.Ae[3286] = (realtype) 1.7395171160597949e-02;
work->Prob.Ae[3287] = (realtype) -4.0855999810198679e-01;
work->Prob.Ae[3323] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[3324] = (realtype) 5.5122769098058277e-01;
work->Prob.Ae[3325] = (realtype) 6.8947888518339079e-02;
work->Prob.Ae[3326] = (realtype) 2.7136763339183939e-02;
work->Prob.Ae[3327] = (realtype) 4.7493786059809173e-01;
work->Prob.Ae[3364] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[3368] = (realtype) 2.4632148584450467e-01;
work->Prob.Ae[3369] = (realtype) -1.4051874042093079e-01;
work->Prob.Ae[3370] = (realtype) 3.8763803705543670e-01;
work->Prob.Ae[3371] = (realtype) 4.5004627477006331e-01;
work->Prob.Ae[3405] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[3408] = (realtype) 8.1882962328316631e-03;
work->Prob.Ae[3409] = (realtype) 1.3901245683499144e-01;
work->Prob.Ae[3410] = (realtype) 6.8508498371403770e-02;
work->Prob.Ae[3411] = (realtype) 1.0743182431325245e-01;
work->Prob.Ae[3446] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[3448] = (realtype) -1.4675123182301564e-01;
work->Prob.Ae[3449] = (realtype) 4.8217050951708376e-02;
work->Prob.Ae[3450] = (realtype) 1.7395171160597949e-02;
work->Prob.Ae[3451] = (realtype) -4.0855999810198679e-01;
work->Prob.Ae[3487] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[3488] = (realtype) 5.5122769098058277e-01;
work->Prob.Ae[3489] = (realtype) 6.8947888518339079e-02;
work->Prob.Ae[3490] = (realtype) 2.7136763339183939e-02;
work->Prob.Ae[3491] = (realtype) 4.7493786059809173e-01;
work->Prob.Ae[3528] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[3532] = (realtype) 2.4632148584450467e-01;
work->Prob.Ae[3533] = (realtype) -1.4051874042093079e-01;
work->Prob.Ae[3534] = (realtype) 3.8763803705543670e-01;
work->Prob.Ae[3535] = (realtype) 4.5004627477006331e-01;
work->Prob.Ae[3569] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[3572] = (realtype) 8.1882962328316631e-03;
work->Prob.Ae[3573] = (realtype) 1.3901245683499144e-01;
work->Prob.Ae[3574] = (realtype) 6.8508498371403770e-02;
work->Prob.Ae[3575] = (realtype) 1.0743182431325245e-01;
work->Prob.Ae[3610] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[3612] = (realtype) -1.4675123182301564e-01;
work->Prob.Ae[3613] = (realtype) 4.8217050951708376e-02;
work->Prob.Ae[3614] = (realtype) 1.7395171160597949e-02;
work->Prob.Ae[3615] = (realtype) -4.0855999810198679e-01;
work->Prob.Ae[3651] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[3652] = (realtype) 5.5122769098058277e-01;
work->Prob.Ae[3653] = (realtype) 6.8947888518339079e-02;
work->Prob.Ae[3654] = (realtype) 2.7136763339183939e-02;
work->Prob.Ae[3655] = (realtype) 4.7493786059809173e-01;
work->Prob.Ae[3692] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[3696] = (realtype) 2.4632148584450467e-01;
work->Prob.Ae[3697] = (realtype) -1.4051874042093079e-01;
work->Prob.Ae[3698] = (realtype) 3.8763803705543670e-01;
work->Prob.Ae[3699] = (realtype) 4.5004627477006331e-01;
work->Prob.Ae[3733] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[3736] = (realtype) 8.1882962328316631e-03;
work->Prob.Ae[3737] = (realtype) 1.3901245683499144e-01;
work->Prob.Ae[3738] = (realtype) 6.8508498371403770e-02;
work->Prob.Ae[3739] = (realtype) 1.0743182431325245e-01;
work->Prob.Ae[3774] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[3776] = (realtype) -1.4675123182301564e-01;
work->Prob.Ae[3777] = (realtype) 4.8217050951708376e-02;
work->Prob.Ae[3778] = (realtype) 1.7395171160597949e-02;
work->Prob.Ae[3779] = (realtype) -4.0855999810198679e-01;
work->Prob.Ae[3815] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[3816] = (realtype) 5.5122769098058277e-01;
work->Prob.Ae[3817] = (realtype) 6.8947888518339079e-02;
work->Prob.Ae[3818] = (realtype) 2.7136763339183939e-02;
work->Prob.Ae[3819] = (realtype) 4.7493786059809173e-01;
work->Prob.Ae[3856] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[3860] = (realtype) 2.4632148584450467e-01;
work->Prob.Ae[3861] = (realtype) -1.4051874042093079e-01;
work->Prob.Ae[3862] = (realtype) 3.8763803705543670e-01;
work->Prob.Ae[3863] = (realtype) 4.5004627477006331e-01;
work->Prob.Ae[3897] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[3900] = (realtype) 8.1882962328316631e-03;
work->Prob.Ae[3901] = (realtype) 1.3901245683499144e-01;
work->Prob.Ae[3902] = (realtype) 6.8508498371403770e-02;
work->Prob.Ae[3903] = (realtype) 1.0743182431325245e-01;
work->Prob.Ae[3938] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[3940] = (realtype) -1.4675123182301564e-01;
work->Prob.Ae[3941] = (realtype) 4.8217050951708376e-02;
work->Prob.Ae[3942] = (realtype) 1.7395171160597949e-02;
work->Prob.Ae[3943] = (realtype) -4.0855999810198679e-01;
work->Prob.Ae[3979] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[3980] = (realtype) 5.5122769098058277e-01;
work->Prob.Ae[3981] = (realtype) 6.8947888518339079e-02;
work->Prob.Ae[3982] = (realtype) 2.7136763339183939e-02;
work->Prob.Ae[3983] = (realtype) 4.7493786059809173e-01;
work->Prob.Ae[4020] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[4024] = (realtype) 2.4632148584450467e-01;
work->Prob.Ae[4025] = (realtype) -1.4051874042093079e-01;
work->Prob.Ae[4026] = (realtype) 3.8763803705543670e-01;
work->Prob.Ae[4027] = (realtype) 4.5004627477006331e-01;
work->Prob.Ae[4061] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[4064] = (realtype) 8.1882962328316631e-03;
work->Prob.Ae[4065] = (realtype) 1.3901245683499144e-01;
work->Prob.Ae[4066] = (realtype) 6.8508498371403770e-02;
work->Prob.Ae[4067] = (realtype) 1.0743182431325245e-01;
work->Prob.Ae[4102] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[4104] = (realtype) -1.4675123182301564e-01;
work->Prob.Ae[4105] = (realtype) 4.8217050951708376e-02;
work->Prob.Ae[4106] = (realtype) 1.7395171160597949e-02;
work->Prob.Ae[4107] = (realtype) -4.0855999810198679e-01;
work->Prob.Ae[4143] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[4144] = (realtype) 5.5122769098058277e-01;
work->Prob.Ae[4145] = (realtype) 6.8947888518339079e-02;
work->Prob.Ae[4146] = (realtype) 2.7136763339183939e-02;
work->Prob.Ae[4147] = (realtype) 4.7493786059809173e-01;
work->Prob.Ae[4184] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[4188] = (realtype) 2.4632148584450467e-01;
work->Prob.Ae[4189] = (realtype) -1.4051874042093079e-01;
work->Prob.Ae[4190] = (realtype) 3.8763803705543670e-01;
work->Prob.Ae[4191] = (realtype) 4.5004627477006331e-01;
work->Prob.Ae[4225] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[4228] = (realtype) 8.1882962328316631e-03;
work->Prob.Ae[4229] = (realtype) 1.3901245683499144e-01;
work->Prob.Ae[4230] = (realtype) 6.8508498371403770e-02;
work->Prob.Ae[4231] = (realtype) 1.0743182431325245e-01;
work->Prob.Ae[4266] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[4268] = (realtype) -1.4675123182301564e-01;
work->Prob.Ae[4269] = (realtype) 4.8217050951708376e-02;
work->Prob.Ae[4270] = (realtype) 1.7395171160597949e-02;
work->Prob.Ae[4271] = (realtype) -4.0855999810198679e-01;
work->Prob.Ae[4307] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[4308] = (realtype) 5.5122769098058277e-01;
work->Prob.Ae[4309] = (realtype) 6.8947888518339079e-02;
work->Prob.Ae[4310] = (realtype) 2.7136763339183939e-02;
work->Prob.Ae[4311] = (realtype) 4.7493786059809173e-01;
work->Prob.Ae[4348] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[4352] = (realtype) 2.4632148584450467e-01;
work->Prob.Ae[4353] = (realtype) -1.4051874042093079e-01;
work->Prob.Ae[4354] = (realtype) 3.8763803705543670e-01;
work->Prob.Ae[4355] = (realtype) 4.5004627477006331e-01;
work->Prob.Ae[4389] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[4392] = (realtype) 8.1882962328316631e-03;
work->Prob.Ae[4393] = (realtype) 1.3901245683499144e-01;
work->Prob.Ae[4394] = (realtype) 6.8508498371403770e-02;
work->Prob.Ae[4395] = (realtype) 1.0743182431325245e-01;
work->Prob.Ae[4430] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[4432] = (realtype) -1.4675123182301564e-01;
work->Prob.Ae[4433] = (realtype) 4.8217050951708376e-02;
work->Prob.Ae[4434] = (realtype) 1.7395171160597949e-02;
work->Prob.Ae[4435] = (realtype) -4.0855999810198679e-01;
work->Prob.Ae[4471] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[4472] = (realtype) 5.5122769098058277e-01;
work->Prob.Ae[4473] = (realtype) 6.8947888518339079e-02;
work->Prob.Ae[4474] = (realtype) 2.7136763339183939e-02;
work->Prob.Ae[4475] = (realtype) 4.7493786059809173e-01;
work->Prob.Ae[4512] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[4516] = (realtype) 2.4632148584450467e-01;
work->Prob.Ae[4517] = (realtype) -1.4051874042093079e-01;
work->Prob.Ae[4518] = (realtype) 3.8763803705543670e-01;
work->Prob.Ae[4519] = (realtype) 4.5004627477006331e-01;
work->Prob.Ae[4553] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[4556] = (realtype) 8.1882962328316631e-03;
work->Prob.Ae[4557] = (realtype) 1.3901245683499144e-01;
work->Prob.Ae[4558] = (realtype) 6.8508498371403770e-02;
work->Prob.Ae[4559] = (realtype) 1.0743182431325245e-01;
work->Prob.Ae[4594] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[4596] = (realtype) -1.4675123182301564e-01;
work->Prob.Ae[4597] = (realtype) 4.8217050951708376e-02;
work->Prob.Ae[4598] = (realtype) 1.7395171160597949e-02;
work->Prob.Ae[4599] = (realtype) -4.0855999810198679e-01;
work->Prob.Ae[4635] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[4636] = (realtype) 5.5122769098058277e-01;
work->Prob.Ae[4637] = (realtype) 6.8947888518339079e-02;
work->Prob.Ae[4638] = (realtype) 2.7136763339183939e-02;
work->Prob.Ae[4639] = (realtype) 4.7493786059809173e-01;
work->Prob.Ae[4676] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[4717] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[4758] = (realtype) 1.0000000000000000e+00;
work->Prob.Ae[4799] = (realtype) 1.0000000000000000e+00;
work->Prob.X1.l[0] = (realtype) -1.0000000000000000e+01;
work->Prob.X1.l[1] = (realtype) -1.0000000000000000e+01;
work->Prob.X1.l[2] = (realtype) -1.0000000000000000e+01;
work->Prob.X1.l[3] = (realtype) -1.0000000000000000e+01;
work->Prob.X1.l[4] = (realtype) -1.0000000000000000e+01;
work->Prob.X1.l[5] = (realtype) -1.0000000000000000e+01;
work->Prob.X1.l[6] = (realtype) -1.0000000000000000e+01;
work->Prob.X1.l[7] = (realtype) -1.0000000000000000e+01;
work->Prob.X1.u[0] = (realtype) 1.0000000000000000e+01;
work->Prob.X1.u[1] = (realtype) 1.0000000000000000e+01;
work->Prob.X1.u[2] = (realtype) 1.0000000000000000e+01;
work->Prob.X1.u[3] = (realtype) 1.0000000000000000e+01;
work->Prob.X1.u[4] = (realtype) 1.0000000000000000e+01;
work->Prob.X1.u[5] = (realtype) 1.0000000000000000e+01;
work->Prob.X1.u[6] = (realtype) 1.0000000000000000e+01;
work->Prob.X1.u[7] = (realtype) 1.0000000000000000e+01;
work->Prob.X2.l[0] = (realtype) -1.0000000000000000e+01;
work->Prob.X2.l[1] = (realtype) -1.0000000000000000e+01;
work->Prob.X2.l[2] = (realtype) -1.0000000000000000e+01;
work->Prob.X2.l[3] = (realtype) -1.0000000000000000e+01;
work->Prob.X2.l[4] = (realtype) -1.0000000000000000e+01;
work->Prob.X2.l[5] = (realtype) -1.0000000000000000e+01;
work->Prob.X2.l[6] = (realtype) -1.0000000000000000e+01;
work->Prob.X2.l[7] = (realtype) -1.0000000000000000e+01;
work->Prob.X2.u[0] = (realtype) 1.0000000000000000e+01;
work->Prob.X2.u[1] = (realtype) 1.0000000000000000e+01;
work->Prob.X2.u[2] = (realtype) 1.0000000000000000e+01;
work->Prob.X2.u[3] = (realtype) 1.0000000000000000e+01;
work->Prob.X2.u[4] = (realtype) 1.0000000000000000e+01;
work->Prob.X2.u[5] = (realtype) 1.0000000000000000e+01;
work->Prob.X2.u[6] = (realtype) 1.0000000000000000e+01;
work->Prob.X2.u[7] = (realtype) 1.0000000000000000e+01;
work->Prob.X3.l[0] = (realtype) -1.0000000000000000e+01;
work->Prob.X3.l[1] = (realtype) -1.0000000000000000e+01;
work->Prob.X3.l[2] = (realtype) -1.0000000000000000e+01;
work->Prob.X3.l[3] = (realtype) -1.0000000000000000e+01;
work->Prob.X3.l[4] = (realtype) -1.0000000000000000e+01;
work->Prob.X3.l[5] = (realtype) -1.0000000000000000e+01;
work->Prob.X3.l[6] = (realtype) -1.0000000000000000e+01;
work->Prob.X3.l[7] = (realtype) -1.0000000000000000e+01;
work->Prob.X3.u[0] = (realtype) 1.0000000000000000e+01;
work->Prob.X3.u[1] = (realtype) 1.0000000000000000e+01;
work->Prob.X3.u[2] = (realtype) 1.0000000000000000e+01;
work->Prob.X3.u[3] = (realtype) 1.0000000000000000e+01;
work->Prob.X3.u[4] = (realtype) 1.0000000000000000e+01;
work->Prob.X3.u[5] = (realtype) 1.0000000000000000e+01;
work->Prob.X3.u[6] = (realtype) 1.0000000000000000e+01;
work->Prob.X3.u[7] = (realtype) 1.0000000000000000e+01;
work->Prob.X4.l[0] = (realtype) -1.0000000000000000e+01;
work->Prob.X4.l[1] = (realtype) -1.0000000000000000e+01;
work->Prob.X4.l[2] = (realtype) -1.0000000000000000e+01;
work->Prob.X4.l[3] = (realtype) -1.0000000000000000e+01;
work->Prob.X4.l[4] = (realtype) -1.0000000000000000e+01;
work->Prob.X4.l[5] = (realtype) -1.0000000000000000e+01;
work->Prob.X4.l[6] = (realtype) -1.0000000000000000e+01;
work->Prob.X4.l[7] = (realtype) -1.0000000000000000e+01;
work->Prob.X4.u[0] = (realtype) 1.0000000000000000e+01;
work->Prob.X4.u[1] = (realtype) 1.0000000000000000e+01;
work->Prob.X4.u[2] = (realtype) 1.0000000000000000e+01;
work->Prob.X4.u[3] = (realtype) 1.0000000000000000e+01;
work->Prob.X4.u[4] = (realtype) 1.0000000000000000e+01;
work->Prob.X4.u[5] = (realtype) 1.0000000000000000e+01;
work->Prob.X4.u[6] = (realtype) 1.0000000000000000e+01;
work->Prob.X4.u[7] = (realtype) 1.0000000000000000e+01;
work->Prob.X5.l[0] = (realtype) -1.0000000000000000e+01;
work->Prob.X5.l[1] = (realtype) -1.0000000000000000e+01;
work->Prob.X5.l[2] = (realtype) -1.0000000000000000e+01;
work->Prob.X5.l[3] = (realtype) -1.0000000000000000e+01;
work->Prob.X5.l[4] = (realtype) -1.0000000000000000e+01;
work->Prob.X5.l[5] = (realtype) -1.0000000000000000e+01;
work->Prob.X5.l[6] = (realtype) -1.0000000000000000e+01;
work->Prob.X5.l[7] = (realtype) -1.0000000000000000e+01;
work->Prob.X5.u[0] = (realtype) 1.0000000000000000e+01;
work->Prob.X5.u[1] = (realtype) 1.0000000000000000e+01;
work->Prob.X5.u[2] = (realtype) 1.0000000000000000e+01;
work->Prob.X5.u[3] = (realtype) 1.0000000000000000e+01;
work->Prob.X5.u[4] = (realtype) 1.0000000000000000e+01;
work->Prob.X5.u[5] = (realtype) 1.0000000000000000e+01;
work->Prob.X5.u[6] = (realtype) 1.0000000000000000e+01;
work->Prob.X5.u[7] = (realtype) 1.0000000000000000e+01;
work->Prob.X6.l[0] = (realtype) -1.0000000000000000e+01;
work->Prob.X6.l[1] = (realtype) -1.0000000000000000e+01;
work->Prob.X6.l[2] = (realtype) -1.0000000000000000e+01;
work->Prob.X6.l[3] = (realtype) -1.0000000000000000e+01;
work->Prob.X6.l[4] = (realtype) -1.0000000000000000e+01;
work->Prob.X6.l[5] = (realtype) -1.0000000000000000e+01;
work->Prob.X6.l[6] = (realtype) -1.0000000000000000e+01;
work->Prob.X6.l[7] = (realtype) -1.0000000000000000e+01;
work->Prob.X6.u[0] = (realtype) 1.0000000000000000e+01;
work->Prob.X6.u[1] = (realtype) 1.0000000000000000e+01;
work->Prob.X6.u[2] = (realtype) 1.0000000000000000e+01;
work->Prob.X6.u[3] = (realtype) 1.0000000000000000e+01;
work->Prob.X6.u[4] = (realtype) 1.0000000000000000e+01;
work->Prob.X6.u[5] = (realtype) 1.0000000000000000e+01;
work->Prob.X6.u[6] = (realtype) 1.0000000000000000e+01;
work->Prob.X6.u[7] = (realtype) 1.0000000000000000e+01;
work->Prob.X7.l[0] = (realtype) -1.0000000000000000e+01;
work->Prob.X7.l[1] = (realtype) -1.0000000000000000e+01;
work->Prob.X7.l[2] = (realtype) -1.0000000000000000e+01;
work->Prob.X7.l[3] = (realtype) -1.0000000000000000e+01;
work->Prob.X7.l[4] = (realtype) -1.0000000000000000e+01;
work->Prob.X7.l[5] = (realtype) -1.0000000000000000e+01;
work->Prob.X7.l[6] = (realtype) -1.0000000000000000e+01;
work->Prob.X7.l[7] = (realtype) -1.0000000000000000e+01;
work->Prob.X7.u[0] = (realtype) 1.0000000000000000e+01;
work->Prob.X7.u[1] = (realtype) 1.0000000000000000e+01;
work->Prob.X7.u[2] = (realtype) 1.0000000000000000e+01;
work->Prob.X7.u[3] = (realtype) 1.0000000000000000e+01;
work->Prob.X7.u[4] = (realtype) 1.0000000000000000e+01;
work->Prob.X7.u[5] = (realtype) 1.0000000000000000e+01;
work->Prob.X7.u[6] = (realtype) 1.0000000000000000e+01;
work->Prob.X7.u[7] = (realtype) 1.0000000000000000e+01;
work->Prob.X8.l[0] = (realtype) -1.0000000000000000e+01;
work->Prob.X8.l[1] = (realtype) -1.0000000000000000e+01;
work->Prob.X8.l[2] = (realtype) -1.0000000000000000e+01;
work->Prob.X8.l[3] = (realtype) -1.0000000000000000e+01;
work->Prob.X8.l[4] = (realtype) -1.0000000000000000e+01;
work->Prob.X8.l[5] = (realtype) -1.0000000000000000e+01;
work->Prob.X8.l[6] = (realtype) -1.0000000000000000e+01;
work->Prob.X8.l[7] = (realtype) -1.0000000000000000e+01;
work->Prob.X8.u[0] = (realtype) 1.0000000000000000e+01;
work->Prob.X8.u[1] = (realtype) 1.0000000000000000e+01;
work->Prob.X8.u[2] = (realtype) 1.0000000000000000e+01;
work->Prob.X8.u[3] = (realtype) 1.0000000000000000e+01;
work->Prob.X8.u[4] = (realtype) 1.0000000000000000e+01;
work->Prob.X8.u[5] = (realtype) 1.0000000000000000e+01;
work->Prob.X8.u[6] = (realtype) 1.0000000000000000e+01;
work->Prob.X8.u[7] = (realtype) 1.0000000000000000e+01;
work->Prob.X9.l[0] = (realtype) -1.0000000000000000e+01;
work->Prob.X9.l[1] = (realtype) -1.0000000000000000e+01;
work->Prob.X9.l[2] = (realtype) -1.0000000000000000e+01;
work->Prob.X9.l[3] = (realtype) -1.0000000000000000e+01;
work->Prob.X9.l[4] = (realtype) -1.0000000000000000e+01;
work->Prob.X9.l[5] = (realtype) -1.0000000000000000e+01;
work->Prob.X9.l[6] = (realtype) -1.0000000000000000e+01;
work->Prob.X9.l[7] = (realtype) -1.0000000000000000e+01;
work->Prob.X9.u[0] = (realtype) 1.0000000000000000e+01;
work->Prob.X9.u[1] = (realtype) 1.0000000000000000e+01;
work->Prob.X9.u[2] = (realtype) 1.0000000000000000e+01;
work->Prob.X9.u[3] = (realtype) 1.0000000000000000e+01;
work->Prob.X9.u[4] = (realtype) 1.0000000000000000e+01;
work->Prob.X9.u[5] = (realtype) 1.0000000000000000e+01;
work->Prob.X9.u[6] = (realtype) 1.0000000000000000e+01;
work->Prob.X9.u[7] = (realtype) 1.0000000000000000e+01;
work->Prob.X10.l[0] = (realtype) -1.0000000000000000e+01;
work->Prob.X10.l[1] = (realtype) -1.0000000000000000e+01;
work->Prob.X10.l[2] = (realtype) -1.0000000000000000e+01;
work->Prob.X10.l[3] = (realtype) -1.0000000000000000e+01;
work->Prob.X10.l[4] = (realtype) -1.0000000000000000e+01;
work->Prob.X10.l[5] = (realtype) -1.0000000000000000e+01;
work->Prob.X10.l[6] = (realtype) -1.0000000000000000e+01;
work->Prob.X10.l[7] = (realtype) -1.0000000000000000e+01;
work->Prob.X10.u[0] = (realtype) 1.0000000000000000e+01;
work->Prob.X10.u[1] = (realtype) 1.0000000000000000e+01;
work->Prob.X10.u[2] = (realtype) 1.0000000000000000e+01;
work->Prob.X10.u[3] = (realtype) 1.0000000000000000e+01;
work->Prob.X10.u[4] = (realtype) 1.0000000000000000e+01;
work->Prob.X10.u[5] = (realtype) 1.0000000000000000e+01;
work->Prob.X10.u[6] = (realtype) 1.0000000000000000e+01;
work->Prob.X10.u[7] = (realtype) 1.0000000000000000e+01;
work->algoInner.glob_Linv = (realtype) 1.0000000000000000e+00;
work->algoInner.glob_mu = (realtype) 1.0000000000000000e+00;
work->algoOuter.glob_Linv = (realtype) 5.1268353916467217e-02;
settings->approach.warmstartInner = 1;
{int i; for (i=0;i<120;++i) {settings->algoInner.init[i] = (realtype) 0.0;}}
settings->algoInner.maxit = 5000;
settings->algoInner.stopgEps = (realtype) 1.0000000000000000e-02;
settings->algoInner.stopgStride = 1;
{int i; for (i=0;i<40;++i) {settings->algoOuter.init[i] = (realtype) 0.0;}}
settings->algoOuter.maxit = 5000;
settings->algoOuter.stopgEps = (realtype) 1.0000000000000000e-02;
settings->algoOuter.stopgStride = 1;
}

