% Compiling:
%     ex10_mex_make
% 
% 
% Usage:
%     mres = ex10_mex(mparams)
%     mres = ex10_mex(mparams,msetgs)
% 
%   Inputs:
%     mparams: struct for parametric problem data, required
%     msetgs: struct for settings, optional
% 
%   Template for mparams (each listed field is required):
%     mparams = struct();
%     mparams.g; %[120x1]
%     mparams.c; %[1x1]
%     mparams.be; %[40x1]
% 
%   Template for msetgs (each listed field is optional):
%     msetgs = struct();
%     msetgs.approach.warmstartInner = 1;
%     msetgs.algoInner.init; %[120x1]
%     msetgs.algoInner.maxit = 5000;
%     msetgs.algoInner.stopgEps = 1.0000000000000000e-02;
%     msetgs.algoInner.stopgStride = 1;
%     msetgs.algoOuter.init; %[40x1]
%     msetgs.algoOuter.maxit = 5000;
%     msetgs.algoOuter.stopgEps = 1.0000000000000000e-02;
%     msetgs.algoOuter.stopgStride = 1;


% 
% This file is generated by FiOrdOs, a program licensed under GPL
% by copyright holder Automatic Control Laboratory, ETH Zurich.
% 
% If you are interested in using this file commercially,
% please contact the copyright holder.
% 

